### ISSUE TITLE
Work-week/ Weekly / Monthly repeated schedule

### ISSUE THREAD

**Issue by magillus** [iSoron/uhabits#1]
Great App!
I have suggestion:
It would be great to have additional schedule for active days of the habbit tracking- example to create a habit to write status report for a day - work week (Mon-Fri) by 9pm. It would have a reminder like current ones but it would track this every day only in selected days of a week.

**Comment by iSoron** [comment]
I'm glad you like the app. Just to make sure I understand, you would like to be able to set which days of the week a certain habit is active, so that the check marks only appear during those days, but not the others?

**Comment by magillus** [comment]
That is correct, either quick selection like " work week" (Mon - Fri) or Weekend or more complex: second Tuesday of the month, etc.

**Comment by iSoron** [comment]
Thank you for the suggestion, but I have decided not to implement this feature, since the app is already able to figure out your schedule by itself, given the number of repetitions and interval that you have specified. Please, see the [FAQ][faq] for more details. I do like the idea of having some "quick selections" such as "every day", "every week", etc.

[faq]: https://github.com/iSoron/uhabits/wiki/Frequently-asked-questions#how-can-i-specify-that-a-habit-should-be-performed-on-certain-days-of-the-week

**Comment by gruvw** [comment]
I know this feature request is quite old (sorry to bump), but I figured out it would be better than creating a duplicate.

The app (streaks algorithm) certainly can "figure out" a given day schedule by itself but I think the feature is still relevant for activities you have to do on particular days but you might do additionally when wanted on other days. That currently messes with the ways streaks are counted.

Let's check an example: I have to clean my room every Sunday to start of the week in a fresh and cleaned room, though I might also clean it on Tuesday night after friends came over for a birthday party.
Currently if I check it on Tuesday and don't follow my routine of cleaning on the following Sunday I won't start my week with a cleaned room and have broken my habit. However now the app thinks the schedule has shifted and marks my Sunday as implicitly done. The app now thinks I should clean my room on Tuesdays. Yes I could ignore that and my streak will get automatically lost after I don't clean on the following Tuesday.
However, chances are I will clean it on the next Monday or Tuesday as it would have gotten quite dirty by then, meaning I won't lose my streak on the app (though I should have lost it as I have not respected my "clean on Sundays" goal).

This is a quite detailed example but I find this quite relevant with many of my habits (cleaning, fitness, laundry, play music, stretching, ...). All share a common underlying property of having a fixed planned weekly schedule with additional optional completion days.
