### ISSUE TITLE
See how many times habits I did, instead of how many percentage(%) is achieved

### ISSUE THREAD

**Issue by JoshGraham** [iSoron/uhabits#100]
(Translating some user feedback from Google Play Store)
...If I could see how many times I did habits, instead of how much percentage(%) is achieved. For example, '13times for this month', instead of '45% for this month'.

**Comment by iSoron** [comment]
Hi Josh, thank you for translating the reviews. I believe this is a duplicate of #23. The frequency view should be able to show number of repetitions vs month in the future.
