### ISSUE TITLE
Checking a habit changes cross also to tick

### ISSUE THREAD

**Issue by invinciblevenom** [iSoron/uhabits#1008]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
When we add 7 or more habits and tick any one day/or two then every cross changes into ticks but they are not highlighted. 

## Steps to reproduce
1. Go to App.
2. Click on plus icon and add at least 7 habits.
3. Scroll down to 7th Habit and tick any two day, now the all the cross also become tick but not highlighted.
4. See error.

## System information
 - Phone: Samsung M21
 - Phone Operating System: Android 11
 - App version: 2.0.2

## Screenshots
![Screenshot_20210703-211439_Habits](https://user-images.githubusercontent.com/37961534/124359721-d20e3c80-dc43-11eb-8bd3-e36b60284c6f.png)

**Comment by iSoron** [comment]
Thanks for the bug report, @invinciblevenom. In your screenshot, what is the frequency of habit "oiling"? If the frequency is "2 times per week", then this behavior is expected. Could you try to switch the frequency to "daily" and see if it still happens?

**Comment by invinciblevenom** [comment]
> 
> 
> Thanks for the bug report, @invinciblevenom. In your screenshot, what is the frequency of habit "oiling"? If the frequency is "2 times per week", then this behavior is expected. Could you try to switch the frequency to "daily" and see if it still happens?

At present the frequency has been set to 'Every 3 days". When I changed it to "Daily" it didn't happen.

**Comment by invinciblevenom** [comment]
I understood your point now that why this behavior is expected. Will close this issue now. Thanks!
