### ISSUE TITLE
Exporting Full Back does not provide the option of File Manager

### ISSUE THREAD

**Issue by shouyou10** [iSoron/uhabits#1011]
## Pre-submission checklist
- [√] I am submitting a bug report, not a feature request.
- [×] I have searched for similar issues, but did not find any matches.

## Description
When I try to make full make up options of many unnecessary apps pop-up except the required File Manager.

## Steps to reproduce
1. Go to ... More Options
2. Click on .... Settings
3. Scroll down to .... Export full backup (and click)

## System information
 - Phone: [Samsung Galaxy A30]
 - Phone Operating System: [Android 10]
 - App version: [2.0.2]

## Screenshots
![Imagepipe_0](https://user-images.githubusercontent.com/76897897/124855556-a3bc9400-df98-11eb-9500-01566539dcab.jpg)
![Imagepipe_1](https://user-images.githubusercontent.com/76897897/124855561-a4edc100-df98-11eb-84e7-3d4b032c99f9.jpg)

**Comment by iSoron** [comment]
Thank you for the bug request, @shouyou10. If you are just trying to save the backup to a folder, it's not necessary to share it with your file manager. Loop automatically saves a copy of your backup to the internal storage. See this question in the FAQ:
> **How can I export a full backup of my data?**
> Select the option "Export full backup" on the settings screen. A file will be generated, and you will be asked to choose an app to share it to. If you select an email application, you will be able to send the file as an attachment to yourself. If you select Google Drive, Dropbox or similar apps, you will be able to upload it. A copy of the generated file is also automatically saved on the SD card, inside the folder Android » data » org.isoron.uhabits » files. Be aware that this folder will be deleted when the app is uninstalled. If you would like to keep the backups on the SD card after the app is uninstalled, you should move them to another folder.
