### ISSUE TITLE
Notifications Huawei P20 Pro

### ISSUE THREAD

**Issue by iClaudia8** [iSoron/uhabits#1024]
Description
I have the app installed on a Huawei P20 Pro which is running the latest version of EMUI. I love the app and think it's peerless on the play store, however, I have an issue regarding the app's notifications which are intermittent. 

After a bit of exploring it seems to only play notifications when I'm actually in the app which means that they don't go off at the time they are set to, just the time I open the app.

I have checked the app permissions, that the phone isn't in Do Not Disturb mode and all the usual and not so usual phone settings and can't seem to find a fix.

Interestingly, my Samsung Galaxy Watch doesn't receive the notifications (as it's programmed to only receive notifications when the app is not in use creating a catch 22 in this scenario), but the indicator in the settings on the Gear app on the phone indicate I haven't received a notification on my phone since downloading the app 5 days ago.

I have also signed up for the beta testing to see if a beta version fixed the issue but no luck.

I would greatly appreciate your help and I have sent you a bug report from a time when this occured via the generate bug report option in the app.

Many thanks

## Steps to reproduce
1. Set a notification
2. Await notification

## System information
 - Huawei P20 pro
 - Phone Operating System: [EMUI 10]
 - App version: 2.0.2

**Comment by iSoron** [comment]
Thank you for the bug report, @iClaudia8. Does this still happen if you disable battery optimizations for Loop Habit Tracker in your phone settings? [Here is a guide on how to disable them](https://dontkillmyapp.com/huawei).
