### ISSUE TITLE
Deprecate Timestamp in favor of LocalDate

### ISSUE THREAD

**Issue by hiqua** [iSoron/uhabits#1051]
## Description
As described there: https://github.com/iSoron/uhabits/issues/967#issuecomment-890404662

Timestamp is deprecated in favor of LocalDate, so future changes (such as a possible implementation of https://github.com/iSoron/uhabits/discussions/466) should take that into account.

**Comment by iSoron** [comment]
Closing this in favor of #1075, which explains why is this change necessary, and (many) other related changes.
