### ISSUE TITLE
Introduce a small delay between toggling a check mark and hiding the habit or sorting the list

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#1055]
## Description

When "hide completed" is enabled, the app currently hides the habit as soon as the user toggles a check mark, making it impossible to mark the habit as failed or skipped. We should introduce a small delay between toggling a check mark and hiding the habit, so that the user can toggle through different states.

Originally suggested in #1053.

## Implementation

One potential way to implement this is to modify `CheckmarkButtonView.performToggle`. Instead of calling `onToggle` immediately, we could wait a few seconds before calling it.

```kotlin
    // CheckmarkButtonView.kt
    fun performToggle() {
        value = if (preferences.isSkipEnabled) {
            Entry.nextToggleValueWithSkip(value)
        } else {
            Entry.nextToggleValueWithoutSkip(value)
        }
        onToggle(value) // Delay this call
        performHapticFeedback(HapticFeedbackConstants.LONG_PRESS)
        invalidate()
    }
```

**Comment by hiqua** [comment]
Ideally it should also delay the sort.

**Comment by hiqua** [comment]
The problem with a `sleep` in `performToggle` is that the user does not get feedback that their action had any result. This makes it confusing, and does not help much to correct mistakes. So maybe it's not the right approach.

I think we should keep the feedback for the checkmark from `performToggle` and just delay the habit list refresh itself.

**Comment by iSoron** [comment]
> The problem with a sleep in performToggle is that the user does not get feedback that their action had any result.

For this solution to work, we would need to run `onToggle(value)` asynchronously, instead of just adding `sleep` before it. By the way, I think adding a sleep there would also lead to an "application not responding" warning.

> I think we should keep the feedback for the checkmark from performToggle and just delay the habit list refresh itself.

That could also work.

**Comment by hiqua** [comment]
I think we fixed this in  #1147.

**Comment by iSoron** [comment]
@hiqua Thanks, I'm currently planning to relase this in Loop 2.1. If we have a 2.0.4 release, I might cherry pick it.

**Comment by aubreyz** [comment]
A really terrible delay that messes up the user experience and leads to mis-clicking and lost habits. I really don't want taskings jumping around while I am checking them off. I have lost hours of effort trying to figure out what I just clicked by mistake (hint to users until this is fixed - always check off tasks from lower down on the screen working upwards). I know this is a free app (and a good one), but this is so sad.
