### ISSUE TITLE
Add option to make notifications not dismissible

### ISSUE THREAD

**Issue by woj-tek** [iSoron/uhabits#106]
First of all - thanks for the great app!

I've noticed that the notifications are not really permanent (and I think sometimes get lost, especially after crash).
Would it be possible to make them more permanent (for example like in https://github.com/quarck/CalendarNotification - which is pretty darn good in keeping calendar notifications).

**Comment by iSoron** [comment]
Thank you for the suggestion. Just to make clear, is your suggestion to add an option so that the notifications cannot be easily dismissed?

Also, is the app crashing on your phone regularly? This should never happen. If it is, please send me a bug report.

**Comment by woj-tek** [comment]
Yes, one thing is to avoid easily dismissing it - I think this is done via one notification property (could be configurable)?

The app is not crashing on me (not that I know) but I noticed, that sometimes I haven't seen notification for particular items (not sure why - it's possible that I've somehow dismissed it, or my pocket has done so, therfore above could be handy). In addition I have a feeling that "snoozed" notification doesn't reappear again (but need to observer it more).
I relatively often reboot my phone (let's say 1-2 times a week) or the app is restarted due to an upgrade (which also removes notifications) but I think this was addressed in the latest version (judging by the changelog)

**Comment by woj-tek** [comment]
A bit of update - loop was updated and two reminders simply disappeared...

I would say (and this may be related to #96, I'll add comment there) - unless the notification item is not marked as done or marked as "not completed" persist the notification - i.e. one would have to explicitly mark item as "not completed" to dismiss the notification. Right now opening notification (not marking) opens Loop itself and the particular notification is gone (which can happen accidentaly) - so unless marked the notification should persist (same is done in the linked Calendar Notifications, which made using device calendar notification usable... - you have to explicitly dismiss it or postpone, opening notification opens calendar item but notification remains).

**Comment by riadd** [comment]
Thanks for this cool app!

Having the same problems with disappearing reminders. It feels like most of the time, reminders don't re-appear when snoozing them. Even when not snoozing it is very easy to accidentally dismiss them and forgetting about them. This reduces the usability of the app quite a bit for me, actually making it almost useless for me since having reliable scheduling for my habits is very powerful to me.

Ideally when an alert has been triggered, a non-dismissable notification should appear that has buttons for three actions: snooze, yes, no.

**Comment by woj-tek** [comment]
OK, not sure if this is related or not, but... recently I'm noticing that a lot of notifications (in the morning) are gon, which feels weird.
Background: recently I've started to get up in the morning a bit later, so instead of following normal pattern/timing with notifications they usually accumulated... but recently I get up with about 15 notifications (total), so there maybe some limitation in android? Or doze function?
Metioned CalendarNotification simply groups remaining notificaitons under one with "and x more notifications: list)

Also - this happens quite often to me - accidental tap on notificatios simply open uHabbits, and we have no idea which notification it was - would it be possible to directly open particular item in the list? (this may be moved to separate issue?)

**Comment by iSoron** [comment]
There is an option now to make the notifications sticky (they cannot be swiped away). Tapping a notification now opens the statistics page for that habit, and does not cancel the notification.

The issue with the snooze button will be fixed by #160. I will open a new issue for persisting the notifications across reboots and reinstalls. Thank you everyone, for your input.

**Comment by woj-tek** [comment]
Oh! This is amazing! Thank you a million! :-)

**Comment by woj-tek** [comment]
> here is an option now to make the notifications sticky (they cannot be swiped away). Tapping a notification now opens the statistics page for that habit, and does not cancel the notification.

Just to make sure - the option is in the development, un-released version - correct?

**Comment by iSoron** [comment]
Yes, that's correct.

**Comment by woj-tek** [comment]
OK, so I've updated to the newest version and it works great - I can't easily dismiss item by swiping, it stays open after taping... but there is tiny problem with it: it's not possible to dismiss it altogether - the only possibility to do it is to mark it as completed (and if it wasn't completed I would have to unmark it).

Possibilities:
- third option in the notification (manual dismiss - still less prone to accidents);
- on the habit screen option to mark it as failed for the day and dismiss/remove notification.
