### ISSUE TITLE
Crash StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by licaon-kter** [iSoron/uhabits#109]
Android 6.0.1, 1.5.2 from F-Droid

Worked fine for weeks otherwise and I remember it opening up ok after the last update, now it won't even open: https://gist.github.com/licaon-kter/99a6babaf19da784a085dde33faa1f44

**Comment by iSoron** [comment]
Thank you reporting. I will release a new version fixing this bug soon.

**Comment by licaon-kter** [comment]
Yes I did have a short one, a number.

Thanks.

**Comment by iSoron** [comment]
A fixed version should be available on F-Droid in a couple of days, probably tomorrow. (They only process updates one time every day).
