### ISSUE TITLE
tiny "ok" button in enter value window

### ISSUE THREAD

**Issue by OliverLew** [iSoron/uhabits#1093]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
The "ok" button is small in the window to enter the number from notification.

## Steps to reproduce
1. Setup a habit with measurable target and with notification.
2. Wait for the notification to show up.
3. Click "enter" 
4. See a small "ok" button.

## System information
 - Phone: Oneplus 8
 - Phone Operating System: lineageos 18.1
 - App version: 2.0.3

## Screenshots

![Screenshot_20210901-203558_Habits](https://user-images.githubusercontent.com/12032219/131674248-501cc01d-b430-4fd1-a41c-2a3a5bfa588a.png)

**Comment by hiqua** [comment]
I have only been able to reproduce it on LineageOS, neither on regular Android nor in an AVD. It would be good to rule out a bug from LineageOS before we do any that would impact other devices.

**Comment by saurabhs** [comment]
Can confirm this happening on my device too which doesn't have LineageOS

System information
    Phone: Oneplus Nord
    Phone Operating System: OxygenOS 11.1.5.5 
    App version: 2.0.3

![Screenshot_20210910-130421_2](https://user-images.githubusercontent.com/829233/132818178-cb669859-fdc9-408a-b665-8cf900f2c570.jpg)
