### ISSUE TITLE
I can't import project!

### ISSUE THREAD

**Issue by tellfa** [iSoron/uhabits#11]
Hi, thanks for this great project but i can't import this and show me this error :disappointed: please help me. i need this project for many tutorials.
error image : 
![17](https://cloud.githubusercontent.com/assets/10583945/13562310/6f1a304c-e44c-11e5-82f6-e35f7359602e.PNG)

How to **fix** it?

**Comment by wangchenghao** [comment]
me too！！！

**Comment by iSoron** [comment]
After cloning the repository, you must also initialize and update the submodules. Here is the complete set of commands you need to run to fetch the source from GitHub and build the APK:

    git clone https://github.com/iSoron/uhabits.git
    cd uhabits
    git submodule update --init
    ./gradlew assembleDebug

The APK will be located in `app/build/outputs/apk/`. I will add this to the README file.
