### ISSUE TITLE
Older versions should fail early when trying to import backups from newer versions

### ISSUE THREAD

**Issue by MaelinaM** [iSoron/uhabits#1115]
## Pre-submission checklist
- [/] I am submitting a bug report, not a feature request.

- [/] I have searched for similar issues, but did not find any matches.

## Description
Uninstalled the latest update 2.0.3 to revert back to an older version. Exported database twice to make sure I could restore it before uninstalling. Reinstalled earlier version 1.8.12. The habits were added along with their settings but the entire history is missing. It appears on the exported .csv but not in the app. I'm not sure if this is a feature or a bug. Its definitely present when I click on the habit, just not viewable in the list.  

## Steps to reproduce
1. Update app to latest version. 
2. Export database. 
3. Uninstall app and reinstall earlier version. 
4. Import saved database. 

## System information
 - Phone: [Samsung Galaxy Tab S3]
 - Phone Operating System: [Android 9.0]
 - App version: [1.8.12]

## Screenshots
![Screenshot_20210923-123058_Habits](https://user-images.githubusercontent.com/91230427/134439360-d58907c0-2d7f-4298-975a-3890ef6f1f9e.jpg)
![Screenshot_20210923-123321_Habits](https://user-images.githubusercontent.com/91230427/134439423-b62e05c4-dd18-4fb3-a704-c0cf9ca83743.jpg)

**Comment by iSoron** [comment]
Hi @MaelinaM, thank you for the bug report. Could you please clarify what is the issue in the first screenshot? It looks to me like the data is being displayed correctly. It's just that, in version 1.8, the checkmarks that Loop automatically adds were grey. They became colorful in Loop 2.0.

**Comment by MaelinaM** [comment]
Hello @iSoron thanks so much for getting back to me. I'll try to explain. Instead of the main page, where the list of habits is shown, displaying information history, it shows that I have yet to complete it at all. Its blank - all the way through. Like the flower pot stick habit in the second image, when I'm on the page looking at it, it says I've completed it on so-and-so, but when looking at the main page, there is no check mark on that date. Does that make sense? I can take more screenshots if seeing it would explain it much better!

Also as just an aside if you caught it but I know that the time interval for the flower pot stick habit would not show up on the main page just yet - as in it would have grey checkmarks because the loop hasn't been completed. It was just the first habit I screenshot but its the same for all of them.

**Comment by hiqua** [comment]
Can you give an example of a checkmark that appears in the CSV but not on the screenshot then?

More screenshots could help indeed. In your screenshot, you do have some history (e.g. 22nd of August).

**Comment by MaelinaM** [comment]
Hello, I realized that the database is missing data from the 24th of September onwards and that is why nothing shows up. 

These two screenshots are from 1.8 for a database that was exported yesterday. Nothing appears from 24th of September. 

![Screenshot_20210925-095837_Habits](https://user-images.githubusercontent.com/91230427/134744391-56443e1b-d1c1-4d68-9812-68c77ad25cfd.jpg)
![Screenshot_20210925-095814_Habits](https://user-images.githubusercontent.com/91230427/134744396-b673f288-6ce6-4324-83ae-b5468fa877fd.jpg)

These are the results from version 2.0 with the exact same database

![Screenshot_20210925-100300_Habits](https://user-images.githubusercontent.com/91230427/134744592-74730aac-e187-4a38-a4e0-4879165c9ef2.jpg)
![Screenshot_20210925-100237_Habits](https://user-images.githubusercontent.com/91230427/134744602-52577609-ee08-4bf5-8149-ef23b52ea74a.jpg)

I'm not sure why the data loss is happening.

**Comment by hiqua** [comment]
What does the CSV look like?

**Comment by MaelinaM** [comment]
@hiqua 
Sorry for the delay. I had to locate the entry. Here is a screenshot of the .csv checkmark showing data for 'Pinterest Queue' right up. 
![Screenshot_20210925-102239_Sheets](https://user-images.githubusercontent.com/91230427/134745518-e52390f7-d212-4acd-a30f-1a80b672fa32.jpg)

**Comment by hiqua** [comment]
By the way you import using the full backup, not the csv, right?

**Comment by MaelinaM** [comment]
Hi @hiqua , yes I use the .db file to import the data.

**Comment by iSoron** [comment]
@MaelinaM Could you please confirm that you generated the backup in version 2.0 of the app, then imported it in version 1.8? If that's the case, then, unfortunately, it won't work. Importing a new database into an older version of the app is not supported. Version 1.8 should have warned you that the file is invalid; the fact that it didn't is a bug, and we should investigate the reason.

**Comment by MaelinaM** [comment]
Hello @iSoron , yes that is what happened. I generated the database backup in version 2.0 when the app updated. There was no warning that the file was invalid when I was opening it in version 1.8.

**Comment by iSoron** [comment]
@hiqua The issue was that we didn't increase the database version number in Loop 2.0.x, so Loop 1.8 thinks that the database is compatible. The schema, in fact, didn't change, but our interpretation of the data did, so we should have increased it. This should no longer be an issue in `dev`, since we increased the database version number after merging #1103. Unfortunately, there is nothing we can do now to prevent Loop 1.8 from importing Loop 2.0.{0..3} backups.
