### ISSUE TITLE
Use Storage Access Framework when importing/exporting files

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#112]
When exporting files, we currently generate intents with URI pointing to files, and when importing, we use a custom file picker that is only able to browse a certain folder on the SD card. A better solution, as suggested by @licaon-kter, would be to use the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html), instead. In this way, users could import/export directly from/to cloud storage, for example. Our current solution might also [stop working on Android N](https://commonsware.com/blog/2016/03/14/psa-file-scheme-ban-n-developer-preview.html) and will certainly not work properly on the Chromebook, so this is somehow inevitable.

One issue is that the Storage Access Framework is not available below API 19 (KitKat). We currently support all devices starting from API 15 (Ice Cream Sandwich).

**Comment by regularcoder** [comment]
I will make an attempt at this. I will use conditional execution to support devices below API 19, unless you think that is not necessary.

**Comment by iSoron** [comment]
Hi @regularcoder, are you still working on this? This issue is preventing us from targeting API 24 (Nougat).

**Comment by regularcoder** [comment]
Hi, no I have stopped working on this.

**Comment by iSoron** [comment]
Implemented on `dev` branch. The app now targets API 25 (Android 7.1 Nougat)
