### ISSUE TITLE
CSV archive not generated correctly when habits have special characters in their names

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#113]
Since we are using the name of the habits as the name of the folders when exporting to CSV, the process fails when these names include special characters, such as slashes. For languages other than English, the names of the folders may also become corrupted, since ZIP has poor UTF-8 support. We should sanitize the name of the habits before creating the folders.

This issue was first reported by @aleksejrs.

**Comment by aleksejrs** [comment]
Now only “001” is saved.  I see it spares dots.  My second habit's name is all Cyrillic and spaces, but it ends with a dot…
