### ISSUE TITLE
Show a running total for the number of times a habit has been checked

### ISSUE THREAD

**Issue by dillbyrne** [iSoron/uhabits#115]
It would be nice to able to see the total amount of times a habit has been completed overall. I think it could be added in the overview beside the year with a `total` string.

At most the total number would have a length of 5 (max 99999) if we assume a habit can only be checked once a day. if a human lived to 100 and checked a habit every day it would still only be 36500. 

Thanks for your app , you have done a great job! :+1: for having it in F-Droid too.

**Comment by iSoron** [comment]
Thank you for the suggestion.

**Comment by regularcoder** [comment]
Hi, would you accept a PR for this? If so, i'm interested in implementing this feature.

Please let me know.

**Comment by iSoron** [comment]
Hi @regularcoder, pull requests are very welcome. How are you planning to show this information to the user? I think adding it to the overview, as it was suggested, would be nice.

**Comment by regularcoder** [comment]
Yes, I will add it to overview to the right of "Year".

Will submit PR next week, thank you.

**Comment by dillbyrne** [comment]
Thanks for this  :+1:
