### ISSUE TITLE
Numerical habits are not cumulative and require the goal to be completed in one day

### ISSUE THREAD

**Issue by habitswidget** [iSoron/uhabits#1153]
## Pre-submission checklist
- [y] I am submitting a bug report, not a feature request.
- [y] I have searched for similar issues, but did not find any matches. 

There is another bug report related to measurable habits and the Hide Completed function - I have Hide Completed unchecked throughout.

## Description
I created a habit to run 6km per week and completed 3km on two separate days this week. Widget doesn't mark as complete. But it will mark as complete if I ran 6 today.

## Steps to reproduce
1. Create new measurable habit with a target of 2 or more per week.
2. Create Widget for Habit
3. Mark as complete on 2 days within the week where the sum is equal to or greater than the goal (but neither are on their own)
4. See that the widget has not marked as completed

## System information
 - Phone: Pixel 3a
 - Phone Operating System: Android 11
 - App version: 2.0.3

## Screenshots

<img width="291" alt="Screenshot 2021-10-07 at 13 50 48" src="https://user-images.githubusercontent.com/92097138/136387511-d64e84b9-ca07-43c8-962d-2e969889cd33.png">
<img width="389" alt="Screenshot 2021-10-07 at 13 50 15" src="https://user-images.githubusercontent.com/92097138/136387526-d6713eb9-5513-4164-bf9b-eb8809f10423.png">

Thanks for your help, love the app.

**Comment by hiqua** [comment]
I'm not sure how it was intended, but I think your expectation of being able to reach your goal over several days is common.

It could be that we just have to add one more type of habits, or replace the current one by a cumulative numerical habit instead.

@iSoron what was your initial intent? Should we have a new type of habit, or just change the current behavior to make it cumulative?

To compare with yes/no habits: if you did 10 when your target is 20, you wouldn't check a habit asking "did you do 20 today?". So in a way, the current implementation of numerical habits match these more accurately than a new hypothetical cumulative numerical habit. I probably would prefer a cumulative behavior myself though.
