### ISSUE TITLE
Export to CSV has additional commas that break the import to Excel or similar

### ISSUE THREAD

**Issue by kenxle** [iSoron/uhabits#1162]
Love that you can export data for your own analysis.

However, the export format is a bit... unrefined? Each entry restates the date, followed by a comma, followed by the actual value. This causes import to Excel and similar files to break, because every comma is considered a new column. 
![16347509539984183641693262748657](https://user-images.githubusercontent.com/989596/138142219-a1db56b7-b90f-4412-a2f9-97314c6be22b.jpg)

I can write a regex to change them. But it's a csv export, right?

**Comment by hiqua** [comment]
Thanks! We should have a fix for the `dev` version some time soon, in the meantime the export for the individual habits within the .zip seems to work fine, so you could use that if you're just interested in some habits.

**Comment by jonasW3F** [comment]
Hi
I am experiencing the same issue on version 2.0.3.

<img width="407" alt="Screenshot 2022-12-24 at 12 37 56" src="https://user-images.githubusercontent.com/67730419/209434292-aa4a0904-a3f3-42e1-81c4-795c5a9b097d.png">

R also tells me that there are more columns than column names when trying to use the first row as header.
