### ISSUE TITLE
Measurable habits are always hidden if "hide completed" is ticked (on dev)

### ISSUE THREAD

**Issue by hiqua** [iSoron/uhabits#1179]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
See title.

## Steps to reproduce
1. use the latest version on `dev
2. create a new habit measurable habit with a target of 10
3. check "hide completed"
4. the habit seems to be hidden although it has no data yet

## System information
 - App version: `dev`

Setting `cant-reproduce` label until somebody else confirms I'm not missing anything.

**Comment by iSoron** [comment]
@hiqua Thanks, I see the same issue here.
