### ISSUE TITLE
Cannot select "Every day" in frequency popup

### ISSUE THREAD

**Issue by baincd** [iSoron/uhabits#1182]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
When attempting to change the frequency of a habit, the popup has an option for "Every day" but it cannot be selected

## Steps to reproduce
1. Create new habit
2. Click on Frequency
3. Choose "Every day"
4. Selection automatically goes back to "Every X days"

## System information
 - App version: [e.g. 2.0.3]

## Screenshots
![habits-bug2](https://user-images.githubusercontent.com/5075659/140612586-fbb9c153-f0de-4c6a-a6cd-e4b55490e232.png)

Workaround is to choose "Every [1] days", which is the same thing.  But it is confusing to have an option that cannot actually be selected.

**Comment by iSoron** [comment]
Thank you for the bug report, but we also need the following information:
 - Phone: [e.g. Google Pixel 4]
 - Phone Operating System: [e.g. Android 10]
 - App version: [e.g. 2.0.2]

**Comment by hiqua** [comment]
Seems to work fine on latest `dev`.

**Comment by baincd** [comment]
I tested with the latest on the dev branch, and interestingly if the cursor is in either of the custom frequency input boxes, "Every Day" *can* be selected

![Peek1](https://user-images.githubusercontent.com/5075659/140644951-461dc5aa-3143-4c18-9a01-1237fab9a14c.png)

However, if "Every X days", "X times per week", or "X times per month" are selected, when "Every Day" is selected, the selection automatically goes back to "Every X days"

![Peek2](https://user-images.githubusercontent.com/5075659/140644954-98c3d91e-fd90-48cd-8dd7-980952107819.png)

* Phone: Nexus 5X
* Phone Operating System: Android 8.1.0
* App version: 2.0.3, and dev branch (eb041bf)

**Comment by baincd** [comment]
I tested with the latest on the dev branch (b62e436), and confirmed it exhibits the same behavior I noted above

**Comment by hiqua** [comment]
Thanks! I can reproduce this with a fresh emulator:

* Nexus 5X
* Android 8.1.0

Current `dev.

For some reason, I don't have this bug on an emulator running Android 11 that I've been using for some time.
