### ISSUE TITLE
Skip day do not always maintain score and sequence

### ISSUE THREAD

**Issue by Gbehanzin** [iSoron/uhabits#1183]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
I have a habit that I do 2 times per week. One week, I entered a skip day and on Wednesday and I did the habit on Saturday.  This break the streak and affected the score negatively.

## Steps to reproduce
- Reproduce the streak from the below screenshot.

## System information
 - Phone: Google Pixel 5
 - Phone Operating System: Android 12
 - App version: 2.0.3

## Screenshots
![Screenshot1](https://user-images.githubusercontent.com/22014963/140623899-779546c6-7385-405c-ac4a-14f41c1ff5c5.jpg)

**Comment by hiqua** [comment]
My interpretation: I don't think we have real support for twice a week, but rather twice every 7 days, and from the 5th to the 12th you did it only once, hence the broken streak. If you enter the skip day on the 11th I think it will work..?

**Comment by Gbehanzin** [comment]
Hi Hiqua, it doesn't work even if I put the skip day on the 11th. Also, if for instance, I mark the 13th as completed, it doesn't break the streak. I believe that if the completion day doesn't affect the streak, the skip day shouldn't either.

**Comment by hiqua** [comment]
That's not how we have it, a skip day is just a day where you were supposed to do it but couldn't, but it just gives you some more time to do it, it doesn't replace actually checking a day. So it's working as intended, feel free to discuss on the forum if you'd prefer something else.
