### ISSUE TITLE
Back button after checking a habit clears the checkmark

### ISSUE THREAD

**Issue by abonhote** [iSoron/uhabits#120]
The back button (Samsung Galaxy S7 edge here) shows some pretty weird behaviour in the habits list. After checking off a habit, the back button clears the checkmark again.

**Comment by iSoron** [comment]
Can you please confirm what version of Android and what version of the app are you using? Also does this happen consistently or just sometimes?

**Comment by abonhote** [comment]
Sure. App Version 1.5.4, Android 6.0.1. Funny enough - I can't reproduce it anymore! I'll try a few things and provide feedback.

**Comment by abonhote** [comment]
Ok, I managed to reproduce it. I created a new habit (after deleting all existing), set an alarm. I then opened Loop from the alarm's notification. 

[This video](https://www.dropbox.com/s/z92zapjmortkj8x/2016_06_08_12_39_02_12_42_56.mp4?dl=0) somewhat shows it. The back button happens between 0.08 and 0.09.

**Comment by iSoron** [comment]
Thanks. I think I see the problem. When you open the app from the notification, a new page is displayed on top of the old one. When you press the back button, the new page closes, revealing the old one, which is still showing some old information. If you press the back button again to close the old page and then restart the app, the checkmark should appear. This should not happen, by the way. Thank you for reporting this bug.
