### ISSUE TITLE
Show a progress indicator when loading data

### ISSUE THREAD

**Issue by aleksejrs** [iSoron/uhabits#122]
When I start Loop, it takes time to show all the checkboxes, which can be especially confusing if it happens on a habit page (probably when started from a widget).  Clicking a checkbox or a history cell works unclearly sometimes when the value is not yet rendered.  It may be the reason why my checking of a box sometimes fails as if I misclicked (Loop tells me to hold or opens the page unless I drag a little).

Something like a throbber would probably be enough.

**Comment by licaon-kter** [comment]
Device? Android version? Loop version?

**Comment by aleksejrs** [comment]
Alcatel POP 3 OT-5015D, Android 5.1, Loop 1.5.4.

70 unarchived habits (many are like "woke up before 9:00" as in issue 97).

If I scroll down quickly after starting Loop, I have to wait till the checkboxes appear before clicking to avoid messing up.

**Comment by iSoron** [comment]
There was a progress bar in early versions, but since loading got so fast, I disabled it. I guess we should still show it if loading is taking more than 1 second or so.

**Comment by aleksejrs** [comment]
When adding or editing a habit (like changing a color), checkboxes and moving do not work for some time without any indication.

**Comment by iSoron** [comment]
This has been fixed in the `dev` branch.
