### ISSUE TITLE
Notification check action weird behavior

### ISSUE THREAD

**Issue by StefanDimov** [iSoron/uhabits#123]
I have a habit, get a notification reminder for it. If I don't choose an action and just dismiss it, the next day when I get same reminder - if I choose an action from it, sometimes it performs it on the previous day.

Haven't tested enough to be sure this is the cause, but it's something with the notifications.

Bottom line: Sometimes notifications perform actions not on current day, but on a previous one;

**Comment by iSoron** [comment]
If you press "check", the checkmark is added on the day that the notification appeared. That is, if a notification appears on a Saturday, but you only press "check" on Monday, the checkmark will still be added on Saturday.

In earlier versions of the app, the checkmark was added on the day you pressed "check", but this caused problems with habits that repeated at night, for example. People would often not look at the phone until the next morning, press check, then be surprised that the checkmark was added "on the wrong day".

**Comment by sojusnik** [comment]
I experience the same and find it very confusing.

If I forget to do a habit on f.i. on Monday and Tuesday, and on both days just dismiss the notification (by swipping it away in the notification area), but check the habit notification on Wednesday, then a checkmark will be added to Monday and not to Wednesday, as it actually should do. This is very confusing and currently stops me from using the notifications at all.

Therefore I pledge to restore the old behavior or find another way to cope with this issue.

Nevertheless, keep your great work!

**Comment by iSoron** [comment]
> If I forget to do a habit on f.i. on Monday and Tuesday, and on both days just dismiss the notification (by swipping it away in the notification area), but check the habit notification on Wednesday, then a checkmark will be added to Monday and not to Wednesday, as it actually should do.

This is a bug. The checkmark was supposed to appear on Wednesday, not on Monday. I will release a new version of the app soon (1.5.5) that should fix this problem. Thank you all for reporting this issue.

**Comment by iSoron** [comment]
The new version should be available from F-Droid and Google Play in a few days. When it becomes available to you, could you please try it out and confirm that the problem has been fixed?

**Comment by sojusnik** [comment]
Seems to work fine with the latest version, thanks!

Alinson Xavier <notifications@github.com> schrieb am So., 19. Juni 2016
16:12:
