### ISSUE TITLE
History plot (calendar) confusing filling

### ISSUE THREAD

**Issue by rsuhada** [iSoron/uhabits#124]
First of all thank you for the amazing app! I've tried many and your app is the best for me! Amazing work!

For me the most important feature is the calendar view - I need to see 1-3 months in the past so that I'm really pushed to not break my habbit. This works almost great - I have just one problem:

I have a habbit that I want to do 3x a week - but every week it is 3 different days... The visualization somehow tries to "guess" the schedule, but since it is irregular I end up with a confusing plot:

![screenshot_2016-06-10-13-52-44](https://cloud.githubusercontent.com/assets/818539/15963660/00cb582e-2f14-11e6-88ab-3feaaf5cb9ce.png)

My proposal would be:
1. simple: add an option to disable the automatic filling of days (so that only days where the user does tick the habit are colored, nothing else).
2. bit harder: add "full week" coloring: simply for each **finished** week in the past, check if the target was filled (e.g. in my case 3x the given week) and if yes, fill all the unfilled days in that week (signifying that the week was successful).

Thank you very much. I can say that the calendar widget occupies 1/2 of my home screen :) - it is a strong motivation and a great product!

**Comment by iSoron** [comment]
Glad you like the app. Could you tell me what did you expect to see, instead of what is currently shown? In your calendar, for example, what days do you think should have been highlighted, but were not?

**Comment by rsuhada** [comment]
In the option 1: I'd see only day I ticked - so only the bright green fields, no dark green fields.

In this option the image would look exactly the same as the screenshot, but with no dark green fields at all.

In the option 2: if the week was successful then: bright green for ticked day, dark green for all the others
Example of week starting 3. April: 4, 6, 8 = bright green, 3., 5., 7., 9. = dark green 
(this dark green highlighting could happen on 10. April - i.e. after the week is finished and it is checked that I indeed checked my target of 3).

In this option the plot would have all green (some dark and some bright) fields during weeks Apr. 3/10/17/24 - these were all successful weeks, i.e. these 4 weeks should all look like the week 17. Apr looks now (i.e. all days green = successful week). 

For the rest of the weeks there would be only bright fields where I checked in (but not on the other days).

The second option is more satisfying (you'd see long stretches of green days if you are filling your target), but if it is too complicated, option 1 would work too.

**Comment by aleksejrs** [comment]
My understanding of the problem:

For each day, the highlighting considers only the past days, not the future days (it shows whether it was necessary/helpful to check a box to fulfill the schedule that day).  That incorrectly breaks streaks that are calculated when the state of the following days is known.

**Comment by rsuhada** [comment]
I think so - I actually don't know how the dark fields are calculated and what they signify... in any case for plans with no fixed schedule it is a bit confusing (e.g. compare my week Apr 17 with Apr 10 and Apr 24., all 3 weeks are successful, yet the colors are not consistent between them).

Thank you for considering this issues!

**Comment by iSoron** [comment]
The dark green days correspond to grey checkmarks on the main screen. That is, checkmarks that the app added automatically for you, instead of ones that you added yourself. To add a checkmark, the app looks at the previous 7 days, and counts how many times have you performed your habit. If you have already performed it three times or more, it adds a checkmark.

In your example, there is no automatic checkmark on April 25 because in the previous 7 days (that is, the interval between April 19 and April 25) you only performed your habit 2 times. In this sense, the app is working as intended, and this is not a bug.

I am considering whether to change this algorithm or not.

**Comment by rsuhada** [comment]
Thank you for the explanation. To sum up, I'd propose: to 1) add option to
disable the automatic checkmarks and/or 2) add option to add the automatic
checkmarks based on calendar week, rather than a rolling 7 day window (as
it is now).

I think the current scheme does have a use for some people, so there
wouldn't be a need to remove it.
Thank you again for your time :)

**Comment by LiveBeef** [comment]
I came to this app's git page specifically to raise this issue. If I have a twice-a-week item that I perform Monday-Tuesday one week and Friday-Saturday the next, the app will correctly auto-fill the rest of the first week and then incorrectly mark the first part of the next week as "missed". I see this as a bug. This could likely be fixable by a simple-ish "least misses" algorithm that runs at each change in checkmark. If you don't want to deal with it iSoron, I'll take a crack at it and pr if successful

**Comment by iSoron** [comment]
@LiveBeef Pull requests are very welcome, but I would like to understand your solution better before you start coding it. What do you mean by a "least misses algorithm"?

**Comment by torkelsson** [comment]
How about actually let "5 times per week" mean 5 times per calendar week and "5 times in 7 days" mean 5 times in the last 7 days? When I first tried the app that was how i interpreted  5 times per week. I discovered it by wanting to change it to 3 times per week, but when choosing Custom, it said 5 times per 7 days. 

IMHO don't think it is really possible to really create a "least misses algorithm" that covers all use cases and that it is better to have a "repeat X times in Y days/weeks/months" when creating/editing a habit.

**Comment by LiveBeef** [comment]
I think that distinction would be confusing and unnecessary. To you and
@iSoron, I'm talking about an algorithm that runs every time a checkmark is
added or removed that scans the habit's history to find every day that
doesn't have a checkmark, then considers every permutation of placing
autofilled checkmark that is legal given the habits frequency and picks the
one that results in the largest legal amount of autofilled checks, or the
"least missed dates". I'm on mobile now but I'll see if I can whip up a
picture later to explain. It's an n^2 algorithm if I can't optimize it, but
I might be able to cheat it down.

**Comment by bdambdam** [comment]
I second the idea of 5 times per week to be actual calendar week. Completely confusing to see me reach my goal of 5x per week and seeing the app telling me I'm failing.

**Comment by Hkly** [comment]
If you are going to add the option for week === calendar week, please also keep the rolling `n` day window (as it is now). This is actually a feature that sold me on this app, I really disliked other apps that forced me to use the calendar week.

**Comment by Weygert** [comment]
I would also appreciate to have both options to be set per habit separately since some of my habits are really calendar week driven and some are not. So having the choice would be great. 
I also would like to mention that the streak is interrupted, also I fulfilled my targets without interruption.
E.g. habit once a week (or in 7 days): In week 1 done on Monday, in week 2 done on Tuesday gives me a streak of 7 for the full week 1 (which is also weird since I actually just did it once, but that's another topic :)) and breaks the streak on Monday of week 2.
I set myself targets (e. g. n weeks in a row target fulfilled) where this kind of calculation doesn't really help.

**Comment by Weygert** [comment]
Would like to add one more obstacle I encounter with the current 'rolling n days window'. 
As a workaround to not having the calculation based on calendar weeks, I set for example '3 times in 28 days'. This way I can consider my current target (do it at least 3 times in 4 weeks) and reduce the number of streak interruptions. But now the reminder that I set on a specific weekday is turned silent as long as the automatic checkmarks are set. So it reminds me only the first reminder day where I already ran out of the streak. That is too late. Would be nice if we could set the option to let the reminder pop up regardless of the current checkmark status.

**Comment by dalai4git** [comment]
Here is my take on the problem. 

In the figure below, I have put an `X` for a real repetition of the habit and a `+` for an 'implicit' repetition used for calculating streaks. The goal in this example is 2 times every 7 days. The current algorithm leaves a gap at the end of the first week and in the middle of the third one, which to me is counterintuitive. 

    MTWTFSS|MTWTFSS|MTWTFSS|MTWTFSS|MTWTFSS|MTWTFSS|MT
        X  |X+X++X+|++  X+X|+++X++ |     X+|X++X+  |   Curent algorithm
     +++X++|X+X++X+|++++X+X|+++X+++| ++++X+|X++X+++|+  Rolling window
        X++|X+X++X+|++++X+X|+++X   |     X+|X++X   |   Rolling window with pruning

My suggestion would be to use a rolling window and check seven days at a time to see if we achieved our goal. If so, then this window is part of our streak and all days in it are marked. The results for this are shown on the second row.

Both the current and the rolling window algorithms result in 'implicit' repetitions that seem wrong. For example those at the end of the 4th week. The rolling window algorithm can be easily adjusted to _prune_ these extraneous 'implicit' repetitions giving the results of row 3.

The advantage of both algorithms is that they are not affected by the order repetitions are added. That means, that repetitions can be entered without needing to adjust previously marked 'implicit' repetitions as in the case of looking for all possible permutations. On the other hand, they will not satisfy people that want to base the streaks on calendar weeks. I am including the pseudocode for both algorithms below.

When a new repetition is entered on day `D` and given we want `N` repetitions in `T` days and provided a function `repetitions_in_range` that returns the number of the true repetitions in a range of days:

    for day in D-T+1 to R
        if repetitions_in_range(day, day+T-1) >= N
            mark_range_implicit(day, day+T-1)

For the rolling window algorithm, `mark_range_implicit(start, end)` is:

    for day in start to end
        if not repetition_on_day(day)
            mark_day_implicit(day)

If we also want pruning, then the same function is:

    for day in start to end
        if not repetition_on_day(day) and is_marked(day-1) and repetitions_in_range(day, end+1) > 1
            mark_day_implicit(day)

Note: all ranges include the last item

**Comment by bubal93** [comment]
Yeah, I guess adding an additional option for calendar weeks would be great. It`s really confusing when you selecting "2 times per week" habit, but the algorithm works in the rolling manner.

**Comment by bubal93** [comment]
IDK, but at least it seems like the current algorithm should be corrected. 
On the screenshot below  I have a 2-times-per-week habit. You can see, that periods between 30 Jan to 2 Feb and from 8 Feb to 11 Feb aren`t marked with light green as completed habit. 

![screenshot_20170321-123313](https://cloud.githubusercontent.com/assets/17985872/24401323/3f1715c0-13b4-11e7-8942-8bf6b34e8aa4.png)

Why it`s happening?
I would definitely consider this a bug.

**Comment by bubal93** [comment]
Yet another confusing thing. Lets assume, that you have a habit with not every day repetition (let it be once per week).

So, then you do it, the app marks next 6 days with different color (light green), that shows your "implicit" repetitions.

But why does it count as a full-week streak? If I did some habit once, it **doesn't mean, that I have a 7-days streak.** This is not logical.

Suggestions - count "implicit" repetitions only if you have done your real repetition inside implicit repetition margin. 

_e.g:_ once per week habit completed in 1 Mar and  6 Mar - you get a six-day streak.

**Comment by iSoron** [comment]
Thank you for the feedback, everyone. I have reworked the way checkmarks are automatically added. The app will now try to avoid leaving gaps in your history. Below, for example, is a habit that should be performed two times per week. These changes should be available in version 1.8.

![checkmarks](https://cloud.githubusercontent.com/assets/4699657/26758985/6c661f74-48bd-11e7-9758-cb6f7e2cc11d.png)

**Comment by fin0** [comment]
Wow great! :) Was always wondering about the current behaviour.
