### ISSUE TITLE
Android Edge-to-Edge content

### ISSUE THREAD

**Issue by EricHier** [iSoron/uhabits#1247]
### Discussed in https://github.com/iSoron/uhabits/discussions/1246

<div type='discussions-op-text'>

<sup>Originally posted by **EricHier** December 27, 2021</sup>
It would be awesome if you could configure the app in a way, that it also displays the content behind system bars. This just looks way better! The Android developer doc about that is available [here](https://developer.android.com/training/gestures/edge-to-edge). </div>

I would love to help but have not enough experience with Koltin & Android to help with development in any meaningful way. But I can definitely test PRs on my Pixel (which has these bottom navigation bars)!

**Comment by iSoron** [comment]
Let's keep this discussion in #1246.
