### ISSUE TITLE
Allow some habits to receive a checkmark automatically at the beginning of the day

### ISSUE THREAD

**Issue by ghost** [iSoron/uhabits#125]
just a thought. maybe some habits would be better suited if there was an option to have the checkmarks ticked automatically instead of having to do it manually every day? for things were you know you will be doing them most days of the week and only be missing every once in a while. it would be easier in those cases just to untick the habit whenever you miss it.

one example im thinking of is trying to give up chocolate. sometimes i might go weeks without having some, but it means that i still have to go to the app every day and hit the button. its not really a problem with just one, but when there is a whole screen of habits that have to be ticked off each day it can start to seem like a chore.

**Comment by pymai** [comment]
actually on second thoughts, you can delete this if you want. i just noticed you might be adding tasker support at some stage so being able to automatically tick off certain habits using tasker would work just as well

**Comment by iSoron** [comment]
I think this is an interesting feature, even if we have Tasker integration.

**Comment by battaglr** [comment]
I don't agree with this, maybe because I'm failing to understand.

The key idea is to create positive habits, like "chocolate free", then you will mark it as done if you didn't eat any chocolate that day, helping you to make that habit stronger with a positive reinforcement.

If you already have incorporated that habit (if you go for weeks without having one you have succeed), I don't see the point in tracking just your failures.

**Comment by brunosabenca** [comment]
Even though a habit might already be established, I still find value in keeping track of its streak. 

Particularly for things that consist on abstaining from something, not wanting to break a long streak of success can help prevent a relapse and while you might not need (or want) to mark a habit manually everyday it can still be beneficial to look at the entry every once in a while, maybe in a moment of weakness, and see how far you have come.

**Comment by YPetremann** [comment]
Ticking on an abstraining habit is quite painfull, but ticking when you do the "forbiden task" is easier, just need to be serious.

**Comment by devurandom** [comment]
This might be one way to solve #96.
