### ISSUE TITLE
Pebble integration

### ISSUE THREAD

**Issue by torkelsson** [iSoron/uhabits#126]
I would be nice to have some Pebble integration. See https://developer.pebble.com/

**Comment by iSoron** [comment]
Thank you for the suggestion.

**Comment by iSoron** [comment]
What kind of integration do you think it would be interesting to have with Pebble?

Currently, the notifications already show up on the watch. Unfortunately, they are not actionable (that is, you cannot toggle them from the watch). Looking over the docs, it seems we would have to use the Pebble Timeline to implement this feature, and this would require either a complete watchapp, or a web server. Is this the case? We can't simply send an Intent back to Android?

If anyone is more experienced with Pebble development, I would like to hear your opinion.

**Comment by that0n3guy** [comment]
@iSoron Are you sure you need timeline integration?   This (https://developer.pebble.com/blog/2014/12/19/Leverage-Android-Actionable-Notifications/) makes it look like you just need to change up the notifications ([example](https://github.com/iSoron/uhabits/blob/a998a62cdbe639c7cfed6ba47f683b8fa6d6b3a2/app/src/main/java/org/isoron/uhabits/notifications/NotificationTray.java#L204)) a little.

**Comment by iSoron** [comment]
@that0n3guy Thank you for the link. We already have actionable notifications. They show up properly on Android Wear, but not on Pebble. Comparing their code snippet with ours, it seems the only difference is that they are adding the actions to the WearableExtender. I will see if this makes any difference, although, according to the Android documentation, it shouldn't.

**Comment by that0n3guy** [comment]
@iSoron  I have a pebble time and can test if you want.   Also, if adding the actions to WearableExtender doesn't work, I'll try to get a hold of pebbles dev's and try to get them to comment.

**Comment by iSoron** [comment]
Yep, that simple modification made it work. We can now check/snooze habits from the Pebble. Thank you for the hint, @that0n3guy.

**Comment by that0n3guy** [comment]
Sweet.  Thanks @iSoron!
