### ISSUE TITLE
Import of HabitBull data assumes all habits are daily yes/no and mis-imports numeric value habit scores as No

### ISSUE THREAD

**Issue by schmerg** [iSoron/uhabits#1265]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
HabitBullCSVImporter only recognises the value of 1 in the "values" column of a HabitBull CSV file to be a "YES" and any other value, such as for habits with scores, is considered to be a "NO" (HabitBullCSVImporter.kt line 80). At worst it should score any non-zero value as a YES, and ideally it would change the type of habit from a yes/no into a measurable habit on the first imported row with a value greater than 1

## Steps to reproduce
1. Import a HabitBull CSV file with a habit where the "value" filed (column 5) contains values greater than 1
2. See that the habit is imported but as a yes/no habit and all days with scores other than 1 have been imported as No.

## System information
 - Umidigi F1 
 - Phone Operating System: Android 9
 - App version: 2.0.3

**Comment by hiqua** [comment]
Can you attach a sample csv file?

**Comment by schmerg** [comment]
Sure thing, file attached with 2 habits (one measurable and one yes/no) but also for ease of reading, here's the first few lines

```
HabitName,HabitDescription,HabitCategory,CalendarDate,Value,CommentText
Pushups,,Fitness,2021-09-01,30,
Pushups,,Fitness,2021-09-02,30,
Pushups,,Fitness,2021-09-03,25,
```

[HabitBull CSV Data File Export.csv](https://github.com/iSoron/uhabits/files/7835223/HabitBull.CSV.Data.File.Export.csv)

**Comment by hiqua** [comment]
https://github.com/iSoron/uhabits/pull/1278 should be more or less ready, feel free to have a look / comment.

**Comment by schmerg** [comment]
I'm not a java dev but it looks like the sort of thing I'd expect to see, and I can see the test case too... will add a further comment once deployed and I can confirm it's working "in the field"
Many thanks...
