### ISSUE TITLE
Gather steps from external sources.

### ISSUE THREAD

**Issue by torkelsson** [iSoron/uhabits#127]
Related to #6 and #17 (so please close this if you think they overlap too much). 

It would be nice to have some way to get for instance step count from Google Fit (or any other source), and if I have walked more steps than the goal I have set in Loop Habit Tracker, the checkmark is automatically set.This is possible in for instance Habitbull. 

This could probably be made more generic, maybe as some kind of plugin interface. Where you set the goal in LHT, get the data from an external source and update the checkmark if some condition is met.

**Comment by iSoron** [comment]
Thank you for the suggestion. My preferred solution, at least for now, is #6. That is, if you want integration between apps, you can write a Tasker plugin or something similar, but I will revisit this in the future.
