### ISSUE TITLE
Max no. of days has reduced to two digits

### ISSUE THREAD

**Issue by johnsonmlw** [iSoron/uhabits#1285]
## Pre-submission checklist
- [x ] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
An Loop Habit Tracker update has reduced the maximum number of days (every xxx days) to two digits (now max. days of 99, previously allowed three digits e.g. 180 days)

## Steps to reproduce
1. Go to "+"
2. Click on "Yes or No"
3. Select second radio button: " Every xx days"
4. See that it now only accepts two digits (e.g. 99), previously three digits (e.g. 180)

## System information
 - Phone: Motorola G7 Power
 - Phone Operating System: Android 10
 - App version: 2.0.3

**Comment by hiqua** [comment]
Yes it's unfortunate, but it's been reverted in `dev` and should be available in the next version. Thanks!

**Comment by johnsonmlw** [comment]
Excellent. Thank you very much. Such a great app.
