### ISSUE TITLE
Remember time of day a habit was fulfilled and graph it

### ISSUE THREAD

**Issue by LuccoJ** [iSoron/uhabits#129]
Sometimes you only tick habits towards the end of your day, or when the alarm reminds you, but sometimes you want to tick them immediately after fulfilling them. If you do the latter, it can be interesting to know when, during the day, you tend to fulfill your habits.

For UI simplicity, I wouldn't make it possible (or at least default) to manually specify the time, but I would simply make the application remember the time a habit was ticked. Then, in the statistics view, there could be a "Time of day" view along with "Weekly" etc, with the hours when the habit tends to occur the most having peaks in the graph.

**Comment by iSoron** [comment]
Thank you for the suggestion, and sorry about the delay to reply. I am still considering it. In any case, I think the app should only display some data if it also allows you to modify it, so this feature would require changing the UI somehow.

**Comment by LuccoJ** [comment]
How about a long tap anyway? In the following way:

* if short tapping is being used, then long tapping will show a clock and you can change the time
* if long tapping is being used, then of course it will cause the habit to be ticked, but then if it's long tapped again, instead of being unticked immediately, a clock appears, including a button to "remove" (untick)

**Comment by evegeris** [comment]
How about a feature you can toggle under Settings like long-tap vs, short tap that will prompt the user to enter more information when they check off a habit? In this window, there could be optional fields for duration, record time of day, user notes, etc. If this information is stored in the database, a chart could later be added to the Habit information Activity for tracking time of day. A message box could also be brought up when a given day is clicked in the history chart that would display any entered information for that day.
