### ISSUE TITLE
Weekly Prompt: "OK" button quite small

### ISSUE THREAD

**Issue by enqueue** [iSoron/uhabits#1298]
I have a habit set up for a weekly numeric check ("how often did you practice yoga this week?"). Everything is working fine, but I wonder if the "OK" button is intentionally small. To me this looks rather curious.

![Screenshot_20220220-200108](https://user-images.githubusercontent.com/5407006/154859902-88c37f45-466c-473f-81e7-8dbd716ce08d.png)

I am running Android 10 on a Nokia device, without any exotic customizations.

**Comment by kalina559** [comment]
I think this might have been solved with this #1096, but it hasn't been include in a release yet. Is that right @iSoron?

**Comment by iSoron** [comment]
@kalina559 That's right; this issue has already been fixed in #1096.
