### ISSUE TITLE
Fix usage of singular/plural in alert messages

### ISSUE THREAD

**Issue by brdvlps** [iSoron/uhabits#131]
A minor mistake: After deleting a single habit, I got the message habits (notice the plural) successfully deleted. This confused me and I had to check twice to make sure I haven't made unwanted changes.

Language: German

**Comment by aleksejrs** [comment]
See also issue 132.

**Comment by iSoron** [comment]
Thank you for reporting this issue. I guess there are other messages that would also need to be corrected.
