### ISSUE TITLE
Auto backup missing in android 12

### ISSUE THREAD

**Issue by mshuflin** [iSoron/uhabits#1324]
## Pre-submission checklist
- [x ] I am submitting a bug report, not a feature request.
- [ x] I have searched for similar issues, but did not find any matches.

## Description
Automatic backup does not appear to exporting daily as expected. (#178) 
There is no folder here:
`/storage/Android/data/org.isoron.uhabits/files/Backups/`

Manual backups work fine
 
## System information
 - Phone: Google Pixel 4xl
 - Phone Operating System: Android 12
 - App version: 2.0.3

**Comment by mshuflin** [comment]
This was caused by a permissions issue with my file manager app, export is working fine

**Comment by iSoron** [comment]
Thank you for the update, @mshuflin.
