### ISSUE TITLE
When set goal of 0, value has to be bigger than 0 to be displayed in color

### ISSUE THREAD

**Issue by Lilo122** [iSoron/uhabits#1327]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
When I set a goal of 0 (f.e. for anxiety) and I set the value to 0 (having not had anxiety that day) the value stays grey in the overview.

Imho it should be colored bc the goal is met.

(Idea to improve the app: it would be nice to configure when a goal counts as met when it comes to measurable habits. Examples could be "0", ">0", "<0,05", "4-8", "3,6,7")

## Steps to reproduce
1. Make a measurable habit
2. Set goal to 0
3. Set value to 0

## System information
 - Phone: [Sony XZ 1]
 - Phone Operating System: [Android 7]
 - App version: [2.0.3]

**Comment by iSoron** [comment]
Thank you for the bug report, @Lilo122, but goals with value zero are not supported. Future versions of the app should prevent zero from being entered as a goal.
