### ISSUE TITLE
Remove deleted habits immediately from the list

### ISSUE THREAD

**Issue by aleksejrs** [iSoron/uhabits#133]
This would be less of a problem with issue #132 (Say which habit was / will be deleted.) fixed.

**Comment by iSoron** [comment]
Thank you for the suggestion. Just to make it clear, the habit already disappears automatically from the list after a few seconds; that is, the user does not need to reload the list manually.

But you are right that, we don't need to wait until the delete operation finishes; we can hide it from the list immediately.
