### ISSUE TITLE
List of habits becomes unresponsive when data is loading

### ISSUE THREAD

**Issue by aleksejrs** [iSoron/uhabits#134]
Since updating from v1.5.4 to v1.5.6.

**Comment by iSoron** [comment]
Could you describe the steps to reproduce this issue more clearly? I can't reproduce this issue here.

**Comment by aleksejrs** [comment]
From memory (repeated many times today):
1. Scroll the list, check a box.
2. Wait till the device locks itself.
3. Unlock (entering a code).
4. Try to check another box.

Maybe it was reloading the list, but it seemed to take too long for that.

**Comment by aleksejrs** [comment]
Now "go to one habit, press Back, go to another habit" takes a long time for at least the second habit's data to show up.

**Comment by iSoron** [comment]
Okay, you are probably experiencing this because the list is getting updated more frequently now. The bug here is that the list should still be responsive, even while the data is loading. That is, you should still be able to click things and add checkmarks. Thank you for reporting.
