### ISSUE TITLE
Habit Repeat - Custom Option

### ISSUE THREAD

**Issue by tribeirom** [iSoron/uhabits#135]
I can set a new habit to:

1) Every Day
2) Every Week
3) 2 times per week
4) 5 times per week
5) Custom

When I click on Custom I have a new dialog asking me to tell the app the amounts of times in a "day". Wasn't it suposed to be "weeks" instead of "days"?

I mean. I wanna set a new habit for 4 times in a week and not 4 times in a day. Also I guess it makes no sense since the app does not have this feature (times/day).

**Comment by aleksejrs** [comment]
There is a field so you can set it to any amount of days 1-99.

**Comment by iSoron** [comment]
You can set the frequency to "4 times in 7 days". This is equivalent to "4 times per week". The interval is measured in days to allow for more irregular schedules, such as "2 times in 3 days" or "1 time in 10 days". I will consider adding this to the FAQ.
