### ISSUE TITLE
Stack Widget miss after reboot

### ISSUE THREAD

**Issue by zouzhenglu** [iSoron/uhabits#1358]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [ ] I have searched for similar issues, but did not find any matches.

## Description
The  Stack widget in the lanunch always miss.  I don't know if  it's because of the reboot.
Now ,I can see the tips : "Check mark Stack widget", ""History Stack Widget".
And it's normal for the widget only one habit.

## System information
 - Phone: [Honor 20]
 - Phone Operating System: [e.g. HarmonyOS2.0.0]
 - App version: [2.0.3]

## Screenshots
![Screenshot_20220424_090903](https://user-images.githubusercontent.com/3361051/164951410-37efab3a-7fff-470f-b7b6-c2bfad8b84a4.jpg)

**Comment by iSoron** [comment]
Thanks for the bug report, @zouzhenglu. I heavily suspect this is actually an Android bug related to widget collections. Unfortunately, Android makes this almost impossible to debug, so I am closing it as wont-fix.  As a workaround, starting in Loop 2.1, you can refresh all widgets by simply re-launching the app.

If re-launching does not fix the missing widgets in Loop 2.1, please let me know.
