### ISSUE TITLE
Allow to Archive multiple habits at once, as can currently do with delete.

### ISSUE THREAD

**Issue by SherylHohman** [iSoron/uhabits#136]
If one habit is selected, I can either archive it, or delete it.

However if multiple habits are selected, my only option is to delete them.
It would be nice to also have the option to archive them.

(small enhancement, low priority) 
(also: relates to issue 131 and 132)

**Comment by iSoron** [comment]
Hi Sheryl, I can't reproduce this issue. When I select multiple **unarchived** habits, I see three actions: change color, archive and delete. The "archive" only disappears when I select some archived and some unarchived habits. This was deliberate, to avoid confusion.

**Comment by SherylHohman** [comment]
v 1.5.6 - the latest that is available in the Android Play store.

I'll attach screen shots.

**Comment by SherylHohman** [comment]
![screenshot_2016-06-24-15-53-50](https://cloud.githubusercontent.com/assets/8204778/16352663/5927fc0e-3a25-11e6-8d5e-b67db82b096a.png)
![screenshot_2016-06-24-15-55-03](https://cloud.githubusercontent.com/assets/8204778/16352664/592e7b9c-3a25-11e6-8b23-13cbf2358c9a.png)
![screenshot_2016-06-24-15-55-14](https://cloud.githubusercontent.com/assets/8204778/16352665/592f4694-3a25-11e6-987e-241cf4561d1e.png)

**Comment by iSoron** [comment]
Can you take a screenshot before you open the menu? There should be two icons on the toolbar: the first one changes color, and the second one archives the habits.

**Comment by iSoron** [comment]
Please let me know if this is still an issue.
