### ISSUE TITLE
"Show question marks for missing data" stopped working after using widgets

### ISSUE THREAD

**Issue by Jessipoo451** [iSoron/uhabits#1366]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
The "show question marks for missing data" setting worked correctly, until widgets were added to the phones homepage, when it then stopped working in the app. Holding the habit checkmark just toggles it between tick and cross, no question mark, despite this setting still being toggled 'on'. Question mark option also is not available on widget but I don't know if that's a bug or a feature.

## Steps to reproduce
1. Go to settings
2. Toggle "show question marks for missing data" on
3. Add checkmark widget to phone homescreen
4. Return to app
5. Question mark feature no longer works, but is still toggled on in the settings

## System information
 - Phone: Samsung Galaxy M30s
 - Phone Operating System: Android 11
 - App version: 2.0.3

## Screenshots
Not applicable

**Comment by iSoron** [comment]
Hi @Jessipoo451, in Loop 2.0, the toggle only cycles between YES, NO and SKIP. Starting in Loop 2.1, you will be able to also select a question mark.

**Comment by Jessipoo451** [comment]
Sorry, I'm confused. I'm using version 2.0.3 and the question mark function is working. It does indeed cycle between YES, NO, and question mark. It worked fine until I used a widget as described in the issue post, but it started working again shortly after.
