### ISSUE TITLE
Usability of measurables: number dial changes position

### ISSUE THREAD

**Issue by paksnuk** [iSoron/uhabits#1386]
## Description
Changing the value of a measurable unit has a usability issue: as soon as you touch the number dial, the keyboard disappears and therefore the position of the widget changes. I suggest not enabling the keyboard by default or keeping the keyboard visible even when using the dial.

In general, adjusting the value of a measurable habit for increments (integer tracking, think *glasses of water*) is annoying:
- I can keep track of the previous value and enter the next one, which is obviously error prone and inconvenient
- I can use the dial to spin to the next value. This is kind of buggy in my opinion because as soon as you touch the dial it changes position and automatically changes the value, so I have to be careful about the value, similar to entering the number on the keyboard.
- Adding a +1 increment for the habit as suggested in the discussions would workaround my problem.

## Steps to reproduce
1. Long press on a measurable habit.
2. Touch the number dial to change the value; the position of the dial widget changes as the keyboard input disappears.

## System information
 - Phone Operating System: Android 12
 - App version: 2.0.3

**Comment by hiqua** [comment]
The dial is now removed on the latest version on `dev`, you can follow https://github.com/iSoron/uhabits/pull/1372 for the next release.
