### ISSUE TITLE
Shows tomorrow's habit

### ISSUE THREAD

**Issue by alittlebitofit** [iSoron/uhabits#1388]
## Pre-submission checklist
- [✔️] I am submitting a bug report, not a feature request.
- [ ✔️ ] I have searched for similar issues, but did not find any matches.

## Description
App shows tomorrow's habit in the notification and therefore it cannot be checked `Yes` or `No`. Only `Later` button is enabled.
Also, I had not marked the Habit as `Yes` or `No` for today.

## Steps to reproduce
How do I explain this? Just slide down notification bar?

## System information
 - Phone: Samsung Galaxy M31s, One UI 4.0
 - Phone Operating System: Android 12
 - App version: 2.0.3

## Screenshots
![Shows tomorrow's habit](https://user-images.githubusercontent.com/42311431/170195184-c0e199fc-2cbf-4fb6-a4d5-348c00beb4a2.jpg)

**Comment by hiqua** [comment]
Did your time change? I had this situation when the clock changed, so the notification was triggered, but can no longer be acted on. So while it's a bug, it should be relatively rare.

**Comment by alittlebitofit** [comment]
I didn't change anything and this is not the first time.

**Comment by alittlebitofit** [comment]
I don't remember.

**Comment by iSoron** [comment]
Thank you for the bug report, @alittlebitofit, but we unfortunately don't have enough information to act on this issue. If anyone else is experiencing this problem, please let us know.

**Comment by iSoron** [comment]
Closing due to insufficient information. If anyone else is experiencing this, please let us know.
