### ISSUE TITLE
Widgets gone in latest update

### ISSUE THREAD

**Issue by nouser321** [iSoron/uhabits#139]
The app works fine but all the mobile widgets have all disappeared. They are no longer even available in my list of widgets. I have several habits and the widgets worked before the last update.

**Comment by iSoron** [comment]
I have not made any changes to the widgets since the last version. I know that the widgets disappear from the list if you mode the app to the SD card. Have you done that, by any chance? If not, could you please send me a bug report from within the app (Settings / Generate bug report)?

**Comment by nouser321** [comment]
I think you're right about it being an SD card issue. Is it possible to have the widgets if the apps on the SD card?

**Comment by iSoron** [comment]
Unfortunately, it's not possible. Widgets are not the only thing that will stop working, by the way. Reminders, for example, may also stop. This is a limitation of Android itself, and there is nothing we can do about it. Here is a [long list of features][1] that will break when an app is moved to the SD card.

I'm curious how did you manage to move it to the SD card, though. This should not be possible. Are you using an app such as Lucky Patcher, or maybe some customized version of Android?

[1]: https://developer.android.com/guide/topics/data/install-location.html#ShouldNot

**Comment by nouser321** [comment]
Thanks for the information. Its an unmodified version of Android on Vodafone smart turbo 4. All I did was go to the app menu in setting and selected "Move to SD Card".
