### ISSUE TITLE
Clicking on Export closes the Settings page before opening Sharing menu

### ISSUE THREAD

**Issue by alittlebitofit** [iSoron/uhabits#1404]
## Pre-submission checklist
- [Yes] I am submitting a bug report, not a feature request.
- [Yes] I have searched for similar issues, but did not find any matches.

## Steps to reproduce
1. Open Settings.
2. Click on Export (full backup or CSV).

Settings page is closed before the Sharing window pops up.
It should stay open.

## System information
 - Phone: Samsung Galaxy M31s
 - Phone Operating System: Android 12
 - App version: 2.0.3

**Comment by hiqua** [comment]
Which phone?

Just tried it on an Android 12, seemed to work fine.

Given #1399 I wouldn't be surprised if we do something wrong with the db files somewhere that would lead to this bug as well.

**Comment by alittlebitofit** [comment]
@hiqua Sorry, its "Samsung Galaxy M31s" and I added it in the report now.

Also, I never faced a crash. Although there have been other issues.

**Comment by kalina559** [comment]
Hey, I managed to reproduce the issue on Samsung A52 (Android 11). It's happening in a freshly installed app and I don't see any errors in the logs. I'll investigate some more :)

**Comment by kalina559** [comment]
I think this is just the way the app was designed - when opening settings, this code is executed: activity.startActivityForResult(intent, REQUEST_SETTINGS) and then we get a result from SettingsActivity (look up RESULT_EXPORT_CSV to see this flow).
So I don't think it's really a bug.

**Comment by iSoron** [comment]
@kalina559 I agree. That's intentional behavior.
