### ISSUE TITLE
"Per week" is a misnomer

### ISSUE THREAD

**Issue by TenshiZA** [iSoron/uhabits#1405]
![Screenshot_2022-06-12-18-25-41-635_org isoron uhabits](https://user-images.githubusercontent.com/29746234/173243107-371b1157-0e89-4ee8-ad6d-81a1be695cc3.jpg)

The chain broke, its set as 3 times per week and its clearly correct but the chain still broke. My start day is set as Monday

**Comment by hiqua** [comment]
3 times per week is a misnomer and it's rather 3 times per 7 days...

**Comment by TenshiZA** [comment]
Thanks I see what you mean now that I had a look after your comment.

**Comment by iSoron** [comment]
The streak is broken because Loop uses rolling weeks instead of calendar weeks. Pull requests implementing calendar weeks are welcome; but, in any case, the behavior described here is intended and not a bug.
