### ISSUE TITLE
Frequency input limited to two digits

### ISSUE THREAD

**Issue by Boefjim** [iSoron/uhabits#1412]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
Frequency no longer supports inputing more than 2 digit numbers

## Steps to reproduce
1, Create a task
2. Click on frequency
3. Select Every X days
4. Attempt to enter a number higher than 99 (for example, 365 for a task that needs to happen only once a year)
5. The third digit will not be added to the input field

## System information
 - Phone: Nord 2 5G
 - Phone Operating System: Android 11
 - App version: 2.0.3

## Screenshots
Input being limited to 2 digits
![input limited to 2 digits](https://user-images.githubusercontent.com/16748131/175780782-6032b773-66e4-481d-a805-36eb47eb06a6.jpg)

A task made before the update, which did allow 3 digit frequency
![task with 3 digit frequency](https://user-images.githubusercontent.com/16748131/175780785-218e04cf-dde8-4887-848c-95d78bf719d9.jpg)

Trying to edit the task that has an original 3 digit frequency of 365 days (it cuts out the third digit)
![task with 3 digit frequency being edited](https://user-images.githubusercontent.com/16748131/175780788-4f96a98d-490b-4f40-bb2a-1a9bee309287.jpg)

**Comment by hiqua** [comment]
Thanks! Fixed on `dev`, and we're waiting for the next release.
