### ISSUE TITLE
Bug: the habit IS DELETED without ask when setting a value on 10-July (today column)

### ISSUE THREAD

**Issue by caos30** [iSoron/uhabits#1429]
I'm using this app since more than 6 months. I love it. Thanks!
But, TODAY i keep pressed the empty value (cross X) of today column (2022 July 10 ) to precisely get MARKED that value for that habit & day column BUT instead of appear the expected tick, the row of the habit disappeared (with a nice movement to up), just as i had ask to remove it !!!???

LOL... i forgot my records of 6 months for that habit :-( 
I know that this is an opensource app, and i know that i should have weekly (daily?) backups, but you know... :-(

So, i suspect that it can be due to:

a) last version of the app (2.0.3 with Android 10, MIUI 12.0)
b) an old existing bug that it arises just today (10 of month 07 ??? maybe this has an undesirable effect on the app)

Note: after get deleted my 6-month habit i've added a new habit and try to marked as DONE and the result is ALWAYS the same... curiously, only when i try to set the value of today (10/July) but not other previous days on this week.

Note2: upss... i've tested another thing now. I've added a numeric-habit and tried to set a value in the today column, and it happened the same result: 1) emerged the popup dialog to specify a decimal numeric value, and 2) after tap the save button then the habit has been removed :-(

**Comment by hiqua** [comment]
Can you double-check that you don't have "Hide completed" ticked? In the second icon starting from the upper right.

**Comment by caos30** [comment]
Ohhhhhhhh!!!!! i never had "seen" that button !? upss... :-(
You're right: that "hide completed" mark was ticked!!
I suppose that i did it accidentally, who knows... moving the phone without see the screen or sometimes the cable of the earphones slightly touch the screen and it causes changes on my apps!

By the way: very interesting this option to HIDE completed habits. Although maybe it could be confusing to have the habits changing of position along the day... Won't one spend more time searching for a specific habit than if they were all always in the same position? I'm sorry, is my "usability" opinion. 

Cheers. I will close the "issue".

**Comment by caos30** [comment]
Indeed, i've been thinking about a suggestion to improve the usability and avoid future people having the same problem than me: it would be desirable to have a way to show to user that are COMPLETED HIDDEN habits.

I have had 2 ways/suggestions:
 - change the color/form of the "filter" icon (second at right-corner top)
 - show a message at top or bottom of the habit list saying something like "(there is COMPLETED HABITS hidden)"

Cheers!
Sergi

**Comment by hiqua** [comment]
Thanks for the suggestions!
