### ISSUE TITLE
Add package to F-Droid

### ISSUE THREAD

**Issue by patcon** [iSoron/uhabits#143]
Just discovering this app, and am absolutely stoked that it's open source! Thanks!

Might you consider allowing it to be hosted on F-Droid, if someone else helps prepare it for packaging?

### References

* [Official Site](https://f-droid.org/)
* Article: [Copperhead, Guardian Project & F-Droid To Build Secure Mobile Ecosystem](https://www.deepdotweb.com/2016/04/03/copperhead-guardian-project-f-droid-partner-build-secure-mobile-ecosystem/)

**Comment by licaon-kter** [comment]
wat https://f-droid.org/repository/browse/?fdfilter=habit&fdid=org.isoron.uhabits ?

**Comment by patcon** [comment]
heh. oops. searched the issue queue for variations of "fdroid", and didn't see it :)

**Comment by iSoron** [comment]
Yeah, the app has been available at F-Droid for a while. Thank you for replying to other users, @licaon-kter.
