### ISSUE TITLE
Score calculation for numerical habits is incorrect

### ISSUE THREAD

**Issue by lisamatule** [iSoron/uhabits#1433]
## Pre-submission checklist
- [✓] I am submitting a bug report, not a feature request.
- [✓] I have searched for similar issues, but did not find any matches.

## Description
A numerical habit's score does not decrease on days the goal was not reached. It will gradually progress from 0% to 100% over time, no matter what the actual success/failure rate is.

## Steps to reproduce
1. Create a numerical goal.
2. Fail to do the goal, but record 0.
3. Given enough time, the goal score will reach 100%

Alternatively: 
go to a date in the past on a numerical goal, add an entry of 0. 
It takes a little over two years for it to hit 100% from the earliest entry.

## System information
 - Phone: pixel 6 pro
 - Phone Operating System: Android 11
 - App version: 2.0.3

## Screenshots
![Screenshot_20220718-122523](https://user-images.githubusercontent.com/10571694/179559748-e93f95e2-13eb-4985-adf8-023e76379a4a.png)

I added historical data from June 2015 to this goal. I noticed the score was wrong, and figured it was because I had some very high values. I went back in, and set those to 0. Now, the goal is permanently at 100%, because the earliest entry is in 2015.

![Screenshot_20220718-124428](https://user-images.githubusercontent.com/10571694/179561288-e424ab71-973b-4848-86c4-121707654354.png)

This screenshot has the most recent days. Any value less than 1 should be counted as a failure based on the goal settings, but that is not occurring. 

![Screenshot_20220718-124841](https://user-images.githubusercontent.com/10571694/179562040-e129bb98-9dc5-40d2-b75a-61ce6ddea8dd.png)

This is a fresh goal, created today, with the same settings. The only data entered was the past week's values, and a single entry of 0 in 2008. So I don't believe it's related to how many entries there are.

**Comment by kalina559** [comment]
Hey, it looks like it's fixed on the dev branch - this bug should be removed in the next version of the app :)
