### ISSUE TITLE
Ability to explicitly mark a day's task as "failed"

### ISSUE THREAD

**Issue by patcon** [iSoron/uhabits#144]
Had been using an app called "7 Weeks" up until I discovered this one. It had the ability to mark as task as failed. For example, if I have a "No coffee after 2pm" task, I might know that I've screwed up already, and can perhaps mark the task as "failed" instead of waiting for midnight to roll-over, and immediately see how that affected my score (?).

This would strike me as a decent (optional) pattern, as it would allow for the ability to notify folks when they haven't yet "addressed" certain tasks. Also, this would be a little bit more data for when people export their data to build visualizations, and perhaps want to ensure that "forgotten" items don't count the same as "failed" ones.

Thanks for your consideration!

**Comment by iSoron** [comment]
Thank you for the suggestion. I am more inclined to implement this feature by allowing some habits to receive a checkmark automatically at the beginning of the day (#125). If you fail them at any time during the day, you can then remove the checkmark. The score will be updated immediately.

The forgotten/failed distinction is covered by issue #96.
