### ISSUE TITLE
OK button for the measurable habit dialogue box is small when using the checkmark widget 

### ISSUE THREAD

**Issue by drossano** [iSoron/uhabits#1448]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
As stated in the title, when entering a measurable habit using the checkmark widget the OK button is small. This issue doesn't occur when entering the habit via the app. 

## Steps to reproduce
1. Click on checkmark widget for measurable habit

## System information
 - Phone: Google Pixel 6 Pro
 - Phone Operating System: Android 12, July 5th, 2022 security update 
 - App version: 2.03

## Screenshots

Widget dialogue box
![Screenshot_20220809-101607.png](https://user-images.githubusercontent.com/72749793/183672297-1d4ffb58-590c-48c2-91f3-b0bed8f1fcac.png)

In app dialogue box for comparison
![Screenshot_20220809-101730.png](https://user-images.githubusercontent.com/72749793/183672657-598851b0-c426-4235-b238-db85a9b5c715.png)

**Comment by hiqua** [comment]
IIRC we fixed that on `dev`

**Comment by iSoron** [comment]
Fixed by #1096
