### ISSUE TITLE
The measurable checkmark widget is not working as intended

### ISSUE THREAD

**Issue by saintpou** [iSoron/uhabits#1468]
Phone: Honor 8
OS: Android 8.0
App version: loop-2.1.0-release

The yes or no habits work, but with the measurable ones, I can't change the value of the habit I want to change, it changes the value of the most recently added measurable habit, doesn't matter which habit I interact with. The problem only occurs with the widget.

If I change the value with the widget and create new ones, the effected habit (recent habit) doesn't change until I delete that specific habit. Hope I'm making sense.

Also, don't know if it's a bug or not, but interacting with measurable habits in the widget opens the app (the app needs to be open for a value to be entered), which seems counterintuitive if it is an intended behavior.

**Comment by iSoron** [comment]
Thanks for reporting this bug, @saintpou. This has been fixed in #1488.
