### ISSUE TITLE
A11y: Text alignment for dyslexia and OCD

### ISSUE THREAD

**Issue by ronilaukkarinen** [iSoron/uhabits#1479]
## Pre-submission checklist
- [x ] I am submitting a bug report, not a feature request.
- [ x] I have searched for similar issues, but did not find any matches.

## Description
It's a common knowledge that [centered text is bad for dyslexia](https://mikebifulco.com/posts/dont-center-paragraph-text). I'd like you to consider aligning the text to left side.

The margins are also bigger on the left side in contrast to the right side. Aligning text to left might fix this issue too. Thanks for considering it. 👍

## Steps to reproduce
1. Go to any habit, detailed view
2. Add long description 
3. See it aligned poorly

## Screenshots
![Screenshot_20220831-122308_Habits](https://user-images.githubusercontent.com/1534150/187695130-e7d70687-16ed-4a5c-8fae-8d7aa3fce800.png)

**Comment by hiqua** [comment]
I think that's already the case in the version that will soon be released, just tested on `dev`.

**Comment by ronilaukkarinen** [comment]
Oh, that's cool. Thanks. I'll follow that thread.
