### ISSUE TITLE
Display gray checkmarks (auto checked) with some color

### ISSUE THREAD

**Issue by j3ll3nl** [iSoron/uhabits#148]
I think it would be nice to make more clear that non-daily habits are automatically checked.
This could be done by showing the checkmark in a darker version of the habit's color.

[http://loophabits.org/faq.html#q8](http://loophabits.org/faq.html#q8)

**Comment by iSoron** [comment]
Hi @j3ll3nl. Sorry about the delay, and thank you for the suggestion. I have actually experimented using darker/lighter colors, but there was not enough contrast to easily tell the two kinds of checkmark apart. I am closing this issue as `wontfix`, but if anyone thinks this can work, please attach a mockup/sketch and I will reconsider.

**Comment by danielBingham** [comment]
Personally, I would prefer non-daily habits to just be checked in the same color as a daily habit.  The habit is done for the day, I don't need to worry about it.  Leaving it greyed out makes me think it is unchecked and undone and leaves me feeling as if my habits are undone -- it beats part of the purpose of the app.  The habit has been done, it should be marked as such the same as any other habit.
