### ISSUE TITLE
Improve adb/developer instructions

### ISSUE THREAD

**Issue by checketts** [iSoron/uhabits#149]
Please add `-r` for the `adb` developer instructions on https://github.com/iSoron/uhabits/wiki/Developer-guidelines#building-from-the-source-code

It currently states to use `adb install app/build/outputs/apk/app-debug.apk` but that fails if the app is already installed. `adb install -r app/build/outputs/apk/app-debug.apk` will allow reinstalls/upgrades of the app. 

I exported my data, uninstalled, then reimported to upgrade previously (granted I am very new to using ADB).

**Comment by iSoron** [comment]
Thanks, I have updated that page. If you find any other problems, please, let me know.
