### ISSUE TITLE
"to enter a lapse, you will need to toggle the checkmark twice"

### ISSUE THREAD

**Issue by chendy** [iSoron/uhabits#1496]
## Description
"For now, to enter a lapse, you will need to toggle the checkmark twice. If skips are enabled, you will need to toggle it three times." 
This doesn't work from main view

## Steps to reproduce

1. From view in screenshot below. Click any checkmark habit. 
2. Toggling this same checkmark only toggles between tick and cross. No 3rd lapse state. 
3. If skip days enabled, checkmark will toggle between tick/cross/line. But still no question mark state

## System information
 - Phone: POCO X3 Pro
 - Phone Operating System: 12
 - App version: 2.0.3

## Screenshots

![Screenshot_2022-09-06-10-19-22-631_org isoron uhabits](https://user-images.githubusercontent.com/601798/188597844-8e562fa5-75f4-4976-b183-e436c46df417.jpg)

**Comment by hiqua** [comment]
This is fixed in the yet unreleased next version: https://github.com/iSoron/uhabits/pull/1372
