### ISSUE TITLE
Bug in calculation for every week schedule? 

### ISSUE THREAD

**Issue by Weygert** [iSoron/uhabits#150]
I have a habit set up with the following schedule: 
- Every week
- Reminder set for Tuesdays

The history calendar shows the following:
![img_20160727_071209](https://cloud.githubusercontent.com/assets/20655714/17183716/0cf70c08-5429-11e6-8d8b-2c68b2410e3b.png)

Shouldn't all weekdays be plotted in light color as soon as I check any day of the week? I mean the current plot I would expect to see if I had set a 'once in 7 days' schedule!?

**Comment by iSoron** [comment]
Thank you for the reporting, but this is not a bug. The app uses a rolling 7-day period, instead of the calendar week. Please see #124 for more information and feel free to join the discussion.
