### ISSUE TITLE
Tasker plugin broken in 2.1

### ISSUE THREAD

**Issue by StanczakDominik** [iSoron/uhabits#1503]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
The Tasker integration appears to be broken in 2.1, reporting either "Error: plugin error: missing, disabled, not exported or no permission received" on trying to create a new Tasker action via the plugin or "To perform this action, the additional plugin org.isoron.uhabits must be installed." on trying to use an existing Tasker action.

## Steps to reproduce
1. Install 2.1
2. Open Tasker
3. Go to Tasks
4. Press the + button to create a new task, give it any name
5. Press the + button to add an Action, select Plugin
6. Press Habits

The following error pops up:
![image](https://user-images.githubusercontent.com/11289391/189862941-4fa63e91-d8b7-4be0-a287-0c5863810df2.png)

Also, when launching any profile connected with an existing Task that uses the Habits plugin, configured pre-2.1, I get the following notification:

![image](https://user-images.githubusercontent.com/11289391/189863315-f9cbf1de-7b90-483c-94ff-f1cfe2b932ed.png)

## System information
 - Phone: Samsung Galaxy A32
 - Phone Operating System: Android 12
 - App version: [loop-2.1.0-release.apk](https://github.com/iSoron/uhabits/releases/download/v2.1.0/loop-2.1.0-release.apk) from https://github.com/iSoron/uhabits/releases/tag/v2.1.0
 - Tasker version: 6.1.3-beta (though it doesn't seem like a Tasker issue, so I'd like to ping @shanbhagrohan who reported the issue in https://github.com/iSoron/uhabits/discussions/1501#discussioncomment-3631093 to confirm their version of Tasker.

## Screenshots
Added inline in "Steps to reproduce".

**Comment by shanbhagrohan** [comment]
My tasker version is 6.14 beta but its not a Tasker issue because it successfully executed a task yesterday before I updated loop.

**Comment by iSoron** [comment]
Thanks for the detailed bug report. I was able to reproduce it.

**Comment by GeekvsCritic** [comment]
Disclaimer: I am not an android developer and have no idea on the implications of the code change I have indicated below.

I have found the code change between the current version and previous version in manifest file that is/might be related to Tasker. So, I have changed the export to `true` from `false` for android receiver `automation.FireSettingReceiver` and reinstalled the app. And the tasker integration is working perfectly fine now.

Note: I am just user who has no experience in Android development. Therefore, I had to test the change for myself before indicating any thing and I am very eager for the official bug fix.

![image](https://user-images.githubusercontent.com/33985056/191000230-c8773065-ed73-463a-b019-1a446c18f9d9.png)

**Comment by iSoron** [comment]
@GeekvsCritic Yes, that's the correct fix.

This issue should be solved in Loop 2.1.1, which will become available shortly for beta testers on Google Play and for everyone on F-Droid in a few days. It's also available immediately from our [GitHub Releases](https://github.com/iSoron/uhabits/releases/tag/v2.1.1) page. If you are still having issues after updating, please let me know.
