### ISSUE TITLE
Integration with Amazon Echo

### ISSUE THREAD

**Issue by artivilla** [iSoron/uhabits#152]
I guess this is a pretty niche feature so definitely not a priority, but I as a user I'm trying to simplify my life by not having to add things I need to manage on my phone -- I like being able to check my habit streak holistically and remind myself where I need to put more effort, however I'd like to shift this habit hands-free. Echo integration would be sweet :)

**Comment by iSoron** [comment]
Thank you for the suggestion, artivilla. I will evaluate this.

**Comment by aschrijver** [comment]
Beware that with this feature privacy would be a big concern. Your habits are really sensitive, personal data.
I would imagine Amazon would love :heart: to receive this data from you for free..

AFAIK currently the app does not send _any_ data to backend services (am I right?), which is a good thing :)

**Comment by artivilla** [comment]
Point. Also, note on that, I just watch my sleep patterns now and leave just about everything else to fate. ¯\_(ツ)_/¯
