### ISSUE TITLE
Google Play Store app not in sync with latest version

### ISSUE THREAD

**Issue by jruiz94** [iSoron/uhabits#1522]
Hello, I just noticed that the F-Droid version of the app is the latest (2.1.1) but on Play Store its still 2.0.3, dated from August. Is this intended for some reason? Thanks in advance, great app btw.

**Comment by iSoron** [comment]
Loop 2.1 is currently available on Google Play for beta testers. You can join our beta program here: 

https://play.google.com/apps/testing/org.isoron.uhabits

**Comment by dimo414** [comment]
It'd be helpful to include a message about its beta status (and how to join) on https://github.com/iSoron/uhabits/releases since it _seems_ like 2.1 is fully released.
