### ISSUE TITLE
Keyboard hide makes data entry difficult

### ISSUE THREAD

**Issue by olereads** [iSoron/uhabits#1529]
Hello, really appreciate this app I've been using it for months and I love the features it has. 

I thought I might share that on my Android when I go to enter something with a measurable value, for me say kilometers walked, if I use the keyboard it works fine. If I want to use the spinner then when I touch it the keyboard hides which automatically spins the spinner up. It only does it on the left column and not the right. 

I hope I'm describing this well enough. Thanks again for the fantastic app.

**Comment by olereads** [comment]
Not that I've heard

**Comment by iSoron** [comment]
Fixed in Loop 2.1. We have a new dialog for entering numerical values.

**Comment by olereads** [comment]
The issue still exists for me, I'm not sure what's going on with closing it?

**Comment by iSoron** [comment]
@olereads What version of Loop are you using?

**Comment by olereads** [comment]
2.0.3
Do I manually update somehow?

**Comment by iSoron** [comment]
Loop 2.1 is currently available on Google Play for beta testers. You can join our beta program here:

https://play.google.com/apps/testing/org.isoron.uhabits

**Comment by olereads** [comment]
Thank you

**Comment by olereads** [comment]
Hi there, data entry is much nicer in 2.1. thank you 😊😊

I noticed that the timed pop-up doesn't have the delay/later option any
longer, was that moved to a different menu somewhere? Or is it just not
available?

Thank you

Erica
