### ISSUE TITLE
Generated Code Plugins

### ISSUE THREAD

**Issue by gaurav34** [iSoron/uhabits#153]
Hello,

I was looking your UHabit app code which has very nice UI, for implementing graph and history at my one of project, while going through code i got little confused regrading flow of code.

Some file are generating under app\build\generated\source\apt\debug\ folder I want to know from which plugin or dependencies this code is generating.

It would be very kind if you can help me.

Thanks,
Gaurav Agrawal

**Comment by iSoron** [comment]
Hi Gaurav, we are using Dagger 2 and Retrolambda in this app, but you don't need to read the generated code to understand what the application is doing. What class are you trying to understand?

**Comment by gaurav34** [comment]
I was looking app flow Habit insertion into DB and fetching records from DB and showing into list.
