### ISSUE TITLE
Disfunctional widgets after exiting landscape-only app/game

### ISSUE THREAD

**Issue by BloodRaven0** [iSoron/uhabits#1534]
## Description
After exiting a landscape-only app (in this case a game called Infinitode 2), the widgets are shrunk to about half their size and don't respond to any input.

## Steps to reproduce
1. Place 1x1 widget on your home screen.
2. Launch an app that forces the phone into landscape mode.
3. Exit the app.
4. See error.

## System information
 - Phone: Poco x3 nfc
 - Phone Operating System: Android 10
 - App version: 2.1.1 F-Droid
 - Homescreen app: Lawnchair 1.2.1.2001

## Screenshots
![Screenshot_20221006-111949_Lawnchair](https://user-images.githubusercontent.com/42444745/194261756-aedcdfc3-cc71-4a57-a863-316f446b67c5.png)

**Comment by iSoron** [comment]
Thank you for the bug report, @BloodRaven0. This looks like a launcher bug to me. Does it also happen with the default launcher? If so, please let us know and I will reopen this issue.
