### ISSUE TITLE
Add capability to add notes to completed habit

### ISSUE THREAD

**Issue by punassuming** [iSoron/uhabits#1540]
This app is great and fills almost all my requirements.  One thing that would close the gap would be the capability to add notes or comments to a completed item.  I understand it might result in a new workflow, but having the ability to take some notes about the item and track all events with something like an agenda view showing the timeline with notes would be beneficial.

**Comment by punassuming** [comment]
This might be a duplicate of #1074, but didn't see how / if that milestone was closed.

**Comment by punassuming** [comment]
Sorry, realize the 2.1 release on GitHub has this.  When will this get pushed to Play store?

**Comment by punassuming** [comment]
With this capability deployed, the only suggestion is to also add an timeline view in the habit screen to show a timeline of all notes.

**Comment by iSoron** [comment]
Thank you for the suggestion, @punassuming. As you noted, this is already available in Loop 2.1.
