### ISSUE TITLE
Checkmark Widget of Numerical Habits does not respect the 3am setting

### ISSUE THREAD

**Issue by KosmicGR** [iSoron/uhabits#1541]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
When using a checkmark widget on my homescreen for numerical habits there is a certain issue between 12am and 3am **when the appropriate setting is enabled**.
Even though it displays the "previous" day's status, when you click on it to edit its value, it picks the current day (e.g. it shows the status from the 2nd day of a month but edits the value of the 3rd day).

## Steps to reproduce
1. Launch the app
2. Go to Settings and enable the "Extend day a few hours past midnight" option
3. Create a Numerical Habit
4. Create a checkmark widget for that habit
5. Edit the current day's value
6. Wait until / Change the time to somewhere between 12am and 3am **of the next day**
7. Click on the widget
8. The textbox will display a 0 value
9. Editing it will not make any visible changes until after 3am, when the day is properly shown both on the widget and in the app

## System information
 - Phone: Redmi 6A
 - Phone Android 9
 - App version: 2.1.1
 - Launcher: Nova Launcher 7.0.57

**Comment by iSoron** [comment]
Fixed in 471f977
