### ISSUE TITLE
App crashes when re-opening "habit completion status dialog" after rotating screen with that dialog open

### ISSUE THREAD

**Issue by RadCraftplay** [iSoron/uhabits#1545]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
If user does not close "habit completion status dialog" and rotates device, the dialog disappears, and if user tries to open that dialog again (for any habit), the app crashes.
Note: It does not matter how many times the screen is rotated as long as as the "habit completion status dialog" disappeared once as a result of switching app from portrait to horizontal mode or the other way around (and it does disappear every time).

## Steps to reproduce
1. Go to main view
2. Click on any "habit completion checkbox" (habit completion status dialog shows up)
3. Rotate screen (habit completion status dialog disappears)
4. Click on any "habit completion checkbox"
5. Application crashes

## System information
 - Phone: Redmi Note 9
 - Phone Operating System: Android 10
 - App version: 2.1.1

## Screenshots
So called "habit completion status dialog": ![Habit completion status dialog](https://i.imgur.com/BvctpMN.jpeg)

**Comment by iSoron** [comment]
Thank you for the bug report, @RadCraftplay. I was able to reproduce it.

**Comment by iSoron** [comment]
Fixed in 2ba5f5f
