### ISSUE TITLE
Don't show reminder notification for entered habits

### ISSUE THREAD

**Issue by t214c** [iSoron/uhabits#1546]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Steps to reproduce
1. Create a daily habit with a reminder at 6:00 pm
2. Open the app before 6:00 pm, mark the habit as complete for today

## Expected behavior
- no reminder notification at 6:00 pm

## Actual behavior
- reminder still shows even for entered habits

## System information

 - App version: 2.1.1

**Comment by iSoron** [comment]
Thanks for the bug report, @t214c. Is this habit numerical or yes/no? The app should already skip reminders for completed habits.

**Comment by t214c** [comment]
@iSoron yes/no

>The app should already skip reminders for completed habits.

It doesn't on my phone 🤷‍♂️.

**Comment by t214c** [comment]
I tried to recreate it. I think it happens specifically if it was marked as not done.

**Comment by iSoron** [comment]
@t214c Then that's intended behavior. The app currently only skips reminders for completed habits, not entered ones. Please feel free to open a feature request.
