### ISSUE TITLE
Swipe to view progress more than a week ago.

### ISSUE THREAD

**Issue by JoshGraham** [iSoron/uhabits#155]
(Translating some user feedback from Google Play Store)
...If I could swipe to view what's been done before,
more than a week ago, it's be great!

**Comment by iSoron** [comment]
Just to make the request more clear, on the main screen, we could allow the user to swipe from right to left on the header. This would "scroll back in time", and the user would be able to see the checkmarks for all the habits, at any given day in the past.

**Comment by Sera-fita** [comment]
Hi, I will try to implement this request. Already started to look into it but may need some minor help with existing code.

**Comment by GoodEveningMiss** [comment]
Seconding request. This makes it easier to see trends across all the habits
