### ISSUE TITLE
Notes for incomplete days are not shown if frequency target is already met

### ISSUE THREAD

**Issue by wolfgangkarall** [iSoron/uhabits#1566]
## Pre-submission checklist
- [ x ] I am submitting a bug report, not a feature request.
- [ x ] I have searched for similar issues, but did not find any matches.

## Description
If a habit already has its frequency target met (e.g. '4 times per week'), it is not possible to see a note for an incomplete day (marked 'x' in the pop-up). It does work when marked complete (tick in the pop-up) or skipped ('-' in the pop-up).

Looking at the sqlite3 DB that's the backup, I see the text entered there in the 'Repetitions' table. It's **not** in the CSV export.

It's not visible in the habits overview screen

![image](https://user-images.githubusercontent.com/5254079/198947033-68a643f6-14a6-4737-93da-8c0a863f2815.png)

I'd expect an 'x' with the dot instead of the unfilled tick, as I see 'x' as manual entry, while the unfilled tick as sign of 'this day has no entry, but the frequency target is met already', but an unfilled tick with a dot would probably work just as well.

But what's worse, the text is gone from the pop-up when editing that day's status again.

There's also no visual hint in the calendar view:

![image](https://user-images.githubusercontent.com/5254079/198947367-d6db9b26-a432-44da-9b61-6d1ed6eb8c39.png)

## Steps to reproduce
1. create some habit with a frequency like '4 times a week'
2. mark that habit with a tick for 4 days
3. add a note on day 5 while also marking it incomplete ('x')
4. open the entry's pop-up again -> there is no note

## System information
 - Phone: Mi A1
 - Phone Operating System: Android 9
 - App version: latest F-Droid version, 2.1.1

## Screenshots
see above

**Comment by iSoron** [comment]
Fixed in 2131fb3a3ddff7ff9a4239259880c117c1bde657. The fix should become available in Loop 2.1.2.
