### ISSUE TITLE
Custom snooze period in dark system theme > watch hand is hardly visible

### ISSUE THREAD

**Issue by uli-on** [iSoron/uhabits#1574]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
When the system is set to a dark theme the watch hands have almost zero colour contrast with the background clock-face, independent of the theme chosen inside the app.

## Steps to reproduce
1. Set the system to a dark theme
2. Snooze an event from its notification
3. Choose a custom period
4. Try to spot the watch hands

## System information
 - Phone: fairphone 3
 - Android 10
 - App version: 2.1.0

## Screenshots
Can't upload images in Octodroid, the app I'm using for participating in GH discussions.

**Comment by uli-on** [comment]
@kalina559 Thanks for all this, Jakub, I think your screenshot brought us closer: please try to replicate with another habit colour, the lightest neutral grey, third from last. Then you should get this one here:

![Screenshot_20221211-170244](https://user-images.githubusercontent.com/35634829/206915918-82820fa7-b30f-415b-990d-67c162c77c93.png)

**Comment by kalina559** [comment]
Okay now I was able to reproduce this. I don't think the bug is very serious, as the user is still able to see the time as digits, but it's a bit weird that the watch hands have different color than when you edit the reminder time in app 😄

**Comment by uli-on** [comment]
Yeah, it's a bit odd, especially cause I chose that colour for its best
visibility

**Comment by uli-on** [comment]
Thanks!
