### ISSUE TITLE
Habitbull import numerical value habit bug

### ISSUE THREAD

**Issue by Rslayl** [iSoron/uhabits#1576]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
When importing Habitbull CSV with numerical value habit, values are off by 3 decimals. Ex: 80 becomes 0.08 in Loop.

## Steps to reproduce
1. Settings > import data > choose habitbull csv
2. Input value for today
3. All data for habit appear
4. Values are off by 3 decimals

## System information
 - Phone: Sony Xperia 5 III
 - Phone Operating System: Android 12
 - App version: 2.1.1

**Comment by hiqua** [comment]
Can you share the csv, redacted if needed?

**Comment by Rslayl** [comment]
[HabitBullData.csv](https://github.com/iSoron/uhabits/files/10079848/HabitBullData.csv)

**Comment by iSoron** [comment]
Fixed in #1591
