### ISSUE TITLE
Error on completion on times-a-week goal

### ISSUE THREAD

**Issue by Almtesh** [iSoron/uhabits#1578]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
I have a habit I set on three times a week, I did it only twice last week and the habit is marked as completed.  
Here's the screenshot of the habit I noticed the bug in:  
![Screenshot_20221128-082801_1](https://user-images.githubusercontent.com/8816946/204219301-f49247d6-afb8-427a-b909-af700c87618a.png)

## Steps to reproduce
1. Create a yes-or-no habit
2. Put a goal on this habit for three times a week
3. Complete the information for three consecutive weeks as follows:
* first week, do it on Monday, Wednesday and Friday
* second week, do it on Monday, Thursday
* third week, do it on Monday, Wednesday and Friday
* put all other days to not done
4. See that the goal is completed for all weeks

## System information
 - Phone: Fairphone 3+
 - Phone Operating System: Android 11
 - App version: 2.1.1

**Comment by hiqua** [comment]
"A week" actually means "for some 7 days in a row". In other words, if there exists a 7-day interval containing the day and fulfilling the goals (so having 3 checkmarks in your case), the habit will be considered fulfilled.

I think the UI could be clearer on that. Ideally we'd also have "human weeks" (so not arbitrary 7 days), but I'm not sure that's really worth it on top of what we currently have.

**Comment by Almtesh** [comment]
Oh, I see. What confused me is that the "a week" option is apart of "every x days".
