### ISSUE TITLE
Checkmarks in different columns appear and disappear when toggled too quickly

### ISSUE THREAD

**Issue by aleksejrs** [iSoron/uhabits#159]
v1.5.4

I think I had Loop running since before midnight, and the day changed.  When (un)checking boxes in the second column, the third (counting from the left) box also changed.  I suppose the appearance of the boxes had not "shifted" properly when the new column was added.

**Comment by iSoron** [comment]
Thank you for the bug report. I will verify this.

**Comment by aleksejrs** [comment]
Sometimes, when I check a box, it apparently checks, unchecks, then checks again (probably because I caused a reload a few seconds earlier), which may have confused me into thinking this — however, it was in a different column, so I filed this report.

**Comment by iSoron** [comment]
I no longer believe this is an issue. We now perform most of the operation in-memory, so this type of lag has reduced significantly.
