### ISSUE TITLE
Filter hide-entered should NOT exclude habits with frequent target met based on calculation

### ISSUE THREAD

**Issue by stefgers** [iSoron/uhabits#1595]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.
_=> #1566 and #1052 might be considered as "related"_ 

## Description
Filter "hide entered" should NOT exclude habits with frequent target met based on calculation.

## Steps to reproduce
1. create some habit with a frequency like '4 times a week'
2. mark that habit with a tick for 4 days "in the past": today should be calculated as 
![grafik](https://user-images.githubusercontent.com/91599513/208114545-9a304fd2-9b01-4d90-be47-6262f8e1080b.png)
3. apply the filter "hide entered"
4. the habit is excluded but nothing has been entered for today

## System information
 - Phone: moto g(8) plus
 - Phone Operating System: Android 10
 - App version: 2.1.1 (F-Droid)

## Note
The use of the "?" option doesn't change the behaviour

**Comment by iSoron** [comment]
Thank you for the bug report, @stefgers, but this is intended app behavior.

**Comment by stefgers** [comment]
> Thank you for the bug report, @stefgers, but this is intended app behavior.

Let me clarify ... I probably assumed another type of filter (see 2.) ...

1. Current filter = hide "done" => hides completed and calculated completes
2. New filter = hide "entered" => hides those entered as complete or "x" incomplete, does not hide non-entered "?"
   - this could be combined with the "?"-option
