### ISSUE TITLE
Full import not working

### ISSUE THREAD

**Issue by apeixinho** [iSoron/uhabits#1598]
Make a full export
In another app, phone, the import generates error
"file not recognized"

**Comment by iSoron** [comment]
Thank you for creating this issue, but we are closing it as it does not follow our bug report template. Please edit your issue to follow our bug report template and make sure to include all the required information (description of the problem, steps to reproduce and system information).

**Comment by SimonDedman** [comment]
Same issue. Exported from Asus Zenfone 6, saves as zip containing folders & csvs. Importing to Samsung Galaxy Note 9, select the zip file, "file not recognised".

Steps to reproduce are simply to follow the expected steps to export then import. Please reopen issue if this comment doesn't do so automatically.
