### ISSUE TITLE
Checked habit is not saved

### ISSUE THREAD

**Issue by dajotim937** [iSoron/uhabits#1616]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
I began to use app after ~1 year pause. Noticed that in current version sometimes checked habits aren't saved and when you reload app, it looks like I haven't toggle habit. I have 8 habits and in wasn't and issue at the end of 2021 IIRC.

## Steps to reproduce
1. Open app.
2. Toggle habit
3. Open, I don't know how this menu in android is called but, all now opened application and close (throw away) habits.
4. Open app again
5. Habit isn't checked

## System information
 - Phone: Nokia 8
 - Phone Operating System: Android 9, 2020-10-01 security patch.
 - App version: 2.1.1

## Additional info
I guess something similar discussed here but switching doesn't interfere with saving. Only closing app.
https://github.com/iSoron/uhabits/issues/206
Also, I think, I could try to record video for you, but my phone doesn't have default screen recording app so I didn't bother about it. If you will need it -- tell me.

**Comment by iSoron** [comment]
Hi @dajotim937, thank you for the bug request, but I was not able to reproduce the issue. A screen recording would be very helpful.

**Comment by dajotim937** [comment]
<details>
<summary>Screen recording</summary>

https://user-images.githubusercontent.com/96221151/214068371-fda142ff-76fc-4686-a3a6-bdf62275bdec.mp4

</details>

**Comment by iSoron** [comment]
Thanks, I was able to reproduce it. The issue is related to the toggle delay, introduced around Loop 2.1.0. Since it also causes other issues, I have removed the delay in 1470dcd. The fix will become available in Loop 2.1.2.

**Comment by dajotim937** [comment]
Any approximate ETA for 2.1.2?
