### ISSUE TITLE
Editing a habit doesn't immediately update the habit detail's title screen

### ISSUE THREAD

**Issue by checketts** [iSoron/uhabits#162]
When I edit a habit's title and it save, I expect the habit detail to now display the updated habit title. Instead it remains the same and doesn't update until leaving the habit detail screen to the habit list (main screen)

**Comment by iSoron** [comment]
What version of the app are you using? Is it from Google Play/F-Droid or are you building from the source code?

**Comment by checketts** [comment]
Built from master commit 3ad3cf54ecee1162abab3a83d1a8782521093d24
