### ISSUE TITLE
Unable to add a new record on Widget

### ISSUE THREAD

**Issue by tingtsz124** [iSoron/uhabits#1620]
When I upgraded Samsung OS to the new version, Habits cannot be add and no response on Homepage. And when I add a new record in app directly, the widget has crushed

Samsung version upgraded on 24_Dec-2022
![Screenshot_20230108_145341_Software update](https://user-images.githubusercontent.com/50259140/211184390-f152c1b0-d97f-4463-9cd2-01171ad58e7a.jpg)

Wight on Homepage 
![Screenshot_20230108_145801_One UI Home](https://user-images.githubusercontent.com/50259140/211184413-1ae9fa60-f0b1-4645-b44e-1372d92106b0.jpg)

Please help to fix it!!!

**Comment by iSoron** [comment]
Thank you for creating this issue, but we are closing it as it does not follow our bug report template. Please edit your issue to follow our bug report template and make sure to include all the required information (description of the problem, steps to reproduce and system information).
