### ISSUE TITLE
Hide completed should only hide completed today 

### ISSUE THREAD

**Issue by alexture** [iSoron/uhabits#1621]
Hi! When 'hiding all completed' for a given day, I believe it should only hide actually complete items, not items that are not required and that are pre-checked (eg. 3rd day in a row for a "2 days out of 3" item). This allows for checking all items that haven't been done today 

## Pre-submission checklist
- [ ] I am submitting a bug report, not a feature request. -> it feels like a bug to me, but might actually be a feature.
- [x] I have searched for similar issues, but did not find any matches. -> no currently open issue

## Description
A clear and concise description of what the problem is.

When 'hiding all completed' for a given day, I believe it should only hide actually complete items, not items that are not required and that are pre-checked (eg. 3rd day in a row for a "2 days out of 3" item). This allows for checking all items that haven't been done today 

## Steps to reproduce
1. Go to the triangle menu
2. Check "hide entered/completed" (sorry, I use the app in another language so I don't know the English string)
3. See error on the list of items

## System information
 - Phone: FairPhone 4
 - Phone Operating System: Android (latest)
 - App version: 2.1.1. via froid

**Comment by arcstur** [comment]
At least for me, that's not what I want. For example, if I have a habit which should be completed once a week, I don't want to be bothered by it when filtering for those I need to do. The current behavior is what suites me at least, and I think it makes sense.

**Comment by iSoron** [comment]
Hi @alexture, thank you for the bug request, but that's intended app behavior.
