### ISSUE TITLE
Cannot Customize Notifications (Snooze Length)

### ISSUE THREAD

**Issue by stef204** [iSoron/uhabits#1624]
Version 2.1.1

Since upgrading to Android 12, I can no longer customize the snooze of `uhabits` notifications.
I used to be able to either snooze for the default length (e.g.15 minutes) OR choose **Customize** and then set tomorrow 10 AM (for example.)  A clock would appear (just as when one sets an alarm) and one would be able to customize the time of next notification.

Is this an issue with `uhabits` or with Android 12 itself?

**Comment by iSoron** [comment]
Hi @stef204, this feature was removed in #1226. See that PR for more details.

**Comment by stef204** [comment]
@iSoron Thanks for your reply.
Removing that feature makes the app much less useful (for my use case.)  Being "stuck" with Android 12's own limitation of 15m, 1h or 2h as the **only** choices for snoozing notifications takes much value away from the app.
