### ISSUE TITLE
I was clicking to complete a task while the whole section just disapeared. 

### ISSUE THREAD

**Issue by TGSunrise** [iSoron/uhabits#1632]
<!
## Pre-submission checklist
- [✓ ] I am submitting a bug report, not a feature request. ✓
- [ ✓] I have searched for similar issues, but did not find any matches. ✓

## Description
I clicked to complete a task and the whole section disapeared. Now all the data from 3+ months is home just like that. Somehow 5 of my upper task like meditation sleep quality and so on disapeared too without even cliking on them. Is there a way i can restore the memory and will someone Fox this awfull issue?

I did not delete or even open the menu when you can delete them they just vanished

## System information
 - Phone: Motorola edge
 - Phone Operating System:  Android 11
 - App version: [e.g. 2.0.2] newest

## Screenshots
If applicable, add screenshots to help expla
![Screenshot_20230126-090011](https://user-images.githubusercontent.com/123624564/214784978-67e4bb3a-cc2f-4a14-9005-2a5ad60738ca.png)
in your problem.

There were 5-8 more task up there and they just vanoshed without me deletting them

I HAVE A VIDEO OF THIS IN A NEW POST I MADE !!!
I HAVE A VIDEO OF THIS IN A NEW POST I MADE !!!

**Comment by iSoron** [comment]
From the FAQ:

> ### When I add a checkmark, the app deletes my habit!
> You have probably accidentally enabled the "Hide completed habits" option. To disable it, open the main screen, tap the filter icon (the one with three horizontal lines), then tap "Hide completed".
