### ISSUE TITLE
logcat said that TimePickerDialog: Unable to find keycodes for AM and PM.

### ISSUE THREAD

**Issue by RiShinku** [iSoron/uhabits#1644]
## Description
when set alarm in the page of creating a new habit, logcat said  'TimePickerDialog: Unable to find keycodes for AM and PM' when I debug this application.

## Steps to reproduce
1. Go to the main page.
2. Create a new habit.
3. Click alarm.
4. logcat print the Error log.

## System information
 - Phone Operating System: Android

**Comment by RiShinku** [comment]
And when the application was opened, some errors also 
 caught:
'Access denied finding property  "persist.device_config.runtime_native.use_app_image_startup_cache"'
'LoadAppImageStartupCache enabled : 1'
'Fail to acquire dataAnalyzerService...'
'AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@xxxxxx'
'parse speed value length error'

**Comment by iSoron** [comment]
Thanks for the bug report, @RiShinku, but from my understanding the AM/PM error message does not lead to any broken functionality. The remaining ones appear to be generated by the operating system, not our app.
