### ISSUE TITLE
Some emoji do not render in habit names and widgets

### ISSUE THREAD

**Issue by cadadr** [iSoron/uhabits#1650]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
A clear and concise description of what the problem is.

I use emoji in some habit names and checkmark widgets as mini reminders. It appears that some emoji are rendered as empty boxes in habit names and widgets, even tho while creating the habit, they do render in the habit name input of the new habit creation form.

Seemingly, it affects emoji in Unicode 13.0 and 14.0 merely, unicode 12.0 and unicode 15.0 emoji do not cause this problem

## Steps to reproduce
1. Create a new habit with the :toothbrush:  (toothbrush, emoji 13.0) emoji in its name
2. Save and observe the habit list
3. Name of the new habit will contain a character-not-found square in place of the toothbrush
4. Create a widget for the same habit
5. The name will be similarly missing the emoji in it

## System information
 - Phone: Xiao Mi Redmi 7
 - Phone Operating System: MIUI 11.0.2 / Android 10
 - App version: 2.1.1

## Screenshots

The emoji in these screenshot are in pairs, each pair represents a version of emoji between Unicode 12.0 and 15.0, respectively.

![IMG_20230215_081808](https://user-images.githubusercontent.com/9742985/218940428-5db452e5-2baa-4cb3-9b85-4510ae2d3887.jpg)
![IMG_20230215_081856](https://user-images.githubusercontent.com/9742985/218940432-ff6340f4-5da2-4f4b-a0a0-06cc54fa9e03.jpg)
![Screenshot_2023-02-15-08-19-22-026_org isoron uhabits](https://user-images.githubusercontent.com/9742985/218940433-3d43b801-a0de-4009-b4d6-3bdd8881a593.jpg)
![IMG_20230215_081945](https://user-images.githubusercontent.com/9742985/218940435-6e1124e0-4ea6-424e-91ff-59476449f2d4.jpg)

**Comment by iSoron** [comment]
Thank you for the detailed bug report, @cadadr. From your screenshots, there's clearly an issue, but I was unable to reproduce this on LineageOS 19, so it seems to be dependent on the launcher or operating system.

If some emoji were missing on the main app, this issue might have been fixable. On widgets, though, I'm not sure there's anything we can do about it, since text rendering is controlled by the launcher.
