### ISSUE TITLE
CSV export generates extra commas, breaking the correct order of columns and rows

### ISSUE THREAD

**Issue by hmcarlos** [iSoron/uhabits#1652]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
csv export generates extra commas, making csv useless

## Steps to reproduce
1. export csv
2. import from your favorite csv viewer (excel...) and notice that to the usual (and correct) commas used to separate data there is another extra comma inside the timestamp. E.G.: " ,Entry(timestamp=2023-02-17, value=7000), ". This should be a single value (a single cell in excel), notice the parenthesis, but the inside comma before "value" breaks the csv into two cells thus breaking the correct order of columns and rows.

## System information
 - Phone: Motorola G10
 - Phone Operating System: Android 101
 - App version: 2.0.3

## Suggestion
- replace inside timestamp comma with a semicolon

**Comment by iSoron** [comment]
Thanks for the bug report, @hmcarlos. This has already been fixed in the beta version of the app (v2.1). You can try it out by joining our beta program on Google Play or downloading it from F-Droid.
