### ISSUE TITLE
Bugs found in version 1.7.0 that cause logcat errors and even app crashes

### ISSUE THREAD

**Issue by Srrsrr123** [iSoron/uhabits#1664]
**_Describe the bug_**

Dear developer!  In the process of using it, I found four bugs causing logcat errors and even app crashes. As shown in the figure, when pressing the button, the logcat errors occur or the app crashes. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.

**_Screenshots_**
1、
![CL{%M6KDU 5L%7`JI(QRYJ1](https://user-images.githubusercontent.com/79861356/225551260-beebb719-137f-435d-9746-066f0ca22289.png)

![V%A34(WE$}KPOX3V}6LI@04](https://user-images.githubusercontent.com/79861356/225551306-f3bfa87d-759e-499a-aa7b-4fd908457b50.png)

2、
![_Q$6Z__ETOC0I7L$17 6N92](https://user-images.githubusercontent.com/79861356/225551362-432f0ffa-e316-45cc-97fe-dcc5a10eaca8.png)

![4~_W1WD`Q~TQ~J8G8$YE99S](https://user-images.githubusercontent.com/79861356/225551388-1e72a74d-cd0e-40e7-b51b-ee166399f915.png)

3、
![CC6J1)NJ9(G%08VL FO76C](https://user-images.githubusercontent.com/79861356/225551451-249c1adb-0ea7-4f7b-a4e5-43113b7d1d66.png)

![9ECO4~K(5SGWC@1B@`{P0$W](https://user-images.githubusercontent.com/79861356/225551478-48eaf8c5-cdb1-4c61-b2d0-f3963390d06d.png)

4、
![FB5TA5$WFN{GZNH_))@67)F](https://user-images.githubusercontent.com/79861356/225551532-aae1f497-5b9f-4eae-a406-d5ed60377ac0.png)

![FCFCCRQ(974_OOEW D0U%L4](https://user-images.githubusercontent.com/79861356/225551560-341d9fc8-4bff-44a9-9f22-4463107d437f.png)

**Comment by hiqua** [comment]
This is an old version, please update.

**Comment by Srrsrr123** [comment]
> This is an old version, please update.

Thank you very much for your reply in your busy schedule, it is very helpful to me.
