### ISSUE TITLE
Custom repeat settings can't be removed

### ISSUE THREAD

**Issue by italiatina** [iSoron/uhabits#167]
First, thank you for making an OS app which is ad-free, useful, and simple! :-)

When I set a custom repeat (eg, 1 time every 2 days), I was unable to go back and change it to one of the defaults (eg, 5 times per week).

**Comment by iSoron** [comment]
I'm glad you like the app. After you select a custom frequency, you can still specify "5 times per week" by typing "5 times in 7 days".

**Comment by oxr463** [comment]
> I'm glad you like the app. After you select a custom frequency, you can still specify "5 times per week" by typing "5 times in 7 days".

I think the issue creator meant they could not go back to the drop-down and choose a different option.
