### ISSUE TITLE
Widget with multiple habits is read-only and has paint issues

### ISSUE THREAD

**Issue by liwsoft** [iSoron/uhabits#1671]
## Description
Widget containing multiple habits is read only and its visualization often fails

## Steps to reproduce
1. Add habits A and B (3-state) 
2. Add a widget with habit A (ref. : WA) 
3. Add a widget with habit B (ref. : WB) 
4. Add a widget with habits A and B (ref. : WAB) 
5. Tapping WAB does not change habit a or B (the bug)
7. Tapping WA or WB does change it and also WAB (expected) and causes WAB to vanish completely or vanish habits which are not on the top of WAB 

## System information
 - Phone: Samsung Galaxy Note 20
 - Phone Operating System: Android 13
 - App version: 2.0.3

## Screenshots
Video attached 

https://user-images.githubusercontent.com/508789/227844274-2e355e44-d65d-4bdc-abb8-6f305a967ec4.mp4

**Comment by iSoron** [comment]
Thanks for the bug report. This is already fixed in the beta version of the app.

**Comment by RetroAbstract** [comment]
Hi, how did you add multiple habits into one checkmark widget to cycle through? When I create a new checkmark widget I can only select one habit

**Comment by hiqua** [comment]
I think that's deprecated and no longer possible, not 100% sure though.

**Comment by iSoron** [comment]
Yes, this feature has been removed as it is not stable on multiple phones. The fix does not seem easy.
