### ISSUE TITLE
Can't edit older than two months values

### ISSUE THREAD

**Issue by mathisgauthey** [iSoron/uhabits#1672]
## Description
I can't edit older than 2 months values, hence can't manually import from Daylio without breaking my habits tracking cause there's no import feature from Daylio.

## Steps to reproduce
Slide to the bottom left of the days. We're the 28 of march, I can only go back as far as the 28 of january. I'd need to get back to the first day of 2023.

## System information
 - Phone: Pixel 7
 - Phone Operating System: Android 13
 - App version: 2.0.3

## Screenshots
Not necessary.

Thanks in advance !

**Comment by hiqua** [comment]
* please update to the latest version
* you can light press a habit, go to the calendar view, and press edit there and that should allow you to change entries. I think that's good enough

**Comment by mathisgauthey** [comment]
> * please update to the latest version
> * you can light press a habit, go to the calendar view, and press edit there and that should allow you to change entries. I think that's good enough

Thanks ! The play store wasn't the last version, I should have checked that before creating an issue. 

Thanks and make sure to have a great day !
