### ISSUE TITLE
Change message on home screen widget when habit is deleted

### ISSUE THREAD

**Issue by italiatina** [iSoron/uhabits#168]
More of a feature request/enhancement

When I add a habit to the home screen as a widget, and then delete that habit, the widget remains on the home screen, but now reads "Error drawing widget."

**Comment by iSoron** [comment]
Thank you for the suggestion. I agree that we should do that, but unfortunately, as far as I know, Android does not allow it. Only the user can add and remove widgets to the home screen. The best we could do is change the message to something more helpful ("Habit deleted / not found").

**Comment by regularcoder** [comment]
I'll take a shot at changing the message to "Habit deleted / not found" on the widget when a habit is deleted.
