### ISSUE TITLE
Widgets won't light/color up when pressed 

### ISSUE THREAD

**Issue by mdsawyermd** [iSoron/uhabits#1684]
## Pre-submission checklist
- [ ] I am submitting a bug report, not a feature request.
- [ ] I have searched for similar issues, but did not find any matches.

## Description
A clear and concise description of what the problem is.

## Steps to reproduce
1. Go to ...
2. Click on ....
3. Scroll down to ....

## System information
 - Phone: [e.g. Google Pixel 4]
 - Phone Operating System: [e.g. Android 10]
 - App version: [e.g. 2.0.2]

**Comment by hiqua** [comment]
Please fill the template, as there's too little information right now to do anything.
