### ISSUE TITLE
When CSV is downloaded the checkmarks central file does not produce the values for each habit

### ISSUE THREAD

**Issue by Channah-Miryam** [iSoron/uhabits#1685]
When I download the CSV from my mobile phone, all files are alright except one file. 
This is the checkmarks central file.
The values of the checkmarks are not displayed at all. 

Download the CSV file. 
Extract it at your laptop.
Open central checkmarks file.

Samsung Galaxy 

Version
2.0.3 (only this version can be downloaded at google play)
![bug 2](https://user-images.githubusercontent.com/60585420/231815273-4e8ce9a1-8785-4088-ac91-37f2c46dcc32.png)

![bug](https://user-images.githubusercontent.com/60585420/231814951-3eeb1950-0bf9-490d-8192-bb3f4386abb3.png)

**Comment by hiqua** [comment]
Can you attach a sample of the CSV file? Open it with notepad or another text editor (not excel), remove almost everything but a few lines, and rename things you consider private?

I'm not sure what you mean by the values not being displayed at all.

**Comment by Channah-Miryam** [comment]
it is the same in csv... 

![image](https://user-images.githubusercontent.com/60585420/235347047-4c073227-a577-440a-8c1a-91c4c976e545.png)

**Comment by Channah-Miryam** [comment]
here is an example of the checkmarks for one habit 

![image](https://user-images.githubusercontent.com/60585420/235347258-9258109c-ed7f-4aaa-9b2d-59523383573a.png)
