### ISSUE TITLE
Habit checkmark widget not working

### ISSUE THREAD

**Issue by josemduran** [iSoron/uhabits#1688]
## Description
I changed my phone from Samsung Galaxy S10 to Galaxy S23 a couple of months ago and backup all my data from the app to transfer it to the new phone. The issue is the habit checkmark widgets are not working, which is the main way on how I track my habits. I haven't used the app since I changed the phone because of that. 
PS. I'm also not able to open the app when I press on the other Loop widgets if it helps, but that not enough issue for me.

## Steps to reproduce
1. Hold press on main screen
2. Select add widgets
3. Look for Loop widgets
4. Select checkmark widget and add the habits you desire
5. Try to check an habit but not responding after few attemps, even after repeating the steps again.

## System information
 - Phone: Samsung Galaxy S23
 - Phone Operating System: Android 13
 - App version: 2.0.3

**Comment by SimonDedman** [comment]
Similar issue. Had to create all habits fresh when a backup didn't work. Most habits are Boolean, once daily frequency, all entered via widget. For one of them, the widget entry seems data to the database but

A. The separate tracking calendar widget doesn't display those data even though they're on the calendar in the habit detailed view, and

B. The check mark widget fills an arbitrary bar and doesn't highlight, versus the other Boolean habits which highlight every day when pressed once.

Photos attached: friends doesn't work, weigh does.

![Screenshot_20230524-220236_Habits](https://github.com/iSoron/uhabits/assets/4599748/830dd6f6-7124-4b1b-8118-581a5e5e8f59)
![Screenshot_20230524-220320_Habits](https://github.com/iSoron/uhabits/assets/4599748/7649c009-3b40-4ab6-b56e-8c285ad251bb)
![Screenshot_20230524-220247_Habits](https://github.com/iSoron/uhabits/assets/4599748/16573106-efc1-4378-9551-d1d17e264cf9)
![Screenshot_20230524-220304_Nova7](https://github.com/iSoron/uhabits/assets/4599748/3f56dc1e-b808-4ebe-9c7d-4a501a6a256e)

**Comment by iSoron** [comment]
Thanks for the bug report, @SimonDedman. This should be fixed in v2.1.2, which is already available for [beta testers on Google Play](https://play.google.com/apps/testing/org.isoron.uhabits).

@SimonDedman This looks like a separate issue, related to the color of the habit. It will be fixed in v2.1.3. As a workaround, could you select another shade of white/grey for "Friends"?

**Comment by SimonDedman** [comment]
Nice one, can't see 2.1.2 yet but sure it'll drop soon. Colour change did the trick - cheers!
