### ISSUE TITLE
Loop Habit Tracker fails to automatically transition to a new day

### ISSUE THREAD

**Issue by keystrike** [iSoron/uhabits#1709]
**Description**
The Loop Habit Tracker does not automatically update to the next day. Instead, the application has to be manually closed and reopened for the new day to reflect.

**Steps to reproduce**

1. Open the Loop Habit Tracker application and monitor or input your habits for the current day.
2. Leave the app running, or in the background, overnight.
3. Open the application the next morning.
4. Observe that the application is still reflecting the previous day's data.
5. Close and reopen the application, which then correctly updates to the new day.

**System information**
Phone: Samsung S23+
Phone Operating System: Android 13, May 2023 patch level
App version: 2.1.1

**Comment by iSoron** [comment]
Thanks for the report, @keystrike. The app is already supposed to refresh at midnight, but there was a bug preventing it from working correctly (8b55ffb147cb3d015e60b2db7aec5a3a0854270e). If this issue is still present in v2.1.3, please let us know.
