### ISSUE TITLE
un-checking a boolean habit clears it's description

### ISSUE THREAD

**Issue by KraXen72** [iSoron/uhabits#1711]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
from edit view, un-checking a boolean habit clears it's description - the description should be preserved through stats changes

## Steps to reproduce
1. Go to a habit detail view
2. Click on EDIT
3. click on a day which has a description to toggle it
4. See it toggling but losing it's description

## System information
 - phone: samsung galaxy m21
 - Phone Operating System: Android 12
 - App version: 2.1.1

## Screenshots
\-

**Comment by iSoron** [comment]
Thanks for the report, @KraXen72. This should already be fixed in Loop 2.1.2.
