### ISSUE TITLE
Incorrect Insertion of Numeric Value Instead SKIP Mark

### ISSUE THREAD

**Issue by osamz** [iSoron/uhabits#1721]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
After updating my app to version 2.1.2 through Google Play, I noticed that when I press SKIP for a field that requires numeric input, the application inserts the number 3 instead of displaying a "--" mark.

## Steps to reproduce
1. Go to any Habit that takes numbers as an input
2. Click on SKIP button.
3. See error: Instead of displaying the expected "--" mark, the application inserts the value 3.

## System information
 - Phone: Samsung Note Fe
 - Phone Operating System: Android 9.0 | OneUI 1.0
 - App version: 2.1.2

**Comment by de-es** [comment]
Can confirm the issue. It is not present in v2.1.1.

**Comment by iSoron** [comment]
@osamz Thanks for the bug report. This has been fixed in 727e88b7b11cff79bdc666406af1fd989ac7e76a and should become available in Loop 2.1.3.
