### ISSUE TITLE
Skip on quantitative habits sets 3

### ISSUE THREAD

**Issue by lllap** [iSoron/uhabits#1726]
Hello,

Since the update of early June, skipping days on habits answered by an integer rather than a boolean doesn't skip anymore, but instead sets 3.
Days that have been skipped before this update are still skipped. Days can still be skipped on yes/no habits.
My current version is 2.1.2 according to the "about" page of the app, and 13.2.4 according to F-droid.

**Comment by iSoron** [comment]
Duplicate of #1721
