### ISSUE TITLE
text doesen't wrap to multiple lines in notes

### ISSUE THREAD

**Issue by KraXen72** [iSoron/uhabits#1729]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
longer notes don't wrap the text, instead they add horizontal scrolling (worse ux) (regression from previous version)
![Screenshot_20230605-175903_Habits.png](https://github.com/iSoron/uhabits/assets/21956756/4b01d81f-9b15-474c-92ae-4112dada4dcc)

![Screenshot_20230605-175950_Habits.png](https://github.com/iSoron/uhabits/assets/21956756/12eba95b-9e3b-4235-b8d7-db4055661786)

## Steps to reproduce
see screenshot

## System information
 - Phone: Samsung galaxy M21
 - Phone Operating System: Android 12
 - App version: 2.1.2

## Screenshots
see description

**Comment by iSoron** [comment]
Thanks for the bug report, @KraXen72. Fixed in 9ca1aa911a2a73cbb10e00303aa51fd490fd2741 and will become available in Loop 2.1.3.
