### ISSUE TITLE
Number of days displayed locked at 3

### ISSUE THREAD

**Issue by Leogendra** [iSoron/uhabits#1747]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
The number of days displayed is locked at 3

## System information
 - Phone: Samsung S20
 - Phone Operating System: Android 13
 - App version: 2.0.3

## Screenshots
![Screenshot_20230622_002120_Habits.png](https://github.com/iSoron/uhabits/assets/61588710/e70cb717-b362-42a0-bb1e-680bdc2dc5e1)

**Comment by ezio-melotti** [comment]
If you want to see the previous days, you can either drag the header with the days/dates to the left or open the individual habits.
I think the number of visible days/columns is fixed and depends on the width/resolution of the screen, so you can either turn your phone into landscape mode or change the screen resolution (if possible).  My phone has 1080×2220 resolution and I can see 5 columns in portrait mode and 11 in landscape mode.
