### ISSUE TITLE
"Hide completed" should hide not daily habits when they are done during previous days

### ISSUE THREAD

**Issue by ettud** [iSoron/uhabits#1756]
https://github.com/iSoron/uhabits/blob/e4d2c93a1d5cdb6cb3a007cd45ce7b5b8e44dbcb/uhabits-core-legacy/src/main/common/org/isoron/uhabits/backend/MainScreenDataSource.kt#L58
`habit.type == HabitType.NUMERICAL_HABIT && checkmarks.getValue(habit)[0].value * 1000 < habit.target`
Here only the current day is checked. However, imagine we have a weekly habit: a sum of the whole week should be checked. Same goes for boolean habits: if a mark was set during some time period (that should be calculated from frequency) a habit should be hidden. I also believe the app should check user culture to determine, which day is the first day of the week.

**Comment by hiqua** [comment]
Can you edit your title to better reflect what you mean?

> I also believe the app should check user culture to determine

That's a setting.

**Comment by iSoron** [comment]
Thank you for creating this issue, but we are closing it as it does not follow our bug report template. Please edit your issue to follow our bug report template and make sure to include all the required information (description of the problem, steps to reproduce and system information).
