### ISSUE TITLE
How often should widgets update?

### ISSUE THREAD

**Issue by Graystripe17** [iSoron/uhabits#176]
Hi, thank you for making this project open sourced and free. I have looked at it in addition to the documentation to learn about widgets.

For the time to update on the daily widget checks it refreshes every hour. I wanted to know your thoughts on increasing this time interval? It's not a big issue.

Thanks!

**Comment by iSoron** [comment]
Yes, we could increment this interval. It is currently only important for updating the widget at midnight.

In theory, we could use AlarmManager to update the widget at precisely the correct time, and remove the automatic refresh completely, but in practice, AlarmManager is so unreliable that I would not trust doing this.

**Comment by SimonDedman** [comment]
I'm not sure if this is related but often in the morning my widgets will still be lit from the day before. If I click one that was still lit from yesterday, there's often a long lag before it, and all the other widgets, reset to the state for the current day. Is there a way this could be improved, do you think? Thanks.
