### ISSUE TITLE
Text in FrequencyPickerDialog is very small

### ISSUE THREAD

**Issue by kidager** [iSoron/uhabits#1817]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
When opening the frequency picker dialog from:

* the notification bar
* or the widget

will cause the confirmation button text to be very small (see `Screenshot 1`)

When opened from inside the app, it seems to be sized correctly (check `Screenshot 2`)

## Steps to reproduce
1. Have/Add a `Measurable` habit
2. Add the `Checkmark` widget
3. Click on it to edit the measure value of the habit
4. The `OK` button should not be sized correctly

## System information
 - Phone: Sony Xperia 1 V (XQ-DQ54)
 - Phone Operating System: Android 13
 - App version: 2.0.3

## Screenshots
| ![Screenshot_20230823-155728~2](https://github.com/iSoron/uhabits/assets/3314980/e4655f25-2869-41c7-a553-b633eda65310) |
|:--:|
| *Screenshot 1* |

| ![Screenshot_20230823-155713~2](https://github.com/iSoron/uhabits/assets/3314980/90b0ec58-8e2f-4ed5-b610-7a7294129925) |
|:--:|
| *Screenshot 2* |

**Comment by nong-fu123** [comment]
I have another request. I have a lot of habits to develop, such as drinking water on time and exercising, but only one habit can be added to the desktop widget. Is there a way to solve this?

**Comment by M3LNYK** [comment]
I have the same issue, but on different device. 
System information
Phone: Samsung Galaxy A41
Phone Operating System: Android 12
App version: 2.0.3

**Comment by kalina559** [comment]
Looks like a similar issue to #1093 solved with #1096

**Comment by iSoron** [comment]
Already fixed in the newest version of the app.
