### ISSUE TITLE
No notification, when Goaltype is set to "Maximum"

### ISSUE THREAD

**Issue by aydinio** [iSoron/uhabits#1819]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
There is no Notification, if Goaltype is set as Max. So the reminder wont work with this settings.

## Steps to reproduce
1. Create a Habit (Messurable) with reminder.
2. Specs: 
- Name: XYZ
- Question: Why not working?
- Unit: Std
- Goal: 0
- Everyday
- Goaltype: Max
- Reminder: 11:00
- Everyday

3. As soon as it changes to Min, notification works.

## System information
 - Phone: OnePlus 6
 - Phone Operating System: LineAgeOs 20
 - App version: 2.1.2

**Comment by not-matt** [comment]
Also experiencing this issue. Android 14 on pixel 6.
Changing from max to min and the notification appears.

**Comment by iSoron** [comment]
Fixed by #1931
