### ISSUE TITLE
Completed issues not marked correctly

### ISSUE THREAD

**Issue by woj-tek** [iSoron/uhabits#182]
So I mostly use notifications to mark issue as done (while at it - in-app UI to mark the issue is quite weird and often I need to try it a couple of times as it doesn't register) and today I've noticed, after opening the app, that even though I marked the issues previous days, they were not correctly marked in the list in the application.
And then a really weird thing happened - I've decided to mark them manually (as I was 99,99% sure I've done them) and... all days when I selected "done" in the notification was correctly marked.
My guess is that notification action made an update to the database but upon opening the app it didn't reload the fresh data but displayed the cashed values, and only after doing manual change there it triggered "save and reload" action (just a guess from the looks of it, haven't looked at the sources)

**Comment by iSoron** [comment]
I believe this issue has been fixed in version 1.6.0. If you meet this problem again, please feel free to post a comment here, and I will reopen this issue.

**Comment by woj-tek** [comment]
Unfortunatelly 1.6 is not available in fdroid yet and apk in github renders error (without any message) whilte trying to install (different signature?)
