### ISSUE TITLE
Archive habits option disappeared

### ISSUE THREAD

**Issue by abellacirera** [iSoron/uhabits#1833]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [ ] I have searched for similar issues, but did not find any matches.

## Description
It used to be possible to archive tasks (which was super useful for habits that are not relevant in the current moment, but will be in the future). I can't find the option of "archive" anymore. I believe this is a bug unless you intentionally removed it. 

## Steps to reproduce
1. Go to a task
2. Click on 3 dots
3. Only options are "export" or "delete" no option to "archive"

## System information
 - Phone: Google Pixel 7
 - Phone Operating System: Android 14
 - App version: 2.1.3

## Screenshots

![WhatsApp Image 2023-09-18 at 13 20 13](https://github.com/iSoron/uhabits/assets/145316954/d1c073ca-44ab-43f7-9b9c-199860c275b3)

**Comment by hiqua** [comment]
I don't remember if the option was there once you've opened the habit, but it's still there right after you open the app: long-press a habit to select it, then open the menu, and you should see the "archive" option.

**Comment by abellacirera** [comment]
Oh now I see it.. I was not doing the long press! Super helpful thank you
so much for your answer.

This app is one of the things that has the biggest impact in my life in my
journey of self improvement so I'm really grateful to you for creating it.
I love how simple, beautiful, easy and amazing it is!! Big thanks!

Laura

**Comment by hiqua** [comment]
Great, thanks!
