### ISSUE TITLE
Multiple widgets don't work anymore 

### ISSUE THREAD

**Issue by antre-mate** [iSoron/uhabits#1835]
Hi before was possible to use a widget with multiple habits, so that you can scroll down to change the habit. Then with an actualisation it was not possible anymore to click the widget and go direct to the app. Now it is possible again, but it isn't to add multiple habits in one single widget.

**Comment by hiqua** [comment]
Yes, feature removed (with rationale) there: https://github.com/iSoron/uhabits/commit/1df9cc7664c9f896ddedff8ecfd5f2f35afb0d1f

**Comment by antre-mate** [comment]
Thank you for your answer. It's a pity I thounk it a very useful funtion. Is there any way to create a multiple widget again? Reinstal an old version of the app or someting like that?
Thank you!

**Comment by hiqua** [comment]
I'd advise against it, as it was a buggy feature in the first place.

**Comment by catdevnull** [comment]
related #1897
