### ISSUE TITLE
Delaying notifications not possible anymore

### ISSUE THREAD

**Issue by ElitCoder** [iSoron/uhabits#1837]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
Upon receiving notifications from Loop Habit, there was 3 options for each notification: Yes, No or "Later". For some reason, the "Later" option has vanished from my personal phone (it's still there on my work phone for some reason, same app version). The "Later" option was really useful as it meant it was possible to distribute certain habits during the day that normally doesn't occur at the same time each day. Snoozing notifications is one workaround, but it doesn't seem to support over 2 hours of delay or a custom notification time and checking the same habit for previous days would remove the snoozed notification.

Re-creating habits / clearing app data / re-installing the app / rebooting the phone etc. doesn't fix it. No system update from Samsung the past 6 months.

## Steps to reproduce
1. Create a new habit with a reminder at time X
2. See that the notification at time X doesn't include the "Later" option

## System information
 - Phone: Samsung Galaxy S10e
 - Phone Operating System: Android 12
 - App version: 2.1.3

## Screenshots
S10e missing the "Later" option (ignore the system snooze option, added that as a remedy for now):
![Screenshot_20230922-090413](https://github.com/iSoron/uhabits/assets/22217922/c93b62b5-66d6-4d93-b4c0-a4da9aabbd79)
Work phone with the "Later" option (SENARE):
![_20230922_090501](https://github.com/iSoron/uhabits/assets/22217922/1cc909d6-f1a1-430b-9cc6-fddd4a0ed41d)

**Comment by hiqua** [comment]
Thanks! But see https://github.com/iSoron/uhabits/issues/1831#issuecomment-1719987692.
