### ISSUE TITLE
Please dark the white splash screen if app theme is dark

### ISSUE THREAD

**Issue by revuwa** [iSoron/uhabits#1856]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
If the app uses dark theme (or not) and is cleared from the recent apps, the next start will flash your eyes with a very bright (white) splash screen. (If the app is not cleared from the recent apps, this is not the case).
I know that this behavior is intentional, but could you please make the splash dark or black if 'dark theme' is activated, so that I don't feel looking into the sun, while trying to check a habit, just before i go to sleep in the dark bedroom?

## Steps to reproduce
1. Clear the app from the recent apps, or just to "clear all" recent apps.
![image](https://github.com/iSoron/uhabits/assets/7300276/4db9de9b-50eb-4bfc-89d9-b6a628adb10a)
2. Start the app and you will initially see the white splash screen, which burns your eyes, (especially at night).

## System information
 - Phone: [Google Pixel 8]
 - Phone Operating System: [Android 14]
 - App version: [2.1.3]

## Screenshots
Screenshots are sadly not possible of this behavior.

**Comment by max-k2** [comment]
@SIKV can I get a debug APK with the changes you made? It seems like an official release would take some time, and my system couldn't build it for whatever reason.

**Comment by SIKV** [comment]
@max-kyou try do download build artifact here -> https://github.com/iSoron/uhabits/actions/runs/7121424704?pr=1888

**Comment by SIKV** [comment]
@max-kyou what's your device theme? is it dark?

**Comment by SIKV** [comment]
@max-kyou thank you for finding it. Here's the updated debug apk with the fix

[uhabits-android-debug.apk.zip](https://github.com/iSoron/uhabits/files/14030644/uhabits-android-debug.apk.zip)

**Comment by revuwa** [comment]
Thanks to all of you ️❤️
