### ISSUE TITLE
Some habits wrongly marked

### ISSUE THREAD

**Issue by gildasio** [iSoron/uhabits#1864]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description

Some of my habits starts the day as marked in a way that if I check "Hide entered" they are hidden but I had not entered they yet.

## Steps to reproduce

Sorry I can't notice a pattern on reproduce it.

## System information
 - Phone Operating System: Android 10
 - App version: 2.1.3

## Screenshots

- "Hide entered" not checked:

![image](https://github.com/iSoron/uhabits/assets/6231305/0953bf6f-a58d-4edb-89b5-379db445f2b8)

- "Hide entered checked:

![image](https://github.com/iSoron/uhabits/assets/6231305/2ba11707-7639-4a30-b1c0-2010eb3f85cb)

**Comment by hiqua** [comment]
They are marked this way because you don't have to complete them on this day, since you did them enough in the previous days for the goal you set. The label of the option is a bit misleading in this case.

**Comment by gildasio** [comment]
Ummm very good to know, thanks!

I'm closing this issue as it is not a bug.
But can reopened in order to fix the label, if you want to.
