### ISSUE TITLE
[bug] 1.6 Beta Won't open

### ISSUE THREAD

**Issue by that0n3guy** [iSoron/uhabits#189]
I own a nexus 5x on Android 7.0 and after updating to the 1.6 beta the app won't open.

It "opens" by flashing a white screen then closes.  I still get notifications though.

Let me know how to find the logs and I'll send ya some more info.

**Comment by that0n3guy** [comment]
Oh, I just saw v1.6.1 (https://github.com/iSoron/uhabits/releases/tag/v1.6.1) maybe that fixes it.   I can't update on google play yet, but maybe it will go live soon.

**Comment by iSoron** [comment]
Yes, that has been fixed in 1.6.1.
