### ISSUE TITLE
Bug: Days are listed in reverse order by default.

### ISSUE THREAD

**Issue by mathwhiz1212** [iSoron/uhabits#1891]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
Days are listed in reverse order by default.

## Steps to reproduce
1. Install a fresh copy of Loop 2.1.3 from F-Droid.
2. Observe that the days of the week are backwards even though I haven't changed any settings (see screenshot below). 

If I enable "Reverse order of days" the order is no longer reversed, but it's asking for data from a few days ago instead of today (the 11th).

## System information
 - Phone: Samsung Galaxy A14 5G
 - Phone Operating System: Android 13
 - App version: 2.1.3

## Screenshots
![Screenshot_20231211_024054_Habits](https://github.com/iSoron/uhabits/assets/11021683/212aa3df-4789-495e-89c2-cbab1138b1b0)

![Screenshot_20231211_024117_Habits](https://github.com/iSoron/uhabits/assets/11021683/5ca5cfa0-362c-499f-b2d4-332e1b48fb15)

With the reversed order enabled:

![Screenshot_20231211_030020_Habits](https://github.com/iSoron/uhabits/assets/11021683/89266112-1da0-40f1-8957-c0aceeebacaf)

The date changes again if I rotate into landscape mode (only when the reverse order option is enabled):

![Screenshot_20231211_030312_Habits](https://github.com/iSoron/uhabits/assets/11021683/fe018195-f6d5-48b2-bab1-119104dba5d0)

**Comment by hiqua** [comment]
Isn't it just about the default being different from what you expect? As in, the "reverse" is just the reverse of the default?

**Comment by mathwhiz1212** [comment]
Indeed. In retrospect, I'm not sure why I made this issue. I've grown to prefer the default sequence.
