### ISSUE TITLE
Stacked widget(s) unavailable in android 14

### ISSUE THREAD

**Issue by rlh1994** [iSoron/uhabits#1897]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
When I go to add widgets from the app on android 14, the stacked widgets are not available. Only 6 widgets are available. I have tried uninstalling and reinstalling the app.

## Steps to reproduce
1. Install the app
2. Hold down on the homepage to add a widget
3. Expand Habit widgets

## System information
 - Phone: Google Pixel 6a
 - Phone Operating System: Android 14
 - App version: 2.1.3

## Screenshots
![Screenshot_20231226-230942](https://github.com/iSoron/uhabits/assets/8260415/7e6b696b-0df5-40bc-893e-7a2bb3e66878)

**Comment by saeedesmaili** [comment]
Apparently removed in this release: https://github.com/iSoron/uhabits/releases/tag/v2.1.2

**Comment by ccornici** [comment]
+1, Im missing this feature :(

**Comment by hiqua** [comment]
Removed intentionally in https://github.com/iSoron/uhabits/commit/1df9cc7664c9f896ddedff8ecfd5f2f35afb0d1f.
