### ISSUE TITLE
Today's View

### ISSUE THREAD

**Issue by nj999** [iSoron/uhabits#190]
Hello,

thanks for this great app. I am using it actively. But I wanted to request if we can get a daily/today view. So I can just see my habits for today. Also, we want to mark failed rows as failed (it is in another thread), completed rows as done and show pending rows. So we would like a filter on Today's page to only show "pending" items, this way we can focus them for today and get it done. I have about ~100 habits and wanted to mark things as done/failed and only look at pending so that I can focus on those for today. Otherwise it gets very difficult to look thru all items together.

I read thru all other requests, but didn't see this request. Please consider this as your enhancement for future.

Thanks

**Comment by jc737** [comment]
I would like to second this option :)

**Comment by haohodev** [comment]
Yeah ,guys i'm a primary developer.I'll try my best to make it soon.

**Comment by iSoron** [comment]
Hi @nj999, this feature already available in the beta version of the app. You can filter out habits that have been marked as completed. When #144 gets implemented, the failed habits will be removed too. For this reason, I am closing this issue as duplicate.
