### ISSUE TITLE
Possibility to add "comment" or "Note" on a specific day ?

### ISSUE THREAD

**Issue by akhater** [iSoron/uhabits#194]
I will try to give an example, I have as habit to sleep at least 7 hours / night and last night I had an overnight at work so, obviously, I failed this habit, but I would like to have a way to add a note to that day explaining why I failed it would help when looking back to understand what happened on a particular day

thanks

**Comment by YPetremann** [comment]
Would be also be great for things like bloging or diversification habits

**Comment by foobarbazquxfred** [comment]
It would also be nice if any numeric "note" left could be graphed. So a user could see how many minutes he meditated this month, for example.

I would be willing to contribute to a bounty for the note feature, FWIW.

**Comment by Rightmanj** [comment]
It will also be useful for swimmers or runners, in order to keep truck the time and distance.

**Comment by iSoron** [comment]
@Rightmanj This will be covered by numerical habits (see #42)

**Comment by holocircuit** [comment]
I'd also like this, and would be willing to write it.

I'm not sure about the best way to do it with the interface though. Perhaps "super-long press" should bring up a menu with an option to add a note?

**Comment by tickTackHack** [comment]
I'm also willing to give it a shot to implement this.  I would recommend making the input length restricted to a relatively short length. Maybe 240 characters? This can help with keeping the database size small and help deter security issues.

**Comment by c33s** [comment]
not sure it makes sense to restrict the length of the field. i personally see no benefit on having a "small"  database. it looks like the performance impact is not that huge (should be tested on an android device before of course). the devices all have quite a lot of space, so keeping the size small does not really matter.  
even if someone writes a long text to 10 habbits, it is still only text. so it is not really big in size.
 
> I recognized, that performance drastically increases with table size dropping. I found:
> 
>     1.6M entries 327 ms w/o indexing => 29.7 ms with indexing
>     670k entries 149 ms w/o indexing => 28.8 ms with indexing
>     280k entries 71 ms w/o indexing => 28.5 ms with indexing
>     147k entries 44 ms w/o indexing => 28.0 ms with indexing
>     19k entries 25 ms w/o indexing => 25.0 ms with indexing
https://stackoverflow.com/q/33456278

> I've created SQLite databases up to 3.5GB in size with no noticeable performance issues. If I remember correctly, I think SQLite2 might have had some lower limits, but I don't think SQLite3 has any such issues.
> 
> According to the SQLite Limits page, the maximum size of each database page is 32K. And the maximum pages in a database is 1024^3. So by my math that comes out to 32 terabytes as the maximum size. I think you'll hit your file system's limits before hitting SQLite's!
https://stackoverflow.com/a/786146

some sort of export text or archive text (to delete the text for a certain period) would be nice.

**Comment by fiosmiles** [comment]
Would love this, just started using the app and the ability to comment on a daily habit (along with the idea of "not done" which I see under discussion),  e.g. flossing habit - "travelling and forgot to bring floss!" And being able to access the notes in a journal style when you open a habit. The calendar could have a small icon modified to indicate there is a note.

**Comment by kpuljek** [comment]
+1 for this, i'm trying to watch more movies and it would be great if I could add their name to individual entries

**Comment by doublehelix24** [comment]
Another +1. Would love this and used this feature a lot in HabitBull.

**Comment by heretoenhance** [comment]
+1 Any update on this one?

**Comment by nottheend** [comment]
+1
It would be beneficial in cases, where a habbit couldn't be placed on a specific day. It is helpful on retrospectives to understand better the (missing) progress of the habbit

**Comment by gaborod16** [comment]
+1
Really love the App, I would even contribute to this feature if it gets into the planning.

**Comment by KristianTashkov** [comment]
@iSoron If we ever merge the advanced options dialog, notes become a very easy continuation of it. I originally planned to implement it after we merge the dialog into master.
