### ISSUE TITLE
Color scheme option

### ISSUE THREAD

**Issue by evitalis** [iSoron/uhabits#195]
Would it be possible to include the [solarized](http://ethanschoonover.com/solarized) color scheme in additional to the standard day/night options?

**Comment by iSoron** [comment]
Thank you for the suggestion, @evitalis, but I have no plans on adding additional themes to the app. Themes are surprisingly difficult to implement in Android, and even having just day/night already made the code considerably complex. If someone does submit a pull request implementing this, however, I might reconsider.
