### ISSUE TITLE
Allow Monday as a start of the week option

### ISSUE THREAD

**Issue by xvdd** [iSoron/uhabits#197]
Could you consider implementing a checkbox option in the settings to allow Monday as start of the week?
It would be reflected in the Habit Strength (when week is selected) and in the History view. 

This is always a small confusion for us Europeans ;-)

**Comment by sciamano** [comment]
Actually, the app is aware of the locale settings, that means if the locale says the week starts with Monday, it will show the Monday as start of the week.
Just check it with an european locale, i.e de_DE/German etc

**Comment by xvdd** [comment]
Thanks for checking!
I have switched from en_US to en_UK and the application now uses Monday as start of the week. 
I haven't thought to try as Google offer this as one of the few settings in its own calendar app.

**Comment by Stefan-Hell** [comment]
I just want to add that this workaround does not work for anyone. My smartphone (Fairphone 1st gen, Android 4.2.2) does not offer an English UK option, so I would need to change the language to a non-English one in order to get the week starting at Monday.
