### ISSUE TITLE
可量化中的目标类型：至多。无法正常添加

### ISSUE THREAD

**Issue by jxch** [iSoron/uhabits#1971]
选择至多点击保存后，列表中并没有添加成功。
版本：2.2.1
系统：安卓13

**Comment by hiqua** [comment]
```
Type of target in quantifiable: up to. Cannot be added properly .

After selecting up to and clicking save, the list is not added successfully.
 Version: 2.2.1
 System: Android 13
```

I don't think we can reproduce this bug with so little information unfortunately, if you have more details, please do share.

Automated translation (apologies for mistakes):
如果您有更多详细信息，请与我们分享（自动翻译）。
