### ISSUE TITLE
Malfunction with the toggle in settings "use pure black in dark theme"

### ISSUE THREAD

**Issue by despinakouli** [iSoron/uhabits#1973]
**Malfunction with the toggle in settings "use pure black in dark theme", does not function until you change pages**

**How to reproduce:**
1. Launch Loop Habit Tracker
2. Click on more icon at top right
3. Click on settings
4. Toggle on "use pure black in dark theme"

**Expected behavior:**
Current page background turns pure black

**Actual behavior:**

https://github.com/SOEN345-Winter24OtherSection/alldiscussion/assets/97748664/335a345d-6e4f-420b-ab69-956f8d00211a

_pure black theme is only applied when you exit the page_

**Android version:**
14.0

**Device** 
Medium_Phone_API_30

**Android emulator version:**
33.1.24

**Comment by hiqua** [comment]
I guess it could change before, but I think the current behavior is also fine.
