### ISSUE TITLE
Issue in the month labels of the habit strength graph

### ISSUE THREAD

**Issue by xvdd** [iSoron/uhabits#199]
On the first of November 1.30am UTC time (and probably every first day of every month), the habit strength graph in the month view does not display September in the month axis. 

The last two points seems to be September and October but they have the axis label of October and November. 

Is this an expected behavior?

Edited to add screenshot:
App version 1.5.6 Android
![screenshot habit month label](https://cloud.githubusercontent.com/assets/23172519/19892511/2f6a2d1c-a080-11e6-81b1-a1e32fede286.jpg)

**Comment by iSoron** [comment]
This is probably a bug. Thanks for letting me know.

**Comment by jtrollkarl** [comment]
What device did this occur on? I've tried to replicate this on both a nexus 5 and 4, but can't get it to occur. I see all months properly in my case.

**Comment by xvdd** [comment]
This happened on a Sony Z3 running Android 6.0.1
But I don't think it's related to the Android version or the phone.

Note that this is happening only on the first of the month. On the second I've checked and the display was normal. 

Anyway this is really just a minor bug.

**Comment by iSoron** [comment]
This has probably been fixed along the way. If anyone still experiences this issue, please let us know.
