### ISSUE TITLE
Please add it to F-Droid

### ISSUE THREAD

**Issue by SecUpwN** [iSoron/uhabits#2]
Seems like a wonderful app that screams to be published on [F-Droid](https://f-droid.org/)! :scream_cat:
Please also add a button with the F-Droid link like done for GooglePlay.

**Comment by iSoron** [comment]
The app has already been added to F-Droid. See this [commit](https://gitlab.com/fdroid/fdroiddata/commit/667ad271d133b8c59059ca851d33bc81dbe7cdcc). It should appear in a few days.

**Comment by iSoron** [comment]
By the way, you can also download the APKs directly from the [release page on GitHub](https://github.com/iSoron/uhabits/releases).

**Comment by SecUpwN** [comment]
Thanks for crating this wonderful app, it just appeared on F-Droid. Installed it right away. :+1:
