### ISSUE TITLE
[1.6.2] Notifications not showing up

### ISSUE THREAD

**Issue by woj-tek** [iSoron/uhabits#200]
I've added 1.6.2 version in the header as I'm currently using it, but the notifications were randomly missing in previous versions as well.
So I have a couple of habits/notifications set at 6am or 7am, and recently I've been getting up at around 8-9am. I've noticed, that quite frequently those earlier habits are not gnerating notifications and I have to open uhabits and check the list (and mark those manually when I'm reminded about them while looking at the list).
My suspicion is that somehow doze is responsible - device enter deep-sleep mode and then any possible notifications are not generated/displayed. Could it be somewhat related to #172 ?

**Comment by licaon-kter** [comment]
You did except uHabits in Doze/Battery things?

**Comment by iSoron** [comment]
This is the same issue as #160. If you have any information that might help diagnose this problem, could you please post it there? At least in theory, the app should work fine with doze.

**Comment by woj-tek** [comment]
OK, excluding uhabits from doze seems to resolve the issue....
