### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by egs2003** [iSoron/uhabits#2003]
Bei Eingabe einer Zahl erscheint nicht das zugehörige Zahlen Layout der Tastatur

Wenn der Habit keine Notiz hinterlegt hat, taucht bei Eingabe trotzdem immer das leere Notizenfeld auf. Das sollte ausgeblendet sein, wenn es gar keine Notizen gibt.

**Comment by iSoron** [comment]
Thank you for creating this issue, but we are closing it as it does not follow our bug report template. Please edit your issue to follow our bug report template and make sure to include all the required information (description of the problem, steps to reproduce and system information). Also, please post in English.
