### ISSUE TITLE
Unhide habits immediately when "[x] Hide" is cleared (but hide them some time after they are made complete and hideable)

### ISSUE THREAD

**Issue by aleksejrs** [iSoron/uhabits#205]
In 1.6.2, issue #204 makes those actions take an unknown time.

1. Unhide: Loop should know why a habit is hidden (archived or complete), so it would be able to unhide it immediately (even if not loaded yet).
2. Hide: even when (after the other issues have been fixed) Loop can find out quickly that a habit is to be hidden because it's complete, it still should give the user some time to untick the box.

**Comment by iSoron** [comment]
This should no longer be an issue in the next version of Loop (1.8.0). If you are still experiencing this problem after the new version is released, please let me know.
