### ISSUE TITLE
Window switching (including returning to the list) triggers a reload of all habits. (Activity indicator doesn't stop if windows are switched while it is active.)

### ISSUE THREAD

**Issue by aleksejrs** [iSoron/uhabits#206]
v1.6.2

1. Wait until the activity indicator stops (everything is loaded).
2. Toggle a checkmark.

* Now, if I just wait, the indicator stops in a second or two, and so the mark seems to have the new value.
* But if I press a window-switching button (window list or desktop), the indicator doesn't stop (ever?) after I re-activate the Loop window.

**Comment by iSoron** [comment]
This should no longer be an issue in the next version of Loop (1.8.0). If you are still experiencing this problem after the new version is released, please let me know.
