### ISSUE TITLE
Can't dismiss notification

### ISSUE THREAD

**Issue by pushcx** [iSoron/uhabits#207]
Hey folks, thanks for an easy, incredibly useful app. I especially like the hints in the app that teach how to use it. I may have found a place where one more hint would be useful.

I ran into something that I think is a bug (but might be my lack of familiarity with Android). I think this is related to #106.

I created a habit and set it to repeat 3 times in 7 days, with a reminder any day of the week - I don't care which days it happens, but it needs to happen three days a week. Day one, got a reminder, did it, great. Day two, got a reminder, didn't want to do it... and there's no way to dismiss the notification.

Tapping the notification goes to the app, but the notification also stays. Expanding it, the options are "check" and "later". Check isn't appropriate as the habit won't happen today, and later only hides for a few minutes. Long press or swiping left/right shows a gear that leads to Android settings for whether this app is allowed to use notifications.

Is there a gesture interface I'm missing, or is this a bug?

**Comment by iSoron** [comment]
Can you check if you have the option "make notifications sticky" enabled on the settings? If so, please disable it, and then try to swipe the notifications away.

**Comment by pushcx** [comment]
Ah, yep, this was my mistake. I unchecked that setting, set the reminder time to a minute away, and was able to swipe away the notification. Thanks for your help, sorry for the hassle.
