### ISSUE TITLE
1x1 habit widgets intermittently don't update themselves on click using Nova Launcher

### ISSUE THREAD

**Issue by slix** [iSoron/uhabits#208]
I'm using Nova Launcher and Android 7.0. I have some of the habit widgets on my homescreen. When I click one, I expect the color the update instantly to "checked". The widget has its white fade-in-and-out effect, but it frequently it stays the same post-click. If I open the app, the habit is checked for the day.

If I wait a while (5 seconds to a minute), the widget eventually changes color. If I force an update somehow, like by holding the widget and selecting "resize", the widget changes color.

It's unclear whether the problem is in Nova or in uHabits. The issue comes and goes. Sometimes the widgets will update immediately for minutes at a time no matter how I click. Sometimes none of them will update.

I'm willing to contribute a fix. But I'm curious if anyone else is experiencing this issue.

**Comment by iSoron** [comment]
Thank you for reporting this. I also use Nova, but I have never experienced this issue. If anyone is also experiencing this and knows how to reproduce it reliably, please, let us know.

**Comment by SVNKoch** [comment]
I think this is an Android (7?) bug and not related to either Nova nor uHabits.
My dad and a friend of mine had issues with widgets not updating properly. Can't remember which app it was for my dad but for my friend it was a alarm widget (Samsung OS included app I think)

**Comment by iSoron** [comment]
I have not heard from anyone else regarding this issue, so I assume it's fixed. If anyone is still experiencing this, please feel free to comment.
