### ISSUE TITLE
Cant import full backup

### ISSUE THREAD

**Issue by castor-troy** [iSoron/uhabits#211]
I changed my phone and tried importing complete backup from my old phone to the new one. I am unable to do so, it shows the error "failed to import data".

Is loop habits dependent on Google play services? I am asking this because, I dont have google play services on my new phone.

**Comment by iSoron** [comment]
Could you please try to import the data again, then generate a bug report from within the app? Loop does not require any third-party services, such as Google Play.

**Comment by castor-troy** [comment]
Sometimes, when I open the app, I get the message "Unfortunately, Habits has stopped" and it doesnt allow me to open. It's happening now. I will try to "clear data" from Apps in Android > Settings and has tried again.

I was able to generate the bug report, but I get the mssage "habits has stopped again".

I found two files in the Logs folder that I am attaching. Hope that will help.

**Comment by castor-troy** [comment]
[Log 2016-11-24 163944.txt](https://github.com/iSoron/uhabits/files/611170/Log.2016-11-24.163944.txt)
[Log 2016-11-24 163945.txt](https://github.com/iSoron/uhabits/files/611171/Log.2016-11-24.163945.txt)

**Comment by iSoron** [comment]
Thank you for the logs. The problem is that you are trying to import a backup that was created by a newer version of the app. Your phone has Loop 1.5.6 installed, but the backup was generated by Loop 1.6 (beta). Could you upgrade the app and try again? F-Droid should have the newest version.

**Comment by castor-troy** [comment]
Thank you very much. I will try the latest version now. FYI, I downloaded the app from "APKpure" which might not have the latest version.

**Comment by castor-troy** [comment]
Wow, it worked like a charm. Didn't have to import again. 👍

**Comment by licaon-kter** [comment]
@castor-troy Why don't you have [F-Droid](https://f-droid.org/) ?
