### ISSUE TITLE
[question] Does too many habits slow down the app?

### ISSUE THREAD

**Issue by castor-troy** [iSoron/uhabits#214]
I have about 15 habits and "Don't show completed" enabled. Whenever I check a habit, it takes about 5 seconds to disappear. Does too many habits make the app slow?

**Comment by iSoron** [comment]
Sorry about the delay, @castor-troy. Yes, having many habits will certainly make the app slower. How many habits are too many? It depends on your phone. Just for comparison, the 4-year-old Nexus 4 is able to handle 50 habits with ease.

The option to hide completed habits is still new, and will certainly improve in the next versions of the app. If you are having performance problems, I would suggest disabling it for now. Archiving old habits can also help improving the performance.

**Comment by castor-troy** [comment]
I have about 20 habits. I added widgets and its taking time to check them too. I guess there is nothing that can be done, other than reducing the number of habits or getting a better phone.
