### ISSUE TITLE
Add option to not show a notification for an already checked item

### ISSUE THREAD

**Issue by licaon-kter** [iSoron/uhabits#215]
Say you check the habit at 10 a.m. but the notification is at 12 a.m., that's unneeded.

**Comment by iSoron** [comment]
The app should not be showing notifications for habits that have already been checked. Are you sure this is happening? Can you trigger this behavior consistently, or just sometimes? The notification should also disappear automatically if you mark the habit as completed in the main app.

**Comment by licaon-kter** [comment]
Every day.

**Comment by licaon-kter** [comment]
Ok, my bad, got things mixed up.
This works as expected, although I did get a crash once, but I did not catch it in a log .
