### ISSUE TITLE
Add option to change language

### ISSUE THREAD

**Issue by toroit** [iSoron/uhabits#218]
I would like to change the language of the app, but didn't found any button to do so.

**Comment by licaon-kter** [comment]
Change the device language in Android Settings?

**Comment by toroit** [comment]
@licaon-kter I would like the option to change the language without changing the language of the hole system.

**Comment by iSoron** [comment]
Thank you for the suggestion, @toroit, but I am still not convinced this is something many users need. Could you clarify why would you want your phone in one language, but the app in another language? If the translation is not good enough, please feel free to suggest improvements.

I am closing this issue for now, but I can reopen it later if there's enough demand.

**Comment by mikicho** [comment]
@iSoron It is common for non-native English speakers to have their system language set to English for better compatibility with applications, inputs, and UI. However, there is still a desire to have certain applications in their mother tongue, especially those like Habits that should feel more "natural".
I'd love you to fix this, but thank you for the app anyway! :)
