### ISSUE TITLE
Missing button on habit adding or editing

### ISSUE THREAD

**Issue by toroit** [iSoron/uhabits#219]
When adding or editing an habit, I click to schedule the habit and the "OK" button is missing:
![sem_botao](https://cloud.githubusercontent.com/assets/24425622/20954730/fe4d5f68-bc24-11e6-9a9f-6dfdf3ff0fbb.jpeg)
I tried to reduce the font size of the system, but it didn't work.

In a different app, a similar screen with hour to choose works fine (the button appears):
![com_botao](https://cloud.githubusercontent.com/assets/24425622/20954803/8080fbc0-bc25-11e6-9c00-200ba73c2e14.jpeg)
PS.: my cellphone is kinda old (Samsung Galaxy Y)

**Comment by iSoron** [comment]
Thank you for the bug report. Could you double-check what version of the app are you using? I thought this was fixed in version 1.6.2.

**Comment by toroit** [comment]
@iSoron Thanks for the reply! I am using version 1.6.2

**Comment by toroit** [comment]
In my opinion, a box with digits would be more simple to digit and choose the time.

**Comment by iSoron** [comment]
@toroit In newer versions of Android, this is what the standard time picker looks like. To keep the app consistent with the operating system, we are also using it.

**Comment by iSoron** [comment]
This has been fixed, and will be available in the next version of the app (version 1.7). For reference, here is what it looks like now:

![device-2016-12-30-130038](https://cloud.githubusercontent.com/assets/4699657/21570027/338de63e-ce90-11e6-9a53-472416a60849.png)
