### ISSUE TITLE
Graph does not properly reflect habit strength value

### ISSUE THREAD

**Issue by Weygert** [iSoron/uhabits#225]
I understand the graph's value point of the current month/year should equal the current habit strength value. Or an I misinterpreting something?

![img_20161212_175219](https://cloud.githubusercontent.com/assets/20655714/21108139/62a91790-c094-11e6-8110-233ab1af3f85.png)
![img_20161212_175117](https://cloud.githubusercontent.com/assets/20655714/21108140/62afc1e4-c094-11e6-93a4-a31bbac72b17.png)

Regards

**Comment by iSoron** [comment]
Each dot on the graph shows the average score for that time period. For example, your average score for 2016 was about 60%. The number on the top shows your score right now.

If we used the score on the last day of the interval, we would also have problems. For example, if your score was close to 100% during the entire year, every year, but then dropped to almost zero every December, your yearly graph would look very misleading.

**Comment by Weygert** [comment]
Ok, understood. Is it anyhow possible to display the exact average value of the time periods? I.e. I set myself targets and would like to know what the value the past months was.
