### ISSUE TITLE
Support record events in the past?

### ISSUE THREAD

**Issue by zhengzhiren** [iSoron/uhabits#227]
Can we support adding events in the past?

**Comment by licaon-kter** [comment]
Like this: https://github.com/iSoron/uhabits/issues/220 ?

**Comment by iSoron** [comment]
Hi @zhengzhiren, I am not sure I understand your request. It is already possible to put checkmarks in the past. Please, see the FAQ.

**Comment by zhengzhiren** [comment]
Yes. In the statistics page, I can check the past days. Thank you!
