### ISSUE TITLE
Korean translation issue

### ISSUE THREAD

**Issue by amoseui** [iSoron/uhabits#229]
I would like to fix some mistranslation on Korean. 

I joined [open translation project at POEditor](https://poeditor.com/join/project/8DWX5pfjS0) as you described in README couple days ago. However, since I am not familiar with this system, I couldn't find any process to fix translations. It's just said (pending) on Korean button. 

Do I have to wait for admission? Please help me. Thanks in advance.

**Comment by iSoron** [comment]
Hi @amoseui, I have approved your admission. You should now be able to change the translations. Thank you for volunteering.

**Comment by amoseui** [comment]
Thank you. I updated couple translations.
