### ISSUE TITLE
Inconsistent interface when marking habits

### ISSUE THREAD

**Issue by JanetQC** [iSoron/uhabits#230]
Hey,
I recently noticed a smal inconsistency in the app.
If I mark one habit, following actions will be shown:
![sel1](https://cloud.githubusercontent.com/assets/4404622/21596119/ddf710ca-d136-11e6-9035-3471cec99c4b.PNG)
If I now mark several habits, these actions will be shown:
![sel2](https://cloud.githubusercontent.com/assets/4404622/21596123/f42c0328-d136-11e6-8c1b-eb597efcfc31.PNG)

**Comment by iSoron** [comment]
The icons change according to the actions available on the list of selected habits. For example, the edit icons disappeared since it is not possible (currently) to edit multiple habits at the same time. If all the habits you select are already archived, then the archive icon will also disappear.

**Comment by JanetQC** [comment]
I thought so, but if a common user does this he just wonders what icon just disappeared and doesn't know why. Maybe put the icons that are available for sure on the far left and the optional icons on the right?
So you will either have one of these combinations:
Paint Edit
Paint Archive
Paint <blank>
It's a bit more consisten, don't you think?

**Comment by iSoron** [comment]
I think the best solution here would be to allow the user to edit multiple habits simultaneously. This could be useful, for example, for changing the frequency or the reminders for multiple habits at the same time. The second best solution would be to keep the icon there, but just disable it.

**Comment by GoodEveningMiss** [comment]
Having the icon there but disabled might serve to confuse users and make them think the action is potentially available when it isn't

**Comment by iSoron** [comment]
I no longer think this is a significant issue. I have not heard from users about this, and there has also been very little feedback here, so I am closing this issue. If anyone has ideas to improve this situation anyway, please feel free to submit a pull request.
