### ISSUE TITLE
Have an option to start the reminder x-days before the due date

### ISSUE THREAD

**Issue by ThidoE** [iSoron/uhabits#232]
I would really like it, if you can have a reminder multiple days before the habit is due.

For example:
I have an habit to go to the hair stylist every 40 days. Now I want the reminder to start 3 days before the 40 days are over, so that I can plan my appointment.

**Comment by licaon-kter** [comment]
This sounds out ef scope, you might need a notes/todo type app.

**Comment by iSoron** [comment]
Thank you for the suggestion, @ThidoE, but I also think this feature is out of scope. For habits with such long interval, and that require careful planning before the due date, a calendar app would be more appropriate.
