### ISSUE TITLE
Snooze is not working

### ISSUE THREAD

**Issue by ThidoE** [iSoron/uhabits#233]
Hi,
the Snooze option is not working for me. I tested it several times with different snooze intervals, but the notification never popped up again.

App Version is 1.6.2
My Phone is a Galaxy S6 (Marshmallow), I also deactivated the "Samsung App-Energysaver".

I have tested the 15 minute interval and kept the screen on, but the notification didn't came again, so I don't think it has something to do with Doze.

**Comment by iSoron** [comment]
Thank you for reporting this issue. This will be fixed together with #160.
