### ISSUE TITLE
Spinner menu closes on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [iSoron/uhabits#237]
When I perform these sequences of events, the spinner menu on screen disappears:

Sequence 1:
1. Click on Add icon
2. Click on Repeat spinner
3. Orientation change

Sequence 2:
1. Click on todo item in list
2. Open Habit Strength spinner
3. Orientation Change

**Comment by licaon-kter** [comment]
Given that you test so many apps, why isn't any fix written here too?

**Comment by reverse-unina** [comment]
I will work on it

**Comment by iSoron** [comment]
Thank you for reporting, but this issue has no impact on the usability of the app, so I am closing it.
