### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by Shriyanshagro** [iSoron/uhabits#245]
A web interface for this smart habit tracking app. At least to view graphs and other stats.

**Comment by licaon-kter** [comment]
What's the use case here?

Instead of opening the app you want to open a browser to http://localhost:37564 while the app is running?

Why!?

**Comment by Shriyanshagro** [comment]
Just in a case when user is not able to access his device for few days due to some circumstances(device under repairing or device is lost).
Having a web interface could always be helpful in such situations, also through a web interface one can have better vision for his/her stats of habits.

**Comment by licaon-kter** [comment]
This is not an online service... If the device is off you can't access the data.

/Close as invalid

**Comment by Shriyanshagro** [comment]
Oh Yeah, you are right this feature requires a much of running online services to handle.
And I guess those are not possible to configure at this point of time. 
But I personally love to have it as well. As it can be aid to user while he/she is not able to access the device.

**Comment by Shriyanshagro** [comment]
So let's close this issue for now.

**Comment by shamsmc** [comment]
A web interface will definitely help many users, especially users at office environment. Its not convenient to use mobile app during office hour, but you can easily open up a browser window and keep tracking & updating your habits. Cloud/web sync will help recover data if you lose your device. I prefer to use apps mobile phone when I'm travelling, but at home I always use my tablet. Cloud/web sync will help using multiple devices seamlessly.

This app can be extend beyond personal use. It can be used developing team habit or tracking repeated tasks in an easy view (a way to monetise the app/service).

**Comment by iSoron** [comment]
Thank you for the feedback, everyone. I will reconsider this issue after #104 is completely implemented and working well.
