### ISSUE TITLE
Add a donation option

### ISSUE THREAD

**Issue by rosenpin** [iSoron/uhabits#250]
I use this app on a daily basis and I feel like it really helps me being more organized.
I looked inside the app and in the README but I couldn't find a way to donate to this project.
Mind throwing in a PayPal donation link in the app or the README?
Maybe an option to support the development via in app purchases?

**Comment by iSoron** [comment]
Hi @rosenpin, I'm glad you like the app. I am not currently accepting donations, but I might in the future.

**Comment by kuba-orlik** [comment]
Please consider accepting donations, I'd likely contribute :)

**Comment by mosajjal** [comment]
+1
