### ISSUE TITLE
optional image in habit push notification

### ISSUE THREAD

**Issue by haopei** [iSoron/uhabits#252]
A picture of worth a thousand words :)

I use habit loop as a reinforcer of my habits, and to trigger certain mental states at various times of the day. For example, I remind myself to be more attentive at 6pm, during family time (pushing aside thoughts from work, and other affairs). Personally uploaded photos can hold special meaning to the user of the app, that a short sentence alone cannot capture. 

I think a photo would be a stronger reminder and motivator than words here.

Cheers

**Comment by iSoron** [comment]
Thank you for the suggestion, haopei, but in order to keep the app very simple and minimalistic, I am not planning to add this feature at the moment.
