### ISSUE TITLE
Completed German translation

### ISSUE THREAD

**Issue by pschwede** [iSoron/uhabits#253]
See https://gist.github.com/9388a56bf36566bd03296be47a93b39d

I used Stringlate for Android to do this. I have no idea if this is useful to you.

**Comment by iSoron** [comment]
Hi @pschwede, thank you for the contribution. Sorry about the delay, we were switching to a new translation platform. Please, join us at [this link](http://translate.loophabits.org/). Even if the translation is already completed, you can still proofread it and suggest changes.
