### ISSUE TITLE
Hindi translation

### ISSUE THREAD

**Issue by KushGoyal** [iSoron/uhabits#254]
Hi,
I can do Hindi translation for your guys if you want.

**Comment by anshulc95** [comment]
@KushGoyal I believe they already got the translation for Hindi done. Look at their project at [ open translation project at POEditor](https://poeditor.com/join/project/8DWX5pfjS0).

![Hindi badge 100% complete](https://drive.google.com/uc?export=download&id=0Bzl706_WJgyINDNGM0VNQUtmMDQ)

**Comment by KushGoyal** [comment]
@anshulc95 The translation if not live yet or not implemented fully. I changed my phone's system language to Hindi. Only the day names changed to Hindi, everything else was still in English.

**Comment by iSoron** [comment]
Thank you for volunteering, @KushGoyal. Hindi is already available in the beta version of the app (1.6.2), but please, feel free to join our [translation project at POEditor](https://poeditor.com/join/project/8DWX5pfjS0).
