### ISSUE TITLE
Restore problem

### ISSUE THREAD

**Issue by dwandw** [iSoron/uhabits#255]
copy an old db file to '/sdcard/Android/data/org.isoron.uhabits/files',but not shown in restore dialog.
file permission:
root:r_sdcard
rw-rw----

**Comment by licaon-kter** [comment]
Not actual SD card, when you open the import dialogue, what path does it say? That's where you need to put it.

**Comment by iSoron** [comment]
The app is probably looking for the file in the internal memory, while it is actually located in the SD card.
This confusion has been fixed in the development version. The app now allows you to pick files from other folders, or directly from Google Drive/Dropbox.
