### ISSUE TITLE
Allow data to be stored externally, so that other apps can sync it

### ISSUE THREAD

**Issue by AnderRasoVazquez** [iSoron/uhabits#26]
This would allow apps like [**Syncthing**](https://syncthing.net/) to sync the data across devices.

The idea here is not making backups or exporting the data (which will be nice too, but that would be for another issue), **the idea is having all the habits data on a directory we choose**. That way, when Syncthing (or another app) notices the changes, it will update the files on the other devices automatically and because the data is not in an exported format we won't have to import it.

**Comment by iSoron** [comment]
This is an interesting solution to the syncing problem. I will have a look at how feasible this is. That would require permission to write on the SD card, but it does look much more simple than every other solution I thought about. Thank you for the suggestion.

By the way, it is already possible to export the data. Just select multiple habits, and click the overflow menu. There should be an option there.

**Comment by AnderRasoVazquez** [comment]
Oh, I see it now! Thanks. =)

**Comment by sojusnik** [comment]
I'm opting in for sheduled daily backups to a specified folder.

**Comment by licaon-kter** [comment]
I'm opting in for a backup at every change.
Say you get hit with #109 and your data is trapped, yes root can help you, but that's a rarity though.

**Comment by iSoron** [comment]
I no longer think this is a good idea. Allowing the database file to be modified by an external app would cause all sorts of trouble, and could very easily lead to data corruption. For daily backups, I recommend using an specialized app, such as Titanium Backup. For device sync, see #104.
