### ISSUE TITLE
Add graph showing the user days they have missed

### ISSUE THREAD

**Issue by atmasol** [iSoron/uhabits#262]
Hey iSoron

Your app is very useful. Thank you.

A coupla things I found with its usage.

1) When the day clocks over to a new day the layout still shows the previous days layout. I have to shut the app down, then restart it for it to show the correct days.

2) The habit graph is really meaningful, but it would be very useful if the graph could toggle between your "habit strength" graph and an "incident graph". The incident graph would show the user what days they have missed. Useful for reflection and self motivation.

Thanks for the useful app.

Regards

Lee

**Comment by iSoron** [comment]
Thank you for the feedback, Lee. The first issue is already corrected, and should appear in the next version. As for the second issue, I don't quite understand what do you mean. By looking at the history graph, it is already quite clear to see any missed days.
