### ISSUE TITLE
Repeating doesn't work for part-week habits

### ISSUE THREAD

**Issue by woj-tek** [iSoron/uhabits#263]
So I have a couple of items with configuration that I want to do them 5 days a week (with the idea that this is "5 workdays") and reminder for such days. However this task can be executed optionally also during weekend.

I've noticed that if I mark the habit on weekend as well then I don't receive notification on the weekday (seems that if the requirement for habit is already fulfilled it disables notification?).

**Comment by bubal93** [comment]
I have the same issue.

Here I post screenshot as an example. I have a habit with '2 times per week' frequency. In all cases I did it 2 times per week, but app don`t think so. 

![screenshot_20170321-123313](https://cloud.githubusercontent.com/assets/17985872/24145721/c28aefee-0e32-11e7-8ef0-8359194a5ba7.png)

**Comment by iSoron** [comment]
@woj-tek Yes, the app will only show a reminder if the habit is pending. Since you already performed the habit five times (one during the weekend, and a few during the week), it thinks you're done, and doesn't bother you anymore. Do you propose any alternative behavior?

@bubal93 You are describing a different issue. Please, see #124.

**Comment by woj-tek** [comment]
@iSoron in my mind it's "at least x times" and if I set notification for 5 days during weekday than I expect it... to show it 5 times during weekday. This probably is different from "do something twice a week".
In my case, if I'm overly actively it results in lack of notifications if in the last 5 days (including weekend) I already completed something (and if I'm doing it daily and set goal for 5 days then there are no notifications).

**Comment by woj-tek** [comment]
@iSoron pondering this a bit more - I think there should be an option (either global or per habit) whether notifications should happen at designated day always (despite "completeness" of task) or depend on whether task is considered completed in the given period -- that should solve the issue IMHO

**Comment by iSoron** [comment]
I have created feature request #686 based on this issue. If enough users are interested, we can add it to the app. This issue itself is not a bug, since the app is working as expected.
