### ISSUE TITLE
Calendar view

### ISSUE THREAD

**Issue by qazip** [iSoron/uhabits#264]
Hello,

It would be cool if one could have a calendar view, after clicking on a habit. Perhaps give us an option to choose the "Default view", one of them being the calendar. I know there's "History"  but it's not sufficiently big/visible.

The app "7weeks" has that and I find it much better for habit building.

**Comment by iSoron** [comment]
Hi @qazip, thank you for the suggestion, but I have no current plans of changing the interface significantly. Remember that you can also use a large home-screen widget, if you would like.
