### ISSUE TITLE
New Feature: Isolate Bad Habits and Build Reward Notifications

### ISSUE THREAD

**Issue by hesseljo** [iSoron/uhabits#266]
1) Identify the behavior the user wants to change. This means asking for a defined “Behavior Name” and adding it to the bad habits log.

2) Isolate Behavior Cues. After a user defines a “Behavior Name”, activate it, and log the location and time of when the user creates an event tied to the name. This means, the user needs to use the app whenever they are triggered by the behavior. Reminders can be sent periodically to ask if the bad habit occurred, this might require a service for checking and requesting.

3) Provide a list of suggested rewards based on global search patterns. For every bad habit, (e.g. not brushing teeth before bedtime) suggest applicable rewards if they log they actually completed the behavior. And also allow the user to input rewards. When they log the good habit, the reward notice is triggered.

4) Allow the user to set rewards to periodicity. (e.g. immediate, after input # of habits, etc.)

5) Record the cues that the user defines as reaching a reward. After a certain # of cues, begin to set reminders for rewards vice reminders for habits. 

The basis of this feature request is to grow a habit into a reward over time based on user defined cues and behavior names.

**Comment by iSoron** [comment]
Hi @hesseljo, thank you for your suggestion. This, however, reads like a completely different app than what we have today, and I am not planning to radically change the app in the immediate future. You are welcome to build a prototype (or at least some mock screens) if you want to show me how these features could be seamlessly integrated to the current app. I would be glad to have a look, and reconsider.
