### ISSUE TITLE
Allow users to export data from the statistics screen

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#27]
Currently, to export data, the user must select the habit on the main screen by long-pressing, then open the overflow menu. This selection operation is somewhat unusual and can be hard to find. It would be better if there was an entry on the statistics screen menu, where it can be easily seen.

**Comment by JanetQC** [comment]
So should the download-icon appear when I'm in the statistic of a habit (and then only download that specific habit) or should the functionality be available when I tap on settings? There we could also offer to download one or more habits.

**Comment by iSoron** [comment]
What I had in mind was this: when you open the statistics page for a habit, there is currently only one menu button, for editing the habit. We could add an "export" button which would generate the CSV just for that habit. This button could be hidden inside the overflow menu.

**Comment by JanetQC** [comment]
Okay I see. I'd like to do this task if it's still free.

**Comment by JanetQC** [comment]
Also I noticed you were using the wrong archive-icon, the current one you're using is actually for download,  I would like to use that one for the download action.

**Comment by iSoron** [comment]
>  I'd like to do this task if it's still free.

Thanks, I'm assigning it to you.

>  Also I noticed you were using the wrong archive-icon

Are you talking about [this icon](https://github.com/iSoron/uhabits/blob/dev/app/src/main/res/drawable-hdpi/ic_action_archive_light.png)? What do you think it should look like?

**Comment by JanetQC** [comment]
I'd suggest sth like [this](https://cdn3.iconfinder.com/data/icons/education-37/49/78-512.png), [this](http://icons.iconarchive.com/icons/icons8/ios7/512/Very-Basic-Archive-Filled-icon.png) or [this](http://www.freeiconspng.com/free-images/archive-icon-15949).

**Comment by JanetQC** [comment]
Nevermind, I just researched and found out that the archive- and download-icon look pretty similar.
