### ISSUE TITLE
Streak includes streaks of incomplete days

### ISSUE THREAD

**Issue by GoodEveningMiss** [iSoron/uhabits#271]
I have a habit I rarely complete. For a couple months until I finally did it once, it showed me a streak of 78 days! Except that was 78 days for which I didn't complete the task. Before I checked today off, it also showed me a streak of 18 or so days for which I again did not complete the task.

In trying to replicate this issue, I now notice it is sometimes showing a duplicate streak for 1 day. As in April 5 is listed twice for a streak of 1 day. I don't have enough (less than 4) legitimate streaks to fill the bottom section.

**Comment by iSoron** [comment]
Hi @GoodEveningMiss, could you please include a screenshot of the problem? Also, what version of the app are you using, and what version of Android?

**Comment by GoodEveningMiss** [comment]
I'm on version 1.5.6 right now, most recent version of Android. Working on that screenshot
