### ISSUE TITLE
sync/export to a google spreadsheet

### ISSUE THREAD

**Issue by ojanvafai** [iSoron/uhabits#279]
I'd love the ability to sync to a Google Spreadsheet so I can use the Spreadsheet tools to data mine and as an added peace of mind regarding backups (e.g. if I lose my phone).

I can export to CSV, and import into Spreadsheets of course, but I'd rather have something automatic. This would also serve as a way of having continuous backups instead of backups when I remember to do them.

Lastly, this could serve as a way of addressing #104 and #17.

Would be happy to help hacking on this if this is an idea you're into.

**Comment by iSoron** [comment]
Thank you for the suggestion, @ojanvafai. For automatic backups, I think integration with Google Drive / Dropbox would make more sense for most users. Even if we could export data to Google Sheets, there's no way we could reliably import it back. I also don't see how Google Sheets could work as a sync solution.

So, leaving backup and sync aside, why would you need to repeatedly export your data to Google Sheets? What kind of data analysis are you performing? Perhaps we could implement that data analysis directly into the app itself.

**Comment by artemohanjanyan** [comment]
@iSoron actually there is an API for accessing contents of Google spreadsheet.

**Comment by morrel** [comment]
A simpler solution would be to automatically export CSVs to Drive with some schedule. Once the CSV is in Drive, there are many good options for syncing that CSV with Google spreadsheets.

As for why someone would do this. It's the only way to combine personal data from different sources. Right now I have to keep a habit of exporting CSVs from various apps once a week.. 

Here's how to load a CSV into a spreadsheet using the built-in script in any Google Sheet. You can also schedule it to run it daily or even hourly.

```javascript
  var file = DriveApp.getFileById(fileId)
  var csvData = Utilities.parseCsv(file.getBlob().getDataAsString(), ';');
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetName);
  sheet.getRange(1, 1, csvData.length, csvData[0].length).setValues(csvData);
```

**Comment by iSoron** [comment]
Thank you for this script, @morrel. Given that it's easy to import from Google Drive to Google Sheets, I think this is the best way to accomplish what @ojanvafai suggested.

I'm closing this since we already have an issue for automatic scheduled backups (#178).
