### ISSUE TITLE
Widget showing archived habits

### ISSUE THREAD

**Issue by mr-flibble** [iSoron/uhabits#283]
Hello, when I create a widget, a list will appear containing all created habits, even those archived.
I think that archived habits should be hidden from this list. It will certainly improve usability.
Thanks.

**Comment by iSoron** [comment]
Thank you for the suggestion, @mr-flibble. I agree that we should not list archived habits in that list.

**Comment by samagra14** [comment]
@iSoron I would love to work on this issue. I am new to open source and therefore targeting small tasks. Can I pick up the issue and work on it? Or is the issue already being handled? If I can work on this issue then I will need your help to get started.

**Comment by iSoron** [comment]
Hi @samagra14, please feel free to work on it.
