### ISSUE TITLE
Import data from Way of Life

### ISSUE THREAD

**Issue by VijayS1** [iSoron/uhabits#284]
How can I import data from Way of Life App? 
PFA sample csv. rename extension if needed
[Way of Life (6-4-17).txt](https://github.com/iSoron/uhabits/files/969584/Way.of.Life.6-4-17.txt)

**Comment by iSoron** [comment]
Hi @VijayS1, currently it is not possible to import data from this app, but this would be an interesting feature to have. Thank you for providing a sample CSV.

**Comment by VijayS1** [comment]
Thanks for taking a look at it. Anyway for me to convert this into existing formats that loop does accept?

**Comment by olejorgenb** [comment]
If would be very useful if the app supported import from an generic csv format. That way users could quite easily write their own import scripts. It's a lot easier to generate what basically amounts to a list of dates (in the simplest case) than to convert to the more complex formats already supported for import.

I have some logs (datestamped lines basically) that would be cool to visualize with the app. With a generic import format conversion would be very easy.

**Comment by olejorgenb** [comment]
I see now that the Habitbull csv format is very simple.

    HabitName,HabitDescription,HabitCategory,CalendarDate,Value,CommentText
    Workout,Did you workout today?,,2017-09-23,1
    Workout,Did you workout today?,,2017-09-28,1
    ...

Ref: #44, https://github.com/iSoron/uhabits/blob/dev/uhabits-core/src/main/java/org/isoron/uhabits/core/io/HabitBullCSVImporter.java

NB: haven't tested if values containing space need to be quoted or not
