### ISSUE TITLE
Habit ring display for habits with less than daily frequency is a little unmotivating

### ISSUE THREAD

**Issue by saschwanbeck** [iSoron/uhabits#288]
If I define a habit to occur just one day a week (like taking out the garbage) -- I'd like for the ring to show 'complete' if I do that habit/chore just one time. At present any amount less than seven times will result in what looks like incomplete progress to me. That's kind of unmotivating.

I suggest that the ring be completed in as many portions as required to equal the number of days the habit was scheduled for reminder and completed.

**Comment by iSoron** [comment]
Thank you for the suggestion, @saschwanbeck. The ring displays the current habit score, regardless of the type of habit. In order to keep the interface consistent, I am not planning to modify this behavior.

**Comment by saschwanbeck** [comment]
So that means you also wouldn't want any help to modify that display?

Sarah
