### ISSUE TITLE
“Habit strength” label is cropped from chart in habit details

### ISSUE THREAD

**Issue by ThibG** [iSoron/uhabits#29]
Hi,
Since it has been translated, the “Habit strength” label on the chart in a habit's details is slightly larger and is cropped… see attached screenshot.

![_20160313_194711](https://cloud.githubusercontent.com/assets/384364/13730647/ef9341a2-e954-11e5-9c31-bdfa531473cb.JPG)

**Comment by iSoron** [comment]
Thank you for letting me know. This is how it looks now:

![layout-2016-03-14-133139](https://cloud.githubusercontent.com/assets/4699657/13754964/5cc6290c-e9ef-11e5-9d2e-51b4534167e1.png)
