### ISSUE TITLE
RTL-layout breaks habit table

### ISSUE THREAD

**Issue by fin0** [iSoron/uhabits#290]
Hey, just a minor problem with the app:

If I select "Force RTL-layout" (right to left) in my Cyanogenmod (don't know of this is available with a standard android) because I'm using my phone with the left hand, the habits and the marks are mirrored, but not the top row with the dates. It is not a problem that makes the app unusable, but a fix would be nice to have.
Should I provide a screenshot?

Solution: Mirror all rows or none, but not sth in between ;)

Greetings!

**Comment by iSoron** [comment]
Thank you for reporting this bug, @fin0. I have just released a new beta version of the app (v1.7.1) which fixed this, in addition to some other issues. Could you please confirm that it works for you?

**Comment by fin0** [comment]
Thanks for the fast answer. Sure I will try, how can I get the apk? Will it be at f-droid tomorrow?

**Comment by iSoron** [comment]
Yes, it should appear on F-Droid tomorrow.

**Comment by fin0** [comment]
Fixed :)
