### ISSUE TITLE
Conditional habits

### ISSUE THREAD

**Issue by ferittuncer** [iSoron/uhabits#293]
It would be very handy if we could have conditional habits.

For example: Habit C is done if and only if A and B done.

Real life example: Consider someone who has nutrition habits for breakfast, lunch and dinner. S/he also wants to check if s/he got done all three habits in a particular day.

Assume that breakfast is A, lunch is B, dinner is C and overall habit is D. D should be automatically evaluated with this expression `D = A & B & C`

Hope that I expressed it clearly.

**Comment by artem-p** [comment]
Maybe nested habits will be better approach? In example above, we can consider D as main habit and A, B, C as "subhabit". And display them in the same way, as subcategories instead of flat structure.

**Comment by ferittuncer** [comment]
What if:

Let A, B, C, habits and D, E conditional habits;
D = A & B
E = A | C

How to nest them now? Habit A belongs both D and E.

**Comment by iSoron** [comment]
I am already planning to add some support to this through the use of tags (see #31). It will not be as advanced as you suggest, but I believe it will cover the most common use cases, while not complicating the UI too much. For example, if a person has the habits breakfast, lunch and dinner, she could select these three habits and add a tag "nutrition", which would allow them to see statistics for these three habits combined. There could be a graph showing how many ticks (for these three habits) she has for each day, for example.

**Comment by c33s** [comment]
conditional habbits would be awesome but tagged or grouped will also help

**Comment by ferittuncer** [comment]
I thought you gave up on this. Sorry @iSoron

**Comment by iSoron** [comment]
Moving this discussion to #495
