### ISSUE TITLE
Habit-Question input text field: Allow arbitrary many lines without hiding buttons

### ISSUE THREAD

**Issue by fin0** [iSoron/uhabits#294]
Something I realized just now: I have the habit to use the "Did you do... today?" text field as general purpose for saving information about how to actually do the habit (example: sport routine with maybe 20 different exercises). At the moment,  when entering too many lines, the "Save" button is not clickable anymore. Would be a nice-to-have for me and maybe others to actually enter more information there.
(Maybe renaming the field would also be a good idea?)

**Comment by iSoron** [comment]
Thank you for reporting this, @fin0. This is a known issue which has already been fixed in the `dev` branch. The fix should be available to all users in version 1.8.0.
