### ISSUE TITLE
Allow user to duplicate / clone habits

### ISSUE THREAD

**Issue by firelite** [iSoron/uhabits#295]
Hi, 

Really loving the app so far! The first thing I felt was missing is the ability to duplicate an existing habit when creating a new habit.  Many of my habits had similar wording so I had to retype each one by memory.  It would be nice to have a quick way to copy existing habits and then modify as needed. 

Thanks!  Wonder if this is something others could use too.

**Comment by iSoron** [comment]
Thank you for the suggestion, @firelite. I agree that this would be an interesting feature.

**Comment by towcar** [comment]
I will take a stride at adding this, shouldn't be too hard. Do we want the edit screen to come up automatically after duplicating?

**Comment by mr-flibble** [comment]
> I will take a stride at adding this, shouldn't be too hard. Do we want the edit screen to come up automatically after duplicating?

I think so, otherwise user will be forced to think which habit is original and which is a copy :)
