### ISSUE TITLE
Applications still crashes from time to time

### ISSUE THREAD

**Issue by qv1x0te** [iSoron/uhabits#296]
Hello,

The version 1.7.1 of the application still crashes from time to time despite having been supposedly fixed.

For further information see https://github.com/iSoron/uhabits/issues/287 and the new bug report attached.

[Bug Report - Loop Habit Tracker.txt](https://github.com/iSoron/uhabits/files/1026464/Bug.Report.-.Loop.Habit.Tracker.txt)

**Comment by iSoron** [comment]
Thank you for letting me know. I will reopen the original issue.
