### ISSUE TITLE
No way to figure out strongest month

### ISSUE THREAD

**Issue by bdambdam** [iSoron/uhabits#298]
Hi again, is there a way to find the strongest week/month? The way uhabits measures doesn't show strongest period. See below, I exercised totally on every day basis in December but had a week month of January. The tool still shows that January was by far my best month. Is there a way to see real values?

![image](https://cloud.githubusercontent.com/assets/20455542/26584457/1a82cbb6-4549-11e7-9ee0-4793c476c695.png)

**Comment by mr-flibble** [comment]
Same "problem" habit strength graph have pretty big ... momentum. 

Maybe solution is add context menu with switch to "Habit frequency view" ?

**Comment by bdambdam** [comment]
In 1.7.4 there was a mention about "Show Strongest Month" or similar, is it that feature? Or what has changed around this topic in 1.7.4?

**Comment by bdambdam** [comment]
Someone asked me again how often I meditated last months. I had to count the entries for every month. I cannot answer 67% and 80% since these values don't absolutely indicate the truth. Is there a way to see actual number of days/month in uhabits?

**Comment by iSoron** [comment]
Thank you for bringing this issue to my attention, @bdambdam. I am planning to add a chart showing the number of repetitions per week, month or year. See #403.
