### ISSUE TITLE
Implement Spaced Repetition intervals

### ISSUE THREAD

**Issue by gstruwig** [iSoron/uhabits#299]
It would be nice to have an option to select spaced repetition reminder interval. Habits can then be used to set study times using the method described [here.](https://www.quora.com/Whats-the-best-spaced-repetition-schedule)  I have tried to implement this with my limited android experience and have managed to compile your code, but the complexity is beyond me and I don't know where to start.

**Comment by iSoron** [comment]
Hi @gstruwig, could you come up with a specific example of a habit where spaced repetition would be useful, and how would it work inside the app? I am very familiar with spaced repetition learning, and it's indeed a great learning tool, but I don't think it would work well for this app.

**Comment by gstruwig** [comment]
Hi @iSoron. I am thinking of a Student that would benefit from set reminder times, based on spaced repetition intervals, to revise previous class work. uHabits will successfully do this but is limited by the fact that reminder intervals are all of a fixed duration.

**Comment by hiqua** [comment]
You're much better off using a dedicated tool for this, like Anki (https://github.com/ankidroid/Anki-Android). There are already plenty of such tools, IMHO there's no need for uhabits to start competing with them.

**Comment by iSoron** [comment]
I agree that this feature is beyond the scope of the app.
