### ISSUE TITLE
Notifications button LATER

### ISSUE THREAD

**Issue by sebastian05067** [iSoron/uhabits#303]
Hi,

When i press the botton LATER the notification goes and return again. Anyone else has this problem?

**Comment by iSoron** [comment]
Hi @sebastian05067, just to double check, what version of the app are you using?

**Comment by sebastian05067** [comment]
Version 1.7.2

Look at video from the bug

https://mega.nz/#!4d0TRSpD!uBIRRVcOhsBqf_2UCl26AtzuEqS1DC-soxh_9nbRhRc

**Comment by abhijith-gururaj** [comment]
Hi even I am facing the same issue. When I press later, does it mean the app will remind us  like 1 hour later or it simply means that I am not going to do this habit today.

**Comment by iSoron** [comment]
Thank you for letting me know. This should be fixed in version 1.7.5, which was released today.

@abhijith-gururaj Pressing later should show you the reminder again a few minutes later. You can change the precise length of "later" in the settings.

**Comment by woj-tek** [comment]
Isn't this the same as #256, which leads to  #160, which in turn is planned for a next major release?
> "Soron modified the milestone: Loop 1.7.0, Loop 1.8.0 on 9 Apr"
