### ISSUE TITLE
Add an activity to export database backup

### ISSUE THREAD

**Issue by matclab** [iSoron/uhabits#304]
It would be nice to allow external tools such as tasker or automate to be able to call an activity for  doing a backup of the database in a given directory.

I've lost two months of data by having forgotten to do a backup before my phone died...

**Comment by iSoron** [comment]
Thank you for the suggestion. I don't think we need Tasker for this. I am fine with the app exporting backups regularly to the SD card by itself. Since we already have #178, I am closing this.
