### ISSUE TITLE
Indonesian translation completed

### ISSUE THREAD

**Issue by azzamsa** [iSoron/uhabits#306]
It seem Indonesian translation already completed, I am just adding 20% of the portion. some of them already translated. and this translation need to be voted.

some of translation from the past is already fine. and I left the app name in englis "Loop Habit Tracker".

Really glad to contribute to this great project.
thanks for everyting iSoron, I am really apreciate your effort.

thanks.

**Comment by iSoron** [comment]
Thank you for your help, @azzamsa!
