### ISSUE TITLE
Associate habits with tags

### ISSUE THREAD

**Issue by AnderRasoVazquez** [iSoron/uhabits#31]
Tags are great for organizing items, would be great to assign a tag to habits instead of colors. For example, all "health" related habits would have the same color that we assigned to health tag.

**Comment by iSoron** [comment]
I think tags are an interesting feature. It would allow us to implement, for example, combined statistics for groups of habits. But I would like to keep the colors independent from them, since you can usually assign multiple tags to one item.

**Comment by aleksejrs** [comment]
The worst thing about tags for me in some tagging UIs (apparently Tickmate and OI Shopping List suffer from this) is the inability to find items not tagged with any tag of a group or at all when I want to add them.  Please make it possible to find at least completely untagged items.

Assigning multiple tags would not worsen this if Loop keeps the habit order consistent in all lists.

**Comment by aleksejrs** [comment]
> to find items not tagged with any tag of a group or at all when I want to add them.

Tickmate actually has a nice tagging UI, which includes both a list of tags to choose from for a track, and a list of tracks to choose from for a tag.

**Comment by mr-flibble** [comment]
Hello, I think the app would benefit from the ability to add tags to the items and be able to view only the selected tags or all (like in habit rpg android app https://play.google.com/store/apps/details?id=com.habitrpg.android.habitica&hl=cs ) 

Example: If I have a habit "go sleep early", so I never actually see a screen congratulating me that I have fulfilled everything.
While 90% of my day I do not care about this task.
