### ISSUE TITLE
Unable to build project after first project import

### ISSUE THREAD

**Issue by rsri** [iSoron/uhabits#318]
I am using Android Studio 3.0 Canary 9. I forked the project and imported it on the studio for the first time. But the project refresh isn't succeeding. I keep getting this error.

Error:Could not get unknown property 'LOOP_STORE_FILE' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.

Am I missing something here? Thanks.

**Comment by rsri** [comment]
Nevermind. I had to comment out the signingConfig under release in gradle for it to work.

**Comment by iSoron** [comment]
This should be fixed now. Thank you for letting me know.
