### ISSUE TITLE
Trend lines / reminders

### ISSUE THREAD

**Issue by Mathnerd314** [iSoron/uhabits#321]
I want an app to remind me to do laundry. The math is pretty simple - I have X clean shirts, I wear roughly 1 a day, and so it should just remind me X days in the future (or a little before then). Ideally, I would just enter in 2 data points, e.g. 26 clean shirts today, 25 clean shirts tomorrow, and then the app would figure out the rest (just fit a [straight-line trend](https://www.fourmilab.ch/hackdiet/e4/signalnoise.html#Fa83), and reset everything when I wash some clothes)

But Loop only supports on-or-off habits, not declining/increasing totals, and certainly not trend lines, so I was wondering if this was something you'd like to see?

**Comment by iSoron** [comment]
Thank you for the suggestion, @Mathnerd314. This sounds interesting, but I feel it's currently beyond the scope of the app. We can discuss this again after #42 is implemented.
