### ISSUE TITLE
Feature request: categories/grouping

### ISSUE THREAD

**Issue by o-antsiferov** [iSoron/uhabits#325]
It would be great to have categories or some kind of grouping for similar habits.

**Comment by konahart** [comment]
I would love this. It would be nice to 
a) view a particular set of habits at a time (e.g., everything related to Health) and 
b) be able to have a meta-habit representing the group that gets checked if anything in the group is checked (e.g., if "run" and "bike" are in the group "cardio," "cardio" would get checked if I check either one)

**Comment by woj-tek** [comment]
Definitely +1. I have a set of "morning routine" habits and this would greatly help have it in check.

**Comment by SomMeri** [comment]
It would be great if I could merge multiple habits into single history/strength widget.

**Comment by iSoron** [comment]
Duplicate of #495. Keeping that one since it has more comments.
