### ISSUE TITLE
Wrong display of checkmarks for once per week 

### ISSUE THREAD

**Issue by stanley85** [iSoron/uhabits#330]
When once per week option is selected and monday is checked the remaining week is checked correct. Checking Tuesday the next week leaves monday unchecked. Please change from checking the following 6 days to a true once in a week manner. Thanks in advance. This App is great and helps a lot to maintain new habbits.

**Comment by iSoron** [comment]
Hi @stanley85, this has already been fixed, and should be available to everyone in the next release of the app. See #124 for more details.

**Comment by stanley85** [comment]
Perfect, looking forward to the next release! Thank you for this!
