### ISSUE TITLE
App crashes when checking tasks

### ISSUE THREAD

**Issue by Foggalong** [iSoron/uhabits#34]
The app crashes for me when trying to check a task as done. There's no option to send an error report so I'm not sure what else I can add, but I'm running on CM13 on the nexus 10.

**Comment by iSoron** [comment]
Thank you for reporting it here. The option to send the report automatically only shows up if you install the app through Google Play Store. If you have installed it through F-Droid, here is how you can get useful information to help us track the bug. In short, you need to install an app like CatLog, set the filter to "org.isoron.uhabits", and then save or email yourself the log. It is a bit of trouble, but it would help a lot.

If you just want to get rid of the bug, you could try to change the frequency of the habit to something else, and then change it back to the original. For example, change it to 1 repetition in 7 days, and then change it back.

**Comment by Foggalong** [comment]
Is this what you need?
![Uploading tmp_13663-Screenshot_20160315-135959-1416058881.png…]()

**Comment by Foggalong** [comment]
As a note, changing the frequency doesn't seem to surpress the bug either.

**Comment by iSoron** [comment]
Thank you, this is exactly the information that I needed. I will try to reproduce this bug on my phone soon. As a workaround, I guess you can you still toggle the checkmarks using the reminders, or using the history editor.

Just a few questions to make this bug easier to reproduce. 1) Does this happen with every habit and every checkmark, or only with a particular combination? 2) Has this happened since the first time you installed the app, or was it after you updated the app / deleted some habit / something else?

**Comment by Foggalong** [comment]
1. Happens with every habit and every check mark
2. I only installed the app today, and after a bit of testing happens with both v1.2 and v1.3
3. Marking a task as done via widget doesn't register it as done within the app

**Comment by iSoron** [comment]
Okay, I think I might have been able to reproduce the bug on my tablet. Just to confirm that this is indeed the same bug, could you please try to run the app when your tablet is in portrait mode, instead of landscape?

**Comment by Foggalong** [comment]
Can confirm it works in portrait mode, and as an added bonus the stuff toggled via widget also shows up in portrait mode.

**Comment by iSoron** [comment]
I have released version 1.3.1 just now, which contains a patch to fix this bug. It might take a couple of days for it to show up on F-Droid, and a couple of hours for it to show up on Google Play Store. Thank you for the detailed report.

**Comment by Foggalong** [comment]
No problem, thanks for the fix! :D
