### ISSUE TITLE
Feature Request : Three-state toggle instead of two-state

### ISSUE THREAD

**Issue by ebfortin** [iSoron/uhabits#343]
I've added a simple funcitonality where each Checkmark is three-state instead of two. Meaning that we can explicitly specify that a day is unchecked. I think it make clear the days that we explicitly didn't do as we were supposed to, instead of always relying on implicity unchecked. It can also be a way to indicate that we reviewed one habit and determined that we didn't succeed that day, when reviewing in a long list of habit we follow. 

If someone is interested to look at it, I can push the branch.

**Comment by iSoron** [comment]
Hi @ebfortin, please feel free to submit a pull request. I am closing this issue as it is a duplicate of #96.
