### ISSUE TITLE
Export data doesn't work

### ISSUE THREAD

**Issue by cyb13** [iSoron/uhabits#344]
"export data as csv" and "export the database" are unable to work on my phone. I try to share the file someway like "save to google drive". There's no error message. But the file doesn't exist and can't be shared correctly.

I am running loop version 1.7.6 on Android 7.1.1 N6F27I on my Nexus 6.

**Comment by iSoron** [comment]
Hi @cyb13, could you generate a bug report from within the app (Settings / Generate Bug Report), so that we can have a better look?

**Comment by licaon-kter** [comment]
@cyb13: Using a file manager (eg. TotalCommander) helps?

**Comment by cyb13** [comment]
@iSoron 

[Bug Report - Loop Habit  @Tracker.zip](https://github.com/iSoron/uhabits/files/1386182/Bug.Report.-.Loop.Habit.Tracker.zip)

This problem disappeared in version 1.7.8. I am not sure if it is because of the update (1.7.6 -> 1.7.8).

**Comment by cyb13** [comment]
@licaon-kter : This problem disappeared recently, so I can't test this.
