### ISSUE TITLE
Disallow users to modify dates in the past

### ISSUE THREAD

**Issue by jsroyal** [iSoron/uhabits#350]
I just installed the app  and first of I want to thank you contribute an open source.
As I can see you can also modify yesterday habit so It won't be fair If we can restrict. Then It will generate true data.
It is just one thought if you like it then accept.

**Comment by iSoron** [comment]
Hi @jsroyal, if I understand correctly, you would like the app to forbid the user from making changes to dates in the past; is that correct? This feature is actually desirable in many situations. For example, many users only put checkmarks once every couple of days, or once every week. More fundamentally, though, if you decide to lie to the app, then there is really nothing that we, the developers, can do to stop you.
