### ISSUE TITLE
Widgets fail to render in some devices

### ISSUE THREAD

**Issue by ZalerC** [iSoron/uhabits#353]
ADW is download from f-droid, version is 1.3.6 standalone. OS is cm11, it is an old phone. The unhabits from f-droid or play, all show error. And cm11 default launcher sometimes is fine, sometimes is error too.
Another is backup always show false.

---------- BUG REPORT BEGINS ----------
App Version Name: 1.7.8
App Version Code: 35
OS Version: 2.6.32.9-AeroKernel (be546efa10)
OS API Level: 19
Device: mb526
Model (Product): MB526 (cm_mb52x)
Manufacturer: motorola
Other tags: test-keys
Screen Width: 480
Screen Height: 854
External storage state: mounted

---------- BUG REPORT ENDS ------------

**Comment by iSoron** [comment]
Thank you for this bug report, @ZalerC. Other users have reported that the widgets fail to render in their devices, showing only the message "error drawing widget", however I have not been able to reproduce this bug reliably on my own devices. If anyone has any further information about this bug, please let me know.

**Comment by iSoron** [comment]
It's not clear this is still a problem in Loop 1.8.8. If anyone is still having this issue, please let us know and I will reopen it.
