### ISSUE TITLE
Add "once a week" repeat

### ISSUE THREAD

**Issue by c33s** [iSoron/uhabits#356]
currently the calculation is every 7 days if i choose "every week". in the first place i missunderstood "every week" i assumed that there is a difference between custom (n times every x days) and "every week". it leads to the assumption that one is calculated day wise and the other week wise but both are calculated day wise.

if you have 2 fitness events a week, one on monday and one on wednesday, i want to visit one of them in a week an fullfill my sport habbit. this is currently not possible, if i visit sport on monday in the first week and on wednesday in the 2nd week it will break my streak line :(

so a "once a week" repeat would be nice, which always counts from monday to sunday (or sunday to monday)

**Comment by iSoron** [comment]
This has been fixed and will be available in the next version of the app. Please, see #124.
