### ISSUE TITLE
Score drops while keeping up a daily habit

### ISSUE THREAD

**Issue by schneiderlars** [iSoron/uhabits#359]
Hey habits team,

Ich wonder about the following situation: I use a daily habit which I checked successfully for the last couple of weeks. First the score was rising to about 90%, but now it seems to drop a couple of percent in a weekly interval.

I made some screenshots to demonstrate the behaviour. My expectation was, that the score climbs continously as you describe it in your FAQ. 

Great app and many thanks for developing it. Best wishes, 
Lars

![screenshot_20171119-091040](https://user-images.githubusercontent.com/6523066/32988702-9ea66400-cd09-11e7-8812-b9663794cb81.png)

![screenshot_20171119-091031](https://user-images.githubusercontent.com/6523066/32988703-a57e783a-cd09-11e7-9f20-bb0d8dd7533c.png)

**Comment by iSoron** [comment]
Thank you for reporting this issue, @schneiderlars. This should no longer be an issue in the upcoming version 1.8.0 of the app. In the meanwhile, the option "repair database" in the settings screen should be able to fix this.

If anyone continues to experience this even after upgrading to Loop 1.8.0, please let me know.
