### ISSUE TITLE
Import data from Rewire App

### ISSUE THREAD

**Issue by tobimensch** [iSoron/uhabits#36]
The Rewire App in the official Android store is very much alike this app. I've used it for a couple of weeks and now that I discovered this free alternative I'd like to have a way of importing Rewire's data, so that I don't have to start at 0 with my streaks.

**Comment by iSoron** [comment]
Thank you for the suggestion. Does Rewire allow you to export your data? If so, that would make things easier. In any case, if the habit is only a couple of weeks old, you can also use history editor (on the habit statistics page, click the 'edit' button below the calendar) to copy the checkmarks manually.

**Comment by tobimensch** [comment]
You should really look into this app, it has some nice features which would be worth copying. For example the widgets are very well done. The idea to write motivations behind the habits I also find good (but not that high priority). Changing between overview and statistics by swiping I also like. The app does allow one to backup, but I don't know where that is stored, export to CVS is only a premium feature unfortunately.

Thanks for making me aware of the history editor, that should help me solve the problem.

**Comment by Yura95st** [comment]
Import from Rewire App is not working at the moment.
The reason is that Rewire App's data file is now encrypted and password protected.

**Comment by iSoron** [comment]
Yes, they have started to password-protect their backup files. The FAQ has been updated accordingly. I have no interest in breaking their encryption. If anyone has a sample of the CSV files generated by the paid version, I would be glad to have a look at it.

**Comment by erikstokes** [comment]
@iSoron I would love to be able to switch away from rewire without losing all my data.  [Here](https://gist.github.com/erikstokes/7bfb72eeb1a9c7aad0c52f52ca632b89) is a sample of the csv output from the paid version
