### ISSUE TITLE
Start score at 100 instead of 0

### ISSUE THREAD

**Issue by vyu1** [iSoron/uhabits#362]
What do you guys think about having an option/setting for habits score to start at 100% and go down when the user doesn't complete that habit, instead of the way it is now (habits start at 0% and go up to 100%)? I'd like to work on this if other people think this would be a cool idea.

**Comment by Anshoe** [comment]
I think this is an idea that will appeal to many

**Comment by dennmuel** [comment]
Probably depends on the way you see it. Please correct me, if I'm wrong, but for _building_ habits I feel it's better to go from 0 to 100. For _maintaining_ habits it's probably better to measure the decrease from 100 towards 0. Does the way it's implemented now not model this once you get a habit to 100%?

**Comment by vyu1** [comment]
It certainly does. I was just thinking that people feel worse seeing their score drop, and it can incentivize some people to better maintain their habits.

**Comment by iSoron** [comment]
I am fine with this. If you would like to start coding this feature, please go ahead @vyu1 and let me know if you have any questions.

**Comment by lacivert** [comment]
Why not start with 50%? I suggest this because there are both possibilities: to complete more (positive score) or not complete (negative score) 

I thibk it is better to be more neutral than positive or negative on start

**Comment by vyu1** [comment]
I liked the idea of starting at 100% because I think that it might give the user more incentive to not lose their perfect score. Starting at 50% doesn't provide this specific incentive since you still have to climb to 100%

**Comment by AeliusSaionji** [comment]
"that it might give the user more incentive to not lose their perfect score."

The problem with this approach is that once you do lose your perfect score, the effect backfires and becomes demotivating. Someone who wants to maintain their 100% will be particularly demotivated by their "perfect record" being permanently "tainted".

Any implementation of this would need to give the user opportunities to negate past mistakes.

Personally, I don't think that tracking deviation from perfection would be beneficial- it might sound motivating to you, but I think your premise only considers half the equation.

**Comment by vyu1** [comment]
I think you made a very fair argument, though I still personally don't
think the incentive system created by starting scores at 100 differs too
much from the incentive system we have now. I've already started working on
this, but I'll wait to finish it until I hear if anyone else would like
this to be done.

**Comment by matkoniecz** [comment]
How hard it would be to get back to 100% after failing it once or twice? Because if it is unreasonably hard it would be quite demotivating.

**Comment by AeliusSaionji** [comment]
It occurs to me that this already exists in some form with the "streak" functionality. Is there some way to tweak the way streaks are presented such that it will fill this role for those who want it?

**Comment by boughtonp** [comment]
I'm in favour of a per-habit option to start at 100%/50%/0%, with a global setting for deciding the default for new habits.

I don't see streaks as a solution to this - and until #124 and #406 are done, streaks don't work anyway.

**Comment by Erudition** [comment]
The percentage is supposed to be habit strength. When you first start a habit, you haven't been doing it, so it's strength, by definition, is zero.

Either way, IMO, if you're looking for incentive to build your habit, the strength meter is not the best place to look.

**Comment by iSoron** [comment]
I am no longer convinced this feature is necessary, and there has been very little user demand for it, so I am closing this issue.
