### ISSUE TITLE
No scroll bar in main menu

### ISSUE THREAD

**Issue by seiichinagai** [iSoron/uhabits#365]
When the user adds more habits than fit on the screen, a thin scroll bar ought to appear when scrolling through habits.

**Comment by iSoron** [comment]
You're right. Good catch. Pull requests for this are very welcome.

**Comment by seiichinagai** [comment]
Great! I'll get started on this one.

**Comment by recheej** [comment]
This is an interesting one. HabitsCardListView is a custom recycler view which is injected. You apparently can only set scrollbars in xml??? @iSoron

**Comment by shkp** [comment]
Hey! I am an Android newbie but I'd like to try to implement this and contribute. Thanks.

**Comment by iSoron** [comment]
As usual in Android, this seems to be way more tricky to fix than expected. There is [some discussion about it on StackOverflow](https://stackoverflow.com/questions/27056379/is-there-any-way-to-enable-scrollbars-for-recyclerview-in-code), but I have not tried it. If anyone wants to give it a shot and submit a pull request, I'd appreciate it.

**Comment by iSoron** [comment]
Fixed in #459
