### ISSUE TITLE
Feature Request: Store user values along with dated checkmark

### ISSUE THREAD

**Issue by Bujiraso** [iSoron/uhabits#368]
Hi there,

First off: love the app. It's great.
Next, to business: I have a feature request that I'm curious to see how well it would fit in here.

I do lots of practice-based habits, for which the value of each day is slightly different depending on time commitment. A day where I have practised 60 minutes is a higher achievement than say 5m. For various other habits I keep a score out of 5 or 10 depending on its personal value to me.

As of now the app presents, in essence, a theoretical tuple of a Boolean check-mark status for a given date string. I would appreciate a feature where, upon checking that habit for a day, it would prompt me to enter a string (e.g. time commitment today in minutes) which it would store and then could output in the export CSV. In other words, modify the tuple to be optionally (Date, String) instead of (Date, Boolean). Simply storing a flat string of limited size would be great as I tend to only need a few characters (e.g. "105", "4/5"). This feature would be enabled while creating or editing a specific habit and it would not be set by default, leaving the default settings as they currently are. 

 In order to make the feature reasonable to implement, there is no need for the app to interact with these data. The app does not need to store units, limits, trends, or understand any calculations implied by the data. Therefore, for scoring these days, I think the first implementation should ignore the user value and merely continue the existing scoring. Parsing and manipulating a user string could get needlessly complex and is not the features' major value, which is merely to store and export a value paired to each check-mark for specific habits.

If the user data is strictly numerical, a "nice to have" sub-feature could be displaying the user lists as simple graphs could be implemented sometime down the road. This would show the user their progress in app, but this could be happily implemented later on.

**Comment by iSoron** [comment]
Hi @Bujiraso, I'm glad you like the app. Please have a look at #42. I am currently implementing full support for numerical habits, which will include statistics. For other kinds of notes, see #194 .
