### ISSUE TITLE
Add option to only count as streak checked days

### ISSUE THREAD

**Issue by AnderRasoVazquez** [iSoron/uhabits#37]
If we have a habit to be checked 1 time for X days, and we check that habit one time only, we will see on the streak graph that we will have an X days streak for that habit. I think it will be more accurate to count as streak only the checked days.

For example: we have a habit to be checked 1 time for 7 days. I check that habit one time. I would expect a 1 day streak not a 7 day streak.

What do you think?

**Comment by iSoron** [comment]
The idea for the current way of counting is that it is consistent across all habits. If you see the number "14", you know that you have been doing the habit perfectly for two weeks; if you see "365", you have been doing it for a year, and so on, no matter what is the frequency of the habit. By counting repetitions, the length of time becomes unclear for habits with complex schedule.

But I am well aware that not everyone likes it this way, and it would be quite easy to make this more flexible, so I guess we could add an option on the settings menu to decide this.

**Comment by AnderRasoVazquez** [comment]
That would be great.

**Comment by Weygert** [comment]
Most of my habits are on a weekly basis and considering that I am looking at the success of doing them on a much wider timeframe, imho the counting of days with its quite high numbers are a bit confusing. I.e. I also like the idea of having the choice how to count it for each habit separately.

**Comment by iSoron** [comment]
Since the release of the app, there has very little user demand for this feature. Implementing it would make the interface inconsistent and hard to explain (sometimes the number means something, and sometimes it means something else). It would also add complexity to the app, both for the users and developers. For these reasons, I no longer think we should implement it.
