### ISSUE TITLE
Show days that can be skipped in advance

### ISSUE THREAD

**Issue by jwleon** [iSoron/uhabits#372]
Hello!

I have a feature suggestion: For habits that are not all days of a week, it would be nice to see, if the next days are currently backed by the x of y "policy" and can be skipped without breaking the streak. This would save me headache of figuring it out for the next day (which is, in some cases, not too easy).

Thanks in advance for reading and maybe considering it and thanks for this great app! :-)

**Comment by vyu1** [comment]
I second this. I've also personally found this frustrating

**Comment by Anshoe** [comment]
That would be quite useful

**Comment by hiqua** [comment]
Would be nice to have.

Ideally we could scroll sideways to show more days, including days in the future, where the marks would also be filled.
