### ISSUE TITLE
Reminders delayed past midnight mark the wrong day

### ISSUE THREAD

**Issue by uli-on** [iSoron/uhabits#374]
If a reminder is delayed until a new day starts, that reminder marks the _new_ day instead of the day it has been triggered from.

Steps to reproduce:

1. Delay a habit's reminder as long as the following day has begun, e.g. 0.10 am. 
2. Now press "Mark" for that habit on its notification panel.
3. Open the app and look for that special habit. The checkmark has been put onto the _current_ day of week instead of the last day/yesterday.

**Comment by iSoron** [comment]
I believe this has already been fixed. If this is still an issue with the current version of the app, please let me know and I will reopen it.
