### ISSUE TITLE
Allow user to change transparency of widgets

### ISSUE THREAD

**Issue by AeliusSaionji** [iSoron/uhabits#376]
For my uses, I only need the ability to make the backdrop completely transparent. My launcher has the ability to apply a dimmer to widgets (and solid colors and other theming options), so I am able to make a consistent visual style by using widgets with full transparency.

Currently, Habits is the only app I use that doesn't conform perfectly ;)

**Comment by AeliusSaionji** [comment]
Well, yours and WhatsApp. You can see from my screenshot, this applies to all types of widgets.
![stitchcraft_20180201-123038-1517506243917](https://user-images.githubusercontent.com/4342746/35693381-0d504606-074c-11e8-8ec9-b2f537aa21bc.png)

**Comment by iSoron** [comment]
Thank you for the suggestion, @AeliusSaionji. This is, in fact, an important feature we are missing. Pull requests implementing this are very welcome.
