### ISSUE TITLE
add "mark today as done" section on summary page or directly in notification

### ISSUE THREAD

**Issue by matkoniecz** [iSoron/uhabits#377]
My usecase: 

- I receive notification
- I click on it what opens summary page
- Now I must to either select "back" button to check it on main screen (or select edit in calendar)

It would be nicer to mark it as done directly in notification or at least to have a button on top of summary page "I did it today".

**Comment by iSoron** [comment]
Thank you for the suggestion. It is already possible to mark a habit as completed directly from the notification. If you don't see the action buttons, it's probably because the notification is collapsed. You can expand it by touching the little arrow close to the notification title.

**Comment by matkoniecz** [comment]
It is not working on my phone (no arrows or other expand buttons whatsoever), I am going blame myself for buying Xiaomi Redmi 4 (and manufacturer of this phone)
