### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Robigus92** [iSoron/uhabits#379]
After a double rotation of the SettingsActivity there are in heap memory 2 instances more of:

class org.isoron.uhabits.activities.settings.SettingsActivity @ 0x12cbe000
class org.isoron.uhabits.activities.settings.SettingsFragment @ 0x12d83800

It should not be like this because the rotations return to the same GUI state and the memory should stay in the same state as well. It could be a symptom of a bad management of the onCreate-onDestroy lifecycle. 

I have encountered this problem on an Android emulator running 7.1.1 os version.

**Comment by recheej** [comment]
I took a look into this. I believe it's related to this:

https://medium.com/@amitshekhar/android-memory-leaks-inputmethodmanager-solved-a6f2fe1d1348

**Comment by iSoron** [comment]
The settings activity is very seldom used. Unless this can be fixed very easily, I don't think it's worth the effort. If anyone finds such a memory leak in the other activities, please let us know.
