### ISSUE TITLE
Encrypt backups

### ISSUE THREAD

**Issue by trymeouteh** [iSoron/uhabits#382]
A good security feature would be able to encrypt the backup files when they are created and set a password on them through the app. This way your backup files cannot be read without the password to the file. This is good for privacy when using cloud storage services to store your backups.

Some people may be tracking habits they don't want others to know about and this will keep your habit tracking more private and secure.

**Comment by aschrijver** [comment]
I think not only backups, but all data created by this app should be encrypted, given that habits are very personal data wherever they are stored :)

**Comment by iSoron** [comment]
Thank you for the suggestion. I think this would be a good feature. If anyone is interested in implementing this and have any questions, please let me know.

@aschrijver We currently do not upload anywhere. When device sync is implemented, it will also be encrypted. Regarding the local database in your phone, unless you root your device, only Loop Habit Tracker has access to it, so we should be safe.

**Comment by iSoron** [comment]
I no longer think this feature is worth implementing. File encryption is complicated, and it clearly falls the main scope of the app. Library support for encrypted archives also seems very weak; Apache Commons Compress, for example, doesn't support writing encrypted files. Finally, if we add any encrypted backup file formats, we will need to support them for a very long time.

Based on this, if you don't trust your cloud provider, I suggest downloading a specialized file encryption app, or switching to a solution such as Syncthing.
