### ISSUE TITLE
API / Expose intent

### ISSUE THREAD

**Issue by jugaltheshah** [iSoron/uhabits#384]
I'm not familiar enough with Android but would it be possible to create a programmatic interface to this app? I imagine using it with physical buttons like the Flic button. Basically like you'd click a button and have it record that you took an action. E.g. If I click a button on my desk, I studied. A button in the bathroom, took my meds, etc.

Google Cloud Framework might work to listen for network input. Or it could just be exposing an intent that sets an action as taken, this could be used in conjunction with an automaton app like Tasker for the network piece.

I'd be happy to submit a PR if the idea is acceptable and I had a general approach that should be taken. Haven't done a lot of Android work but I can figure out the details.

**Comment by mr-flibble** [comment]
Helo, is worth mentioning that habit app already have Tasker support -
https://github.com/iSoron/uhabits/wiki/Integration-with-Tasker

**Comment by jugaltheshah** [comment]
Ahhh sorry, wish I'd seen this earlier. Thanks, this should suffice quite
nicely!

**Comment by Erudition** [comment]
How does one *read* the habit data in Tasker though?

**Comment by iSoron** [comment]
@Erudition This is not currently possible. Please, feel free to open an issue about this. This has not been implemented yet because we need to figure out a way to do it securely. I don't want every app on your phone to have access to your private habit data.

**Comment by Erudition** [comment]
Ah, I didn't realize that was an issue. For now I'll just have to have Tasker read the notifications to see the reminders.

I'll open the issue.
