### ISSUE TITLE
Consider using Github Projects for larger feature requests

### ISSUE THREAD

**Issue by aschrijver** [iSoron/uhabits#388]
Great project this! There is a lot of willingness to contribute and a great issue backlog with many valuable feature requests. However, some features are quite large, like the one for the website landing page https://github.com/iSoron/uhabits/issues/267

You could consider creating Projects for these kinds of features and divide tasks among contributors.

**Comment by iSoron** [comment]
Thank you for the suggestion. I have experimented a little bit with GitHub projects, but they don't seem very helpful. I think lists and checkmarks, however, work quite well, as you can see in this issue: #487.
