### ISSUE TITLE
Add privacy statement

### ISSUE THREAD

**Issue by neopostmodern** [iSoron/uhabits#389]
I couldn't find any information concerning if and what data leaves my device? I've seen #104 which sounds as if at least not all of the data is uploaded. But still there could be analytics kind of things...

Might help / attract new users (like me)!

**Comment by neopostmodern** [comment]
Also on website / [FAQ](http://loophabits.org/faq.html)...

**Comment by iSoron** [comment]
Thank you for the suggestion, @neopostmodern. Yes, we need a privacy statement. To make it short, the app itself does not upload your data anywhere. In fact, it does not even have permission to access the Internet. It does not include any tracking code, such as Google Analytics, or any advertisement libraries. When it gets implemented, cloud sync will be an opt-in feature.

Note: If you have activated "backup & reset" in your phone settings (Settings / Backup & Reset / Back up my data), then you should be aware that Android itself will periodically save a copy of your phone's data in Google's servers. This backup contains a lot of sensitive information, including your WiFi passwords, messages and call history. It may also include data from Loop Habit Tracker and from other apps you use. If you are concerned about your privacy, I suggest disabling this feature.

**Comment by neopostmodern** [comment]
That's great to hear :) And I've of course disabled the automatic backups...

So please, be proud of this and make it visible!

**Comment by iSoron** [comment]
Our privacy policy is now available at http://loophabits.org/privacy. There is a link to this page on our Google Play page. I am also planning to include a link to this page inside the app itself.
