### ISSUE TITLE
When sort by color: Enable sort manually inside each color block

### ISSUE THREAD

**Issue by jt007** [iSoron/uhabits#391]
When we want to sort the habits by color, today the habits are sorted alphabetically inside each color block. 

When the habits are displayed alphabetically inside each color block, it create a bit mess when it's many habits. It's then easy to lose the overview of what's most important inside each color block.

This could be solved in two ways when we sort by color:

1) Enable manual sort of habits in "sort by color" as it works in "sort manually". The app remember this setting til next time.
or
2) The app follow the manually order inside each color block by the order we have sorted in "sort manually". 

Is it possible to fix this?

**Comment by iSoron** [comment]
This is a good suggestion, however I think it would be somewhat hard (from a technical perspective) to implement. I'm not planning to work on this myself, but if anyone would like to try, I would be glad to help.

**Comment by iSoron** [comment]
Given how hard this is to implement and the low user demand for this feature, I unfortunately no longer think we should implement it.
