### ISSUE TITLE
Home screen name changes

### ISSUE THREAD

**Issue by kpeckett** [iSoron/uhabits#392]
Sometimes, my home screen shows the app name as "Habits", and other times as "Loop Habit Tracker". I am using the Microsoft Launcher (formerly Arrow Launcher), if that has significance.

**Comment by iSoron** [comment]
Thank you for letting me know, @kpeckett. The correct name for the launcher icon is "Habits". If your launcher is showing anything else, that is probably a bug in your launcher. I'm closing this, as there is not much we can do about it.
