### ISSUE TITLE
Add app shortcuts

### ISSUE THREAD

**Issue by kilotaras** [iSoron/uhabits#393]
Android 7.1 introduced app shortcuts, which can be used from long press or even searched from some launchers (e.g Nova + Sesame). They can also be added to home screen and, unlike widgets, be put in folder there.

https://developer.android.com/guide/topics/ui/shortcuts.html

Please consider adding shortcuts for habits.

**Comment by bykursat** [comment]
I agree
Please consider adding shortcuts for habits

**Comment by iSoron** [comment]
I am aware of this new Android feature, but I'm not sure how could Loop benefit from it. What kind of app shortcuts do you think it would be interesting?

**Comment by bykursat** [comment]
Example:
Ebook file shortcuts
Pdf file shortcuts
Excel file shortcuts
Image file shortcuts
App shortcuts
Internet link shortcuts
