### ISSUE TITLE
Please add TIME BLOCKS or CATEGORIES 

### ISSUE THREAD

**Issue by jt007** [iSoron/uhabits#394]
This can give us an option to:
   1)	Only view habits in a time block (e.g. Morning habits, Afternoon habits or Evening habits etc)
        or
   2)	Only view habits in one category (e.g. health, fitness or productivity etc)

We may choose individually if we want to use the feature for time blocks or for categories. It would be nice if it’s possible to tag several categories to a habit (e.g. morning habits and afternoon habits). 
If possible to tag several categories, it will also open the opportunity to even cover both option 1 and 2 in the same feature (e.g. tag both “morning habits” and “health”). We may create the categories ourselves based on preference.

This feature will make this great app AWESOME!!! 😊  Please Add!

**Comment by jt007** [comment]
How it can work: 
When we edit a habit, we may have the option to open a list of categories and tag one or more of those to the habit. The menu on the home page may have the category option under the “sort” option.

Really hope this feature could be implemented very soon!

**Comment by LMurphy001** [comment]
Here is an alternative for implementing 2. "Only view habits in one category "

I suspect most of the code to implement this is already in the project's code.

In the menu that says "Hide archived," "Hide completed," and "Sort," add a toggle menu item "Show Color/Show All Colors"

That will bring up a way to select a color of the tasks to be shown.  There is already a filtering function for Hiding things (e.g. completed.) That filtering code could be modified to check each task's color against the color the user has chosen to be shown.

It would be up to the user to use the colors to for his/her categories (or blocks, etc).

If I had the Android app development environment set up on my computer I would try to figure this out myself and add it to the project for review.

Thank you!
Linda

**Comment by iSoron** [comment]
Moving this discussion to #495
