### ISSUE TITLE
add an option to put Databases at Internal user storage？

### ISSUE THREAD

**Issue by fairyex** [iSoron/uhabits#401]
So Tasker can read these data without ROOT via sqlite query.

**Comment by licaon-kter** [comment]
To do what with it?

**Comment by iSoron** [comment]
Hi @fairyex, thank you for the suggestion. Unfortunately, this is not something I am planning to add to the app, for several reasons:

1. Loop was designed with the assumption that it has exclusive access to the database. If other apps start accessing and modifying the underlying SQLite database directly, without notifying Loop, this would most certainly lead to all sorts of strange bugs, crashes and data corruption.

2. The database schema of Loop is not "published". It may change completely from version to version, and in the future we may move away from SQLite completely. Your Tasker script would break constantly, after each update.

3. In the current version of the app, the database still contains a cached version of a lot of information, such as scores and streaks. However, to reduce the database size, simplify the code and improve performance, this will change in the next version of the app. The information you would be able to read using SQLite, starting from Loop 1.8, would be only the list of checkmarks and some basic information about the habits. The other tables are gone.

**Comment by qazip** [comment]
This would be a good thing for me. If this happened, I could sync the DB with syncthing to my computer. I could then create a CLI to add/remove/edit/whatever habits on my computer and have it shown on my phone or vice-versa.

Is this something you still don't want, @iSoron ?
