### ISSUE TITLE
Option to hide habits not possible to do today

### ISSUE THREAD

**Issue by jt007** [iSoron/uhabits#402]
I like the feature Hide habits completed today. 
Some habits are unfortunately not possible to complete today. It would be nice to be able to hide this/those habits just for today. So we can view only those habits that are relevant today.

One possible way to solve this: 
When long pressing the habit, we today get the options (in the menu up right corner):  archive or delete. Please add "hide today" on this list.

**Comment by jt007** [comment]
Could it be possible to add this nice feature?

**Comment by iSoron** [comment]
Duplicate of #272
