### ISSUE TITLE
Change "best streaks" to "longest streaks"

### ISSUE THREAD

**Issue by KeronCyst** [iSoron/uhabits#404]
Some of the habits I'm measuring are negative ones that I do not want to encourage, so it'd be more objective to just say "longest" instead of "best."

**Comment by KeronCyst** [comment]
Yeah, but say I did the negative habit early in the morning. Then I may forget in the evening whether I did it or not (did I do it today/should I check it?). I have poor memory and would rather have it inversely tracking, so that way I can immediately mark that I did the bad habit right on the spot than having to review whether I lasted the whole day into the evening, if that makes sense.

**Comment by iSoron** [comment]
Thank you for the suggestion, @KeronCyst, however the app was specifically designed with positive habits in mind, so I am not planning to change this. As for forgetting the checkmark, please have a look at #125.

**Comment by KeronCyst** [comment]
iSoron, I still want to suggest this. To be blunt, I was using Loop to help myself get over my ex by tracking my frequency of not-checking-up-on-her. But having to be REMINDED of the daily victory of not checking up on her still kept her in my mind daily, so I eventually created an inverse habit that only tracked my frequency of when I DID check on her, which helped a lot more. I believe this was very positively helpful, but to call the latter "best" doesn't line up. Does this make sense? It'd make an already-great app even more versatile, I believe.
