### ISSUE TITLE
The task's name(including Chinese) doesn't refresh instantly when it is changed.

### ISSUE THREAD

**Issue by LosikiS** [iSoron/uhabits#407]
When I change a habit's name(including Chinese character) in the main interface , The main interface won't refresh immediately.
If the habit's name is in English only,This problem won't appear.

To reproduce this problem:
1.Add a habit named 测试(means test)
2.Press the habit,and then change it's name to 测试1
3.The name of this habit is still 测试 , and it will be refresh when I press it again or open the night mode or close this app and start it again.
![1](https://user-images.githubusercontent.com/33153388/39580666-379776e2-4f1c-11e8-8b71-bc1531d3f8e3.jpg)
![2](https://user-images.githubusercontent.com/33153388/39580667-3848b0a6-4f1c-11e8-9461-de7a594a85f3.jpg)
![3](https://user-images.githubusercontent.com/33153388/39580670-3897e0ea-4f1c-11e8-8f56-718e058453aa.jpg)
![4](https://user-images.githubusercontent.com/33153388/39580671-38e8db44-4f1c-11e8-87fa-037d20e94be3.jpg)

My app version 1.7.8
(Please forgive my poor English.)

**Comment by iSoron** [comment]
Thank you for the bug report, @LosikiS. I have tried this in the development version of the app, and this issue seems to have been fixed. If the problem is still there when version 1.8.0 becomes available, please let me know.
