### ISSUE TITLE
Import data from Tickmate

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#41]
[Tickmate](https://play.google.com/store/apps/details?id=de.smasi.tickmate) is another popular open-source habit tracking app. It would be nice if Loop could import data from it.

**Comment by DocSniper** [comment]
Tickmate data that has "Multiple entries per day" is not imported as "measurable", only as "Yes or No". 
So the values are unfortunately lost.
Would be great if the values would also be taken over during import, thanks.
