### ISSUE TITLE
Add FAB to add habits

### ISSUE THREAD

**Issue by lokesh-krishna** [iSoron/uhabits#410]
Could you please consider moving the add button from the top of the app to a FAB? This will really improve reachability.

**Comment by woj-tek** [comment]
I would argue that you more often look at (current) habits statistics/entries than adding new habits, and the FAB button covers quite a lot of space…

**Comment by lokesh-krishna** [comment]
Ah yes, forgot that it would hide elements of the UI. Should I close this or can this serve as the place to discuss any alternative to the present position of the add button?

**Comment by iSoron** [comment]
Thank you for the suggestion, @lokesh-krishna. The reason why we don't have a FAB is precisely not to cover important information. Furthermore, as woj-tek mentioned, the primary action in the app is not adding new habits, but adding checkmarks.

If anyone has other ideas about the FAB, please feel free to open a new issue.
