### ISSUE TITLE
Allow user to switch back to standard habit frequencies after selecting custom

### ISSUE THREAD

**Issue by aschrijver** [iSoron/uhabits#412]
When creating a new habit and selecting Custom, there is no way to switch back to Daily or Weekly without discarding the habit altogether, and you lose the text you just typed (not a very big deal, but allowing a switch to fixed periods would still be an improvement).

**Comment by iSoron** [comment]
We should certainly improve the user interface with respect to this.

However, just to let you know, you can still get the same behavior as "daily" or "weekly" habits by entering "1 in 1 days" or "1 in 7 days".

**Comment by iSoron** [comment]
Fixed in the `dev` branch
