### ISSUE TITLE
Export to WebDAV and/or FTP

### ISSUE THREAD

**Issue by CryptoStar2000** [iSoron/uhabits#414]
An export function to WebDAV and/or FTP would be awesome.  At best as encrypted zip/7z :-). This would be good to sync different devices.

**Comment by iSoron** [comment]
Thank you for the suggestion, @CryptoStar2000. Backup encryption is already covered by #382.

As for exporting to WebDAV or FTP, when you click the export button, the app already shares the backup file with other apps on your phone, and relies on them for the actual upload. For example, if you have Google Drive installed, the app can give the file to the Google Drive app, which will then upload it to your account. I'm guessing some FTP clients may also allow this. This is a much better solution, in my opinion, than supporting every single protocol or web service directly. For this reason, I'm not planning to implement this feature.
