### ISSUE TITLE
Full overview of habits

### ISSUE THREAD

**Issue by dorofino** [iSoron/uhabits#416]
I love this app.

It will be nice to have a screen where you can see a full overview of how are you doing across all habits.

**Comment by daledesilva** [comment]
Hi dorofino,
On my phone I’ve set up a number of widgets to do just that. I’d suggest that in the meantime, however, I’m keen to get involved as a developer in the future to make this work a bit smoother - cause I find this method of seeing the colours fill up the screen to be very self rewarding.

![d828f94d-ae3a-4d2a-8cf0-73e5e6df0284](https://user-images.githubusercontent.com/18710973/41037050-69fe3d90-69d5-11e8-9858-838bb59c21fe.jpeg)

**Comment by iSoron** [comment]
Duplicate of #51
