### ISSUE TITLE
Bad habit tracking

### ISSUE THREAD

**Issue by Garf1eldGit** [iSoron/uhabits#418]
Hi!
Is it planned to add tracking bad habits?
For example I want to set myself a limit. Do not do something more than once a week.
If I do this more than 1 time a week then a bad habit increases

**Comment by adrienbeau** [comment]
This is the first question in the FAQ: http://loophabits.org/faq.html#q1

Here is the answer:

> Instead of tracking bad habits, it is better to rephrase your habit in a positive way. In this way, every time you open the app to put a checkmark, you are rewarding yourself for some good behavior, instead of getting punished. For example, instead of having the bad habit "Did you smoke today?" you could have the good habit "Did you have a smoke-free day today?". Another example, instead of "Did you eat junk food today?" you could have "Did you eat healthy today?".

**Comment by iSoron** [comment]
@Garf1eldGit There are no plans to add this feature. I considered it before, but could not come up with a way to add negative habits, while keeping the interface simple and intuitive.
