### ISSUE TITLE
Feature request: Kids version

### ISSUE THREAD

**Issue by amitguptagwl** [iSoron/uhabits#420]
No doubt it's my favorite. I love it's simple interface. What I'm looking for Goal meter like illustration so I can motivate my kid to make good habits. And showing a map / path to achieve the reward / trophy. Best part can be if I can upload the image of reward.

Though I'm not aware with Android development, I would be happy to contribute.

**Comment by iSoron** [comment]
Thank you for the suggestion, @amitguptagwl. This sounds interesting, but, given the amount of changes we would need to introduce on the user interface to make this work, I think it would be better to do this as a separate project. If anyone wants to fork our code and start a kid's version, please go ahead and keep us updated.
