### ISSUE TITLE
Circumstantial habit support

### ISSUE THREAD

**Issue by AnderRasoVazquez** [iSoron/uhabits#43]
There are some examples of **habits that only occur on certain conditions**:
- Taking the stairs instead of the lift
- Arrive early to a meeting...etc

You probably cannot predict how many meetings will you have every week, or how many chances to take the stairs will you have in a week (or even in a day). What would be great is the possibility to check a habit when it occurs. [**Habitica**](https://habitica.com/#/tasks) **makes it easy to track this kind of habits, here's an example**:

![1 _099](https://cloud.githubusercontent.com/assets/3936719/13899780/bd42ab7e-edf6-11e5-8e75-f774be00ff0d.png)

"Puntaje" in this context means "habit strength". In this example the habit label could be "take the stairs", we would tap `+` if we decide to take the stairs or `-` if we take the lift. Each tap on `+` or `-` modifies habit strength.

Do you think this is a good way to support this kind of habits? I've been using it for a few months and I like it a lot.

**Comment by iSoron** [comment]
I am wondering what does the score represent in this case. Is it the average number of repetitions in the last month, or something like that?

**Comment by AnderRasoVazquez** [comment]
No, it's what they call "task value". From the [Habitica wiki](http://habitica.wikia.com/wiki/Task_Value): 

>Task Value refers to the value of a Habit, Daily, or To-Do. It is represented by the task's color, where yellow is neutral, orange and red are negative, and green and blue are positive. 

| Color	| Value	|Consecutive Clicks|
|--------|---------|--------|
|Bright Blue	|Greater than 10	|12 positive|
|Blue Grey	|Between 5 and 10	|6 positive|
|Green	|Between 1 and 5	|1 positive|
|Yellow	|Between -1 and 1|	0 clicks|
|Orange	|Between -10 and -1	|1 negative|
|Red	|Between -20 and -10	|9 negative|
|Dark Red|	Less than -20	|16 negative|

**This is the formula they use**:
> + Performing a good Habit (+) or checking off a Daily will increase that task's value.
+ The task value changes by approximately 0.9747^x, where x is the current task value. This means the greater the magnitude of the task value, the less it will change. For more precise information on how task value changes are calculated, see the [**talk page**](http://habitica.wikia.com/wiki/Talk:Task_Value#Task_value_calculations).
+ Performing a bad Habit (-), missing a Daily, or procrastinating on a To-Do will decrease that task's value.  Task value changes by the same amount as for a good Habit/Daily, but in the opposite (negative) direction.

**Comment by iSoron** [comment]
Thank you for the explanation. So, if I understand correctly, these habits would be completely independent of time? If I take the elevator today, but then I am not faced with the choice of taking either elevator or stairs for a month, then the score of the habit would keep the same until then?

I am not sure I would even consider these as "habits", but I will leave the issue open in any case.

**Comment by AnderRasoVazquez** [comment]
Yes, they are independent of time. The habit score only will change tapping `+` or `-`.

Well, I would call a good habit arriving early to meetings, brushing your teeth after every meal, choosing the healthy alternative when you go to a restaurant... Those things that require some willpower when they happen. =)

**Comment by flyingdan** [comment]
What might help with this is having the option to select the days on which I expect to perform the habit rather than just frequency. 

Say a user goes to the gym three times per week on Monday, Wednesday and Friday. At the moment the user can only select 1 every 2 days which works fine for the first week but Habit then expects the check mark on Sunday Tuesday and Thursday.

This may be a different feature request though.

**Comment by iSoron** [comment]
@flyingdan If you set the frequency to "3 times in 7 days" then perform your habit consistently on Mondays, Wednesdays and Fridays, the app will automatically add checkmarks on all the other days of the week.

**Comment by flyingdan** [comment]
@iSoron Thanks for the reply, that works perfectly. Great app, keep up the great work!

**Comment by Anshoe** [comment]
@iSoron 
Replying to :
"Thank you for the explanation. So, if I understand correctly, these habits would be completely independent of time? If I take the elevator today, but then I am not faced with the choice of taking either elevator or stairs for a month, then the score of the habit would keep the same until then?

I am not sure I would even consider these as "habits", but I will leave the issue open in any case."

In Habitica, if you take the stairs you click on the plus. If you take the elevator, you click on a minus. So you still monitor the habit accurately every time there is an opportunity. The only thing is that it is not time bound.

Also there are many habits that are not time bound but instead respond to a certain event. This could be a valuble feature

**Comment by iSoron** [comment]
I am closing this issue, since I no longer think this kind of habit is within the scope of the app. There has also not been much user demand for this feature.
