### ISSUE TITLE
Translation incomplete

### ISSUE THREAD

**Issue by Kasurus** [iSoron/uhabits#430]
The "Customize notifications" option in the settings is not translated (screenshot). On the translationsite (http://translate.loophabits.org/) it says German 100%. So i assume it is a bug?

Habits Version: 1.7.9 (from F-Droid)
Device: OnePlus 5T (Android 8.1.0)

![screenshot_20180815-165654](https://user-images.githubusercontent.com/38571075/44156184-9e2847d0-a0af-11e8-90b9-f26d4bbec513.jpg)

**Comment by Kasurus** [comment]
ok, i realized that you handel the strings.xml differently. so no need for a pull request there... :smile:

**Comment by iSoron** [comment]
Yes, this is a bug. Thank you for reporting. I will close this issue after the string becomes available in our translation platform (http://translate.loophabits.org).

**Comment by iSoron** [comment]
This is now fixed.
