### ISSUE TITLE
[not a bug, SOLVED]Streak problem with first day of the week

### ISSUE THREAD

**Issue by mr-flibble** [iSoron/uhabits#433]
Hello, I find out strange behavior with one of my habits and I'm think that app is not supposed work like that.
I'm using English (United Kingdom) locale because I want to week start at monday. So week should be monday to sunday
I have habit with setting "5 times in 7 days"

My streak is strangely interrupted when I missed friday and saturday

![image](https://user-images.githubusercontent.com/5197625/44310352-a1569380-a3d4-11e8-851d-5319e4af8939.png)
![image](https://user-images.githubusercontent.com/5197625/44310357-baf7db00-a3d4-11e8-955b-e531801f4df3.png)

Andorid 7.0
Habbits 1.7.9

Is this normal? What the point of first day of week then? Thanks

**Comment by jphofmann** [comment]
This is working as intended. 

As if Friday the 17th your habit was completed 4 of the 7 day period so it counted as miss. The streaks do not consider the days of the week, or the start day of the week. The streak is a rolling period of days, in this case the last 7.

The "start day" of the week is just to make the display look more natural to the user.

**Comment by mr-flibble** [comment]
Thank you for nice explanation, now I get it - streak is floating.
So my workaround is change repeat from 5 times in 7 days to 15 times in 21 days - that solve problem with short term misses.
