### ISSUE TITLE
Loop "94%-99%-94%..." 

### ISSUE THREAD

**Issue by skvord89** [iSoron/uhabits#434]
Hello there!
I met a strange situation growing habit-score to nearly 100%.
At first, score was growing as I expected - slower and slower while growing.
But at some point I entered the loop. Every day habit-score is 94% before check and 99% after check. Next day it's 94% again.
It seems to be something wrong, doesn't it? How it's possible grow from 94% to 99% in one day in that algorithm? And drop from 99% to 94% again in one day.

Thanks for assistance!

Tracker version 1.7.9.

![1](https://user-images.githubusercontent.com/33492463/44327707-145d1a00-a468-11e8-9fff-398306e302c0.PNG)
![2](https://user-images.githubusercontent.com/33492463/44327708-145d1a00-a468-11e8-8766-d89e80184a31.PNG)

**Comment by luther9** [comment]
You should see that same pattern no matter what, unless yesterday's score is less than 20%, in which case the penalty might not be visible due to rounding off. The score you see before adding the checkmark is what your score *would* be if you did not add the checkmark for the day.

**Comment by iSoron** [comment]
Merging this issue with #463
