### ISSUE TITLE
Import data from HabitBull

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#44]
[HabitBull](https://play.google.com/store/apps/details?id=com.oristats.habitbull) is one of the most popular habit apps on Android and iOS. It does allow to export habits into a .csv file. Would be great, if Loop could import them.

**Comment by iSoron** [comment]
I was planning to implement this feature for Loop 1.4.0, but, after having a look, it seems that they only allow exporting any kind of data if you pay for the app. If someone is kind enough to provide me with some samples of CSV files generated by HabitBull, I might implement this feature. Otherwise, there is nothing I can do.

**Comment by sojusnik** [comment]
And there it comes...

[HabitBull CSV Data File Export.csv.zip](https://github.com/iSoron/uhabits/files/184964/HabitBull.CSV.Data.File.Export.csv.zip)

**Comment by iSoron** [comment]
That's great, thanks. Could you please create a habit that has a comma anywhere on the name/description and export the file again? I want to see how do they deal with that. For example, name: "reduce sleep, and wake up early".

**Comment by sojusnik** [comment]
Second try: [HabitBull CSV Data File Export.csv.zip](https://github.com/iSoron/uhabits/files/185606/HabitBull.CSV.Data.File.Export.csv.zip)

**Comment by iSoron** [comment]
Nice, thanks. The feature is already implemented, and should be available in Loop 1.4.

**Comment by omol1991** [comment]
Hello from the future. So I am new, premium member of habitbull. I need some vsialization of select habits from a .csv file. I am on an Ipad which habitbull doesn't support, and it doesn't even support mport of csv files afaik.

**Comment by omol1991** [comment]
Is there any way I can do this fsirly fast?
