### ISSUE TITLE
Export or Import Incomplete

### ISSUE THREAD

**Issue by daledesilva** [iSoron/uhabits#448]
Upon creating a full backup to Google Drive. I then uploaded into a new install and not all habits imported and no history data imported.

I've attached the db file.
[Loop Habits Backup 2017-12-26 030952.zip](https://github.com/iSoron/uhabits/files/2669963/Loop.Habits.Backup.2017-12-26.030952.zip)

**Additional Info:**
- Same phone
- Wiped phone inbetween (so can't re export to test)
- Last habit that seems to have come through is "Read" - so the error is probably somewhere near there.
- Other habit categories that should have come through are "Grab", "Falter", "Illustrate", "Write", "Cook" (I might be missing some)
- Didn't know how to properly view the db file so haven't been able to assess whether it's an import or export issue, but a find in sublime text on the habit titles seems to indicate they're not there and it was export.

**Comment by iSoron** [comment]
Thank you for the bug report, Dale. Just to double-check, are you sure this is the latest backup file exported by the app? The filename suggests that this file was created back in December, 2017. For your information, our backup files are [SQLite databases](https://en.wikipedia.org/wiki/SQLite). You can open them with [this viewer](https://sqlitebrowser.org/), for example.
