### ISSUE TITLE
third type of check mark which doesn't break nor add to streak

### ISSUE THREAD

**Issue by SVNKoch** [iSoron/uhabits#449]
I have some task which can only be done at home. I'm often not at home due to vacation for example. 
That's why I suggest a third type of check mark (maybe a circle?) which doesn't count as done, however also doesn't break your streak.
I find it frustrating breaking my streak every so often even though it's not my fault.

**Comment by iSoron** [comment]
Thank you for the suggestion. This is a duplicate of #88.
