### ISSUE TITLE
Scheduled Habits

### ISSUE THREAD

**Issue by YohananDiamond** [iSoron/uhabits#454]
Hello, I would like to suggest **Scheduled Habits** on Loop Habit Tracker. Here's how they could work:
1. The user can schedule days where the habit is obligatory.
2. These habits will have the checkboxes highlighted on the scheduled days.
2.1. If the day passes and the user didn't check off, the habits can have an "X" on the checkbox.

Also, some extra features related to this:
1. Option to filter only habits scheduled for that day.
2. Home Screen Widget with the habits for that day (and only one checkbox for each habit).

**Comment by zuron7** [comment]
+1 Habit notifications if stickied should automatically disappear at the end of the day or should have an option to mark not done.

**Comment by eSkry** [comment]
+1 Good idea!
