### ISSUE TITLE
Got an archived reminder after importing from full export.

### ISSUE THREAD

**Issue by blunket** [iSoron/uhabits#455]
on my old phone I had a habit (I'll call it "A") that I had a reminder on for 12pm every day. then I archived it and replaced it with a new one "B" that had a reminder at 11pm every day.

fast forward about 6 months, I get a new phone, do a full export from my old phone, transfer it to my new phone and import. then (same day as the import) at 11pm (the time for habit B's reminder), on my new phone I got habit A's reminder. My old phone properly got habit B's reminder at 11pm.

I assume something went wrong when exporting or importing.

**Comment by iSoron** [comment]
Thank you for the bug report. This has already been fixed in the development version of the app.
