### ISSUE TITLE
Provide an option for a repeating habit to be completed some number of times in a calendar week (or a calendar month)

### ISSUE THREAD

**Issue by openjck** [iSoron/uhabits#456]
Loop allows users to create habits that need to be completed some number of times over some number of days. For example, someone who wants to exercise three times per week might create an *Exercise* habit which needs to be completed 3 times in 7 days.

The problem with this approach is that it doesn't allow for much flexibility. Imagine that person exercises on Monday, Wednesday, and Thursday one week. The next week, they exercise on Monday, Wednesday, and Saturday.

They exercised three times per week for two weeks in a row, but Loop would penalize them because the Saturday exercise was more than 7 days after the Thursday exercise.

One possible remedy is to have a *x number of times per calendar week* option. Other apps, like HabitHub, have this feature.

**Comment by Anshoe** [comment]
Yesss. I desperately want this feature. We already have it for two times a week but would like it for other options as well

**Comment by JackElsey** [comment]
If you read the reviews on the Google Play store, it seems like this is one of two main issues people have with the app (the other being the lack of an automatic data backup).

Would this take that much work to implement? I'm willing to offer a financial reward to anyone who submits a successful pull request with this feature.

**Comment by JackElsey** [comment]
If I were to hire a freelancer to implement this feature, what qualifications should I make sure they have?

**Comment by iSoron** [comment]
> The problem with this approach is that it doesn't allow for much flexibility. Imagine that person exercises on Monday, Wednesday, and Thursday one week. The next week, they exercise on Monday, Wednesday, and Saturday.

This issue has already been fixed in the development version of the app. The app no longer requires that you perform the habit exactly the same day every week. See screenshot below. Note that this update is not yet available on Google Play. To receive it as soon as it is ready for testing, please make sure that you are enrolled in our [testing program](https://play.google.com/apps/testing/org.isoron.uhabits).

![screenshot_20190302-181605](https://user-images.githubusercontent.com/4699657/53689268-b616cb00-3d17-11e9-8874-58cfbc739808.png)

**Comment by iSoron** [comment]
> Would this take that much work to implement? I'm willing to offer a financial reward to anyone who submits a successful pull request with this feature. If I were to hire a freelancer to implement this feature, what qualifications should I make sure they have?

Thank you for your interest in sponsoring the development of the app. This particular issue is already fixed, but, more in general, I will give full consideration to any pull requests submitted to the project, whether the author has been paid to write it or not. Even if the changes are ultimately not accepted into the official project, note that you could still hire someone to create a personalized version of the app, just for yourself. Our software license allows that. The only major drawback, in that case, is that you would stop receiving our official updates. As for who to hire, I am not currently available, but perhaps [one of our previous contributors](https://github.com/iSoron/uhabits/graphs/contributors) is. Other than that, any competent Android developer should be able to implement changes, although it may take them a while to understand our codebase. 

You may also be interested in reading [Chapter 5 of the book **Producing Open Source Software**](https://producingoss.com/en/contracting.html), by Karl Fogel, which talks about hiring contractors to contribute to open source projects.

**Comment by JackElsey** [comment]
Hi Alinson, thanks for letting me know. I'm glad to see this feature is making its way into the app!

**Comment by openjck** [comment]
> This issue has already been fixed in the development version of the app.

That's great! Is there an estimate for when that improvement will be released? I don't think I see it in the latest version of the app.

**Comment by iSoron** [comment]
The app now allows much more flexible weekly schedules, so I am closing this issue.
