### ISSUE TITLE
Global reminder

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#46]
Besides habit specific reminders, a global one, to tick off habits at a user specified time, would greatly improve the chance of using Loop on a regular basis.

**Comment by sciamano** [comment]
may be you will also find interesting my ideas on integration with opentasks,
see https://github.com/dmfs/opentasks/issues/269

**Comment by sojusnik** [comment]
@that0n3guy Thanks, I've already created a habit to remind me of my habits.

**Comment by iSoron** [comment]
Since this can already be accomplished in many ways, I am closing this issue.
