### ISSUE TITLE
Can't save habit if description is too long

### ISSUE THREAD

**Issue by Sirove** [iSoron/uhabits#462]
Hope the screenshot makes the issue clear:

![screenshot](https://user-images.githubusercontent.com/24733228/51436709-737ebf00-1c92-11e9-80cd-aae7f1ea832e.png)

**Comment by iSoron** [comment]
Thank you for the bug report, @Sirove. In fact, this should not happen.

**Comment by iSoron** [comment]
Fixed in #472.
