### ISSUE TITLE
feat: Add way to enter numbers in a fast way 

### ISSUE THREAD

**Issue by chennemann** [iSoron/uhabits#469]
If you want to track numbers which are quite high it's actually pretty hard. You have to scroll the spinner a lot until you reach the desired number. 

I would propose a customized keyboard that is carefully purposed for entering numbers. That means it contains only numbers and the decimal separator. This keyboard can then be used to enter a number quickly and without thinking too much. 

I think it would be even easier (thinking wise) to enter the number with a specialised keyboard instead of the spinner that is used now. 

To clarify: I don't think it would be good to use an EditText with the input type number and then rely on the system keyboard to only show numbers. That is because those are not specific to our use-case and can even be used to potentially enter wrong characters. With a specialized keyboard we could minimize nearly all problems regarding user input while providing a better Usability.

**Comment by pasbc** [comment]
Do you think you could clarify? I'm not sure which input you are referring to and what type of number you want to track.

**Comment by chennemann** [comment]
first of all I'm using the experimental tracking of numeric habits. I track my weight with it so I have to input numbers >60 which is quite hard with the current input wheel. 

![](https://i.imgur.com/PVvtIMT.jpg)

To make it easier I would propose to have the ability to enter the number manually. to simplify this we could use the text input type number which instructs the keyboard to show the numbers in a more convenient way. see the following screenshot: 

![](https://i.imgur.com/qeJ3k8f.jpg)

The problem with this approach is that it is easily possible to enter invalid numbers so we need additional logic to cope with that. and that is where my custom keyboard idea comes in. with that approach you would limit the ways of entering an invalid input to the absolut minimum while giving the best user experience. 

could I clarify what I meant?

**Comment by iSoron** [comment]
@chennemann Thank you for the screenshots. On stock Android, as soon as the number dialog pops up, the number field should become automatically selected and a numerical keyboard should automatically appear. See screenshot below. If you want to type a new (large) number, you can easily do so by using the keyboard. Typing a new number will automatically replace the old one, since the field is already selected. If you just want to increment or decrement the number, that's also possible by scrolling. I am not sure why is your phone showing the full keyboard, instead of the numerical one. If you are using the latest development version, this should be considered a bug.

![screenshot_20190302-183522](https://user-images.githubusercontent.com/4699657/53689396-8fa65f00-3d1a-11e9-9781-70a54d60252c.png)

**Comment by chennemann** [comment]
I see. I just double checked and it worked. thanks for the hint. my keyboard did not show the number keyboard because the field was not selected. 

so the bug would be that the correct field is not selected when opening the numeric input. (if that is a bug)

we should probably open a new issue and cross reference this one here to make it more clear.

**Comment by iSoron** [comment]
@chennemann The field should get automatically selected when the dialog appears. The numerical keyboard should also automatically appear. If any of these two things is not happening, that's a bug. Please feel free to open an issue about this. Pull requests are also very welcome. If you want to submit a pull request about this, there is no need to open an issue first. You can just link to this thread.

**Comment by minttea** [comment]
@chennemann hey, could you share where you got the code for the experimental feature? From #42, I see it should be in a branch called `feature/numerical-habits`, but that branch is not available on the repo right now.

cc also @iSoron - would you be willing to push that branch to GH again please? :)

**Comment by yonootz321** [comment]
Is this tracking for numeric habits released in the play store? My version doesn't seem to have it

**Comment by iSoron** [comment]
@yonootz321 Yes, that feature is still work in progress.

@minttea That branch has been merged into the `dev` branch, but the feature is disabled.

**Comment by chennemann** [comment]
This issue should be closed since it was basically just missing knowledge that you could enter larger numbers via the keyboard. 
Maybe it would be good to add a hint to the dialog (something like "tap the number to enter manually") to improve the feature discoverability

**Comment by iSoron** [comment]
This should be fixed in 6d4cac4. To clarify, below is what the experience is supposed to look like.

<img src="https://user-images.githubusercontent.com/4699657/92191760-2ed57680-ee2a-11ea-8c32-9c62aa7ba2c3.gif" width=300 />
