### ISSUE TITLE
Description of a habit

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#47]
It would be very handy to have a way to add a small description of a habit, when adding it. F.i. the habit "meditation" could have the description "15 mins after getting up", to specify it more and keep the habit name as short as possible.

**Comment by AnderRasoVazquez** [comment]
Something like what [Rewire](https://play.google.com/store/apps/details?id=com.rstudioz.habits) does:
![photo_2016-03-20_16-34-03](https://cloud.githubusercontent.com/assets/3936719/13905215/a40ea504-eeb9-11e5-825f-e5e5e59ed74d.jpg)

**Comment by iSoron** [comment]
This is what the "question" field is supposed to be about. If the title of you habit is "Meditation", a question could be "Did you meditate for 15 minutes after getting up this morning?". Please, see the [FAQ](https://github.com/iSoron/uhabits/wiki/Frequently-asked-questions#when-i-am-creating-a-new-habit-what-am-i-supposed-to-write-on-the-question-field).

**Comment by sojusnik** [comment]
IMHO, I'm not using questions at all and sometimes need to know what my habits are all about, in form of a small description. So therefore I don't agree, that the "question" feature is supposed to include details about the habit.

Actually, from a usability point of view, it would be even better to remove questions at all and instead have a description field, so that users can faster set up a habit and additionally would see its description in the individual habit overview. I think, that the way HabitBull implemented the notification of a reminder is the best and non-cluttered way, because you only see the habit's name and the description of the habit in the notification, where you can check it off or postpone it.

Please think about adding the description field. I'm sure, that the majority of users aren't using questions at all.

**Comment by iSoron** [comment]
> I think, that the way HabitBull implemented the notification of a reminder is the best and non-cluttered way, because you only see the habit's name and the description of the habit in the notification, where you can check it off or postpone it.

This is exactly what Loop shows if you set up a question for your habit: the title, the question, and then two buttons, to either check it off or postpone it, as the screenshot below shows. I agree that, if this feature is not clear enough, and if users are not using it, then that is an issue.

![media-20160320](https://cloud.githubusercontent.com/assets/4699657/13905648/778a520c-ee9c-11e5-87c7-7f13a8c72ea4.png)

**Comment by sojusnik** [comment]
Ok, I can live with that, as long the notes will be shown in the statistics page.

BTW, huge kudos to your great app! It's rare to find nowadays such a well thought out app, that's also fast and for free. Thank you and keep up the good work!

**Comment by iSoron** [comment]
Thank you for using the app, and please keep the feedback coming.
