### ISSUE TITLE
idea: Change order of history and calendar

### ISSUE THREAD

**Issue by chennemann** [iSoron/uhabits#474]
I think it would be better to change the order of the calendar and the history widget. That is because the user is more likely to find out on which days he completed the habit than how many times he did the habit in a certain month. 

Also it would put the history and the best streak chart together which kinda belong together in my opinion.

What are your thoughts about this?

**Comment by chennemann** [comment]
No I think I didn't put across my point clear enough. Habit strength is the most important thing for me as well. 
I was referring to the bar chart that shows how many times you completed the specific habit in a given month and the calendar view. 

Following is a screenshot of my adjustment: 
![](https://i.imgur.com/uewh8wG.jpg)

For reference I'm taking about those two charts. The order of those is normally switched.  
![](https://i.imgur.com/MKSyDwB.jpg)

**Comment by ziem** [comment]
Now this change makes sense 👍 . I had uhabits 1.7.9 from Google Play and the layout on my device looked differently.

**Comment by iSoron** [comment]
Moved the discussion to #475
