### ISSUE TITLE
Motivational quotes or images

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#48]
To keep the motivation up, inspirational quotes (like implemented in [Rewire](https://play.google.com/store/apps/details?id=com.rstudioz.habits)) or images (as shown in [HabitBull](https://play.google.com/store/apps/details?id=com.oristats.habitbull)) could appear on a daily basis, to a specified time.

**Comment by iSoron** [comment]
Thank you for the suggestion, but I have decided not to implement this feature. I am trying to keep the app minimal, and very focused on doing one job well (tracking habits). Finding and selecting good  inspirational images and quotes is a non-trivial task, specially considering that the app is available in more than 15 different languages. There are also numerous other apps and websites (such as r/getmotivated/) that can show you inspirational quotes and images already.
