### ISSUE TITLE
idea: add gps location to habit

### ISSUE THREAD

**Issue by gigaguy** [iSoron/uhabits#481]
Some habits I track, i'd like to add GPS info to.  Just wondering if that's possible?

**Comment by chennemann** [comment]
Could you elaborate for which habits that could be useful? AFAIK it is not possible at the moment though.

**Comment by gigaguy** [comment]
Just using some example from the screenshots.  Maybe I play chess is a different park and want to look back on where i've played. Same can be said for pretty much any habit.  Where did I read, where did I use a restroom, where did I meditate, where did I have coffee.  Examples could go on. Let me know if you need more info.

**Comment by eSkry** [comment]
Аor example, I want to walk slowly on walks, and for this it is necessary to check whether I am at home or not.

**Comment by iSoron** [comment]
Thank you for the suggestion, @gigaguy. Unfortunately I am not planning to add this feature to the app, both for privacy and technical reasons:

(1) This would require declaring that our app would like to track the user's location. This has huge privacy implications. Most users would probably be surprised that the app even needs this sort of information.

(2) A significant number of users toggle their checkmarks at night, after arriving home, or even a few days after the habit was performed. The recorded location data would be inaccurate.

(3) Just silently storing this data is not enough. We would need to design and implement new screens to clearly show this location data to the user and allow it to correct any incorrect data points, which is a lot of work for a minor feature.
