### ISSUE TITLE
Automatic Backup

### ISSUE THREAD

**Issue by r4taw2mg** [iSoron/uhabits#484]
Please add an option to regularily back up data on a schedule (e.g. daily, weekly). Backup functionality is already part of the app, but I have to do it manually. It would be great, if one could choose, how many backups to keep.

**Comment by mrstlmk** [comment]
Agreed. Good idea.

**Comment by pasbc** [comment]
I too think that it would be a very useful feature. Just something that isn't overly complicated would suffice like syncing at whatever interval to Google drive or something similar

**Comment by iSoron** [comment]
Duplicate of #178.
