### ISSUE TITLE
feature request: Adding a failure state

### ISSUE THREAD

**Issue by SomeDude2** [iSoron/uhabits#488]
Could there be a "failure" state after tapping the habit twice which would add bold cross instead of a tick and hide the habit (if the user has "hide completed" selected)?

For example "Wake up at 6" could be crossed off (and removed from the list) if the user fails to complete the task.

**Comment by YohananDiamond** [comment]
That could be useful. It would help to have a clear list of what you're
actually going to be able to do on the day.

Em seg, 1 de abr de 2019 às 16:54, SomeDude2 <notifications@github.com>
escreveu:

**Comment by iSoron** [comment]
Thank you for the suggestion. This is a mix of two existing issues: #96 and #272.
