### ISSUE TITLE
It seems mathematically impossible to get 100% as score

### ISSUE THREAD

**Issue by hamjo** [iSoron/uhabits#490]
The current formula for the score is the following  : 
```
f(x) = k * x + (1 - k)
```
where `k` is `0.948077` for daily habits, `0.984881` for 2 times a week habits and `0.992411` for weekly habits.
`f(x)` is the score for a day according to the previous score, `x`.
If we want to know what previous score is needed to get a score of `1` or `100%`, we replace `f(x)` by `1` and isolate `x` :
```
1 = k * x + (1-  k)
k = k * x
1 = x
```
This means that we need a previous score `100%` to get a score of `100%`. Which does not make any sense.
Since rounding is always done using `floor` this is unachievable.

This could be fixed by simply adding a constant in the equation.

**Comment by iSoron** [comment]
Great analysis, but it is possible to achieve 100%. You just need to use the app for an infinite amount of time!

More seriously, though, for daily habits, it takes exactly 100 days to reach 100%. Although we don't round the scores when performing the computation, we do round them to two decimal digits on the user interface. After 100 days, your score will be 0.9951, and will get rounded to 1.

**Comment by hamjo** [comment]
Did not check for rounding in the UI. It totally makes sense now!
