### ISSUE TITLE
How can I view the database file?

### ISSUE THREAD

**Issue by skygate2012** [iSoron/uhabits#491]
I accidentally wiped my `/data` partition without backing up, so I am trying to recover the database files. Since the database of Habits is in SQLite format, I restored all of the deleted sqlite-typed files using `photorec`, but the problem is that I do not know which restored file belongs to Habits app. Moreover, the new database file `uhabits.db` which contains my newly created habits data showed empty in DB Browser for SQLite, causing it more difficult to find out the database file. So, is the database encrypted? How can I view it?

**Comment by iSoron** [comment]
@skygate2012 Sorry to hear that. If you are using Linux, to detect which database file belongs to Loop, you could try to run the command `grep Habits *` in the folder that has all the restored database files. If a file matches, the message `Binary file FILENAME matches` will be printed, and you can restrict your search.

Also, our database file is not encrypted. You should be able to open it with any SQLite3 browser.

**Comment by skygate2012** [comment]
> 
> 
> @skygate2012 Sorry to hear that. If you are using Linux, to detect which database file belongs to Loop, you could try to run the command `grep Habits *` in the folder that has all the restored database files. If a file matches, the message `Binary file FILENAME matches` will be printed, and you can restrict your search.
> 
> Also, our database file is not encrypted. You should be able to open it with any SQLite3 browser.

Thanks for replying. I ran the `grep` command and filtered out several files. However, none of them seems to be the database file of Habits because their size are so large (up to 1GB) and when I opened some of them the contents are just package indices of my previously installed apps. Besides, when I ran the command `grep Habits *` in the folder that contains the actual database file (`uhabits.db`) it did not return `Binary file uhabits.db matches`.

**Comment by Dim25** [comment]
Probably you already checked this, but it may be helpful for others: 

From [FAQ](http://loophabits.org/faq.html#q13):
> Loop supports Android's native backup service: if you have backups activated in your phone settings (Settings » Backup & Restore » Back up my data) ..

The interesting catch is that if you have your **Android's native backup service** enabled, but it fails to recover data by itself and you see an empty screen in your app you still may be able to restore it from the backup manually. Go to your app and try to make the full back up (Settings -> **Export** full backup) and see what will be exported in your db file. In my case, it exported all data from Android's native backup service from previously used device. 

Not sure if it's a bug or feature, but for me it was a well desired behaviour :)

**Comment by skygate2012** [comment]
> 
> 
> Probably you already checked this, but it may be helpful for others:
> 
> From [FAQ](http://loophabits.org/faq.html#q13):
> 
> > Loop supports Android's native backup service: if you have backups activated in your phone settings (Settings » Backup & Restore » Back up my data) ..
> 
> The interesting catch is that if you have your **Android's native backup service** enabled, but it fails to recover data by itself and you see an empty screen in your app you still may be able to restore it from the backup manually. Go to your app and try to make the full back up (Settings -> **Export** full backup) and see what will be exported in your db file. In my case, it exported all data from Android's native backup service from previously used device.
> 
> Not sure if it's a bug or feature, but for me it was a well desired behaviour :)

Thanks for the suggestion, sadly I didn't enable Android backup service since I mainly use WebDAV and NextCloud.
