### ISSUE TITLE
Add aggreate widgets

### ISSUE THREAD

**Issue by PrototypeNM1** [iSoron/uhabits#494]
Note: this is different from the stacked widgets currently merged in dev.

It would be nice to have something minimalist similar to the Apple Watch's activity tracker. Ideally this widget would fit nicely into a 1x1 tile and give a sense of all habits progress throughout the day at a glance. Ideally the design would also be a visual sore until completed to motivate action.

What I'm currently imagining is a radial widget where each non-archived task is represented as a petal. When a task is completed it could transition from e.g. a clear blue to solid blue. Other details such as neglected habits being represented as a browning petal. Care would need to be taken not to blow the UI budget representing too much detail.

This is something I would like to work on. I'm hoping to get design thoughts in this issue so that I don't work on something which doesn't match the design philosophy of this project given that Loop's strength is it's conciseness.

**Comment by iSoron** [comment]
Thank you for the suggestion, @PrototypeNM1. I would be interested in seeing a prototype. Please feel free to submit a pull request. In the meanwhile, I will merge this issue with #495. Widgets for groups of habits are a part of that issue.
