### ISSUE TITLE
Import data from CSV

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#5]
It is currently possible to export data to CSV, by long-pressing a habit, then selecting the appropriate option from the menu. It would be nice to also be able to import data, using the same format. I would prefer not having a new permission on the app, if possible.

**Comment by sojusnik** [comment]
Would be nice to have only one csv-file when exporting, since currently, every habit is stored within a separate folder, with its corresponding csv-files, upon export.

**Comment by andunix** [comment]
+1 for all habits in one CSV file. Should we open an separate issue for that?

**Comment by iSoron** [comment]
@andunix Yes, feel free to open a new issue.

**Comment by olejorgenb** [comment]
If anyone else are looking for a generic import format, use the habitbull csv format: https://github.com/iSoron/uhabits/issues/284#issuecomment-332981034
