### ISSUE TITLE
Some activities change state after orientation change

### ISSUE THREAD

**Issue by datalossdetector** [iSoron/uhabits#503]
I developed an automatic test case generation tool and it detected these problems in your app.
I would like to know if you consider them as failures and, if not, why. Thanks for your collaboration.

1) When I change the orientation of the device screen, MainActivity changes its state. Below there are two different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after)

--- first case ---

A Dialog disappears after the orientation change.

![2019-07-25 13-27-08_before](https://user-images.githubusercontent.com/53469180/62161979-8f38e100-b317-11e9-824f-4a8258bce972.png)
![2019-07-25 13-27-08_after](https://user-images.githubusercontent.com/53469180/62161980-8f38e100-b317-11e9-998e-3f5e3d3b6156.png)

--- second case ---

The options "PASTE, SELECT ALL" disappear after an orientation change.

![2019-07-25 11-02-38_before](https://user-images.githubusercontent.com/53469180/62161981-8fd17780-b317-11e9-8c73-08f349d42253.png)
![2019-07-25 11-02-38_after](https://user-images.githubusercontent.com/53469180/62161982-8fd17780-b317-11e9-98e9-389a60c46aab.png)

2) ListHabitsActivity, when I change the orientation of the device screen, changes its state. Below there are four different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after)

**--- first case ---**

The options "CUT, COPY, PASTE, ..." disappear from the screen.

![2019-07-25 21-21-55_before](https://user-images.githubusercontent.com/53469180/62161807-42eda100-b317-11e9-9251-1b32dae1f2de.png)
![2019-07-25 21-21-55_after](https://user-images.githubusercontent.com/53469180/62161808-42eda100-b317-11e9-8aec-9e1b76d7c4d9.png)

**--- second case ---**

The dialog disappears from the screen.

![2019-07-25 18-54-58_before](https://user-images.githubusercontent.com/53469180/62161809-42eda100-b317-11e9-92da-cd006ce5e974.png)
![2019-07-25 18-54-58_after](https://user-images.githubusercontent.com/53469180/62161811-43863780-b317-11e9-85f3-e59d59e725ff.png)

**--- third case ---**

The selected item is no longer selected.

![2019-07-25 16-08-51_before](https://user-images.githubusercontent.com/53469180/62161812-43863780-b317-11e9-88ba-06d62e83c6c5.png)
![2019-07-25 16-08-51_after](https://user-images.githubusercontent.com/53469180/62161813-43863780-b317-11e9-9177-eee152c03b3f.png)

**--- fourth case ---**

The numbers inside the fields change.

![2019-07-25 11-13-04_before](https://user-images.githubusercontent.com/53469180/62161814-43863780-b317-11e9-91c5-9a6fc46b5b78.png)
![2019-07-25 11-13-04_after](https://user-images.githubusercontent.com/53469180/62161815-43863780-b317-11e9-8340-b59a44b10348.png)

**Comment by chennemann** [comment]
thanks for submitting that. 
in my opinion they are all bugs but not all are worth fixing. 

to clarify I would vote to fix case 3 and case 4. the other cases are so minor and probably unlikely to even occur that it is not forth putting in the effort.

**Comment by dlicse1** [comment]
Ok, thank you for your patience and attention!

**Comment by iSoron** [comment]
Thank you for the bug report, @dlicse1. This seems like an interesting tool. I agree with @chennemann that only cases 3 and 4 seem worth fixing it. Pull requests are very welcome.

**Comment by iSoron** [comment]
Case 3 is fixed in the `dev` branch. I don't consider the remaining cases serious issues.
