### ISSUE TITLE
Feature Request: User login with Google or social media

### ISSUE THREAD

**Issue by ShyvayChamanNarved** [iSoron/uhabits#506]
It can help very much

**Comment by hiqua** [comment]
Which login are you referring to? There's currently no login procedure in the app AFAIK.

**Comment by ShyvayChamanNarved** [comment]
I like to login with Google Account in this app so i can see my account or habits in another device.

**Comment by hiqua** [comment]
Ok so unless I'm mistaken, this looks like a duplicate of #104.
