### ISSUE TITLE
Update Support Library to AndroidX

### ISSUE THREAD

**Issue by olegivo** [iSoron/uhabits#507]
Also may be useful to update targetSdkVersion:
[as mentioned](https://developer.android.com/distribute/best-practices/develop/target-sdk), 
>From November 1, 2019, app updates must target at least Android 9.0

**Comment by iSoron** [comment]
See discussion in #517.

**Comment by olegivo** [comment]
@iSoron, I think the discussions in #517 is not related to the subject as AndroidX and Android Studio can be updated separately.

**Comment by iSoron** [comment]
Reopening. Pull requests for this are very welcome.

**Comment by olegivo** [comment]
WIP

**Comment by TacoTheDank** [comment]
I'll make one for this :)

**Comment by olegivo** [comment]
> WIP

done
