### ISSUE TITLE
Notifications broken after latest Android system update (10)

### ISSUE THREAD

**Issue by cakerug** [iSoron/uhabits#509]
![Screenshot_20190914-094508](https://user-images.githubusercontent.com/792431/64909018-cb13e400-d6d4-11e9-9da0-9bdb4c3a9f7d.png)

![Screenshot_20190914-094450](https://user-images.githubusercontent.com/792431/64909019-ce0ed480-d6d4-11e9-9278-94044d49679f.png)

After updating my Android system, the notifications are broken:

- visual: there is a large whitespace below the notifications (see above)
- functionality: you can't swipe away individual notifications anymore if you did not do the habit (see above)
- functionality: you can't scroll down to see all the notifications if you have more than one

**Comment by iSoron** [comment]
Thank you for the bug report, @cakerug.

1. Unfortunately, I could not reproduce the visual glitch shown in your screenshots. Does this happen consistently? Is this restricted to Loop Habit Tracker? Could you please send a bug report from within the app (Settings / Generate bug report).

2. Before you can swipe away an individual notification or execute any actions (such as adding a checkmark), you need to fully expand the notification, by tapping the tiny little arrows on the right side of the screen. This change was implement by the Android operating system itself, not by Loop Habit Tracker. I greatly dislike it, but unfortunately there is nothing that we, app developers, can do to prevent it.

**Comment by cakerug** [comment]
It all seems to have fixed itself. Weird!
