### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by DuMuT6p** [iSoron/uhabits#512]
Hello,
Version v1.7.9 is marked as latest release, but on F-droid it is v1.7.11. On Google Play it is Version 1.7.10. Which one is considered latest stable?
Also v1.7.11 doesn't have release information and changelog file seems outdated.

**Comment by iSoron** [comment]
Hi @DuMuT6p, the latest stable version is whatever is available on Google Play. Currently, that's version 1.7.10. If you enroll in our beta program, you should receive version 1.7.11. This version will become available to all remaining Google Play users after it has been tested for a while. Alternatively, you can get it immediately from F-Droid.

You're right that the releases page here on GitHub is not updated. Thank you for the reminder.
