### ISSUE TITLE
Abide by system wide theme in Android 10

### ISSUE THREAD

**Issue by veyndan** [iSoron/uhabits#513]
In Android 10, users can enable night mode across all apps [at a system level](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme). My proposal is to remove the "Night mode" menu item for API 29+ and abide by the system wide day/night mode. I believe removing it for these users won't be an issue as (to me) it would seem odd to want dark mode across the whole phone and want light mode for one app (and vice versa).

**Comment by iSoron** [comment]
@veyndan Yes, we should do that. Pull requests are very welcome.

**Comment by Anshoe** [comment]
I'm not sure what the popularity would be for others but I am certainly someone who uses a dark mode system wide and has some apps as exceptions. I also know many others who do that. I would like it if the night mode menu item can stick around and behave as it currently does. Can't speak for what everyone's choice would be though
