### ISSUE TITLE
Button in notification to open specific app

### ISSUE THREAD

**Issue by JanMalch** [iSoron/uhabits#516]
I would love to see a feature to add a button in the notification which opens a specific application, depending on the habit.
Like opening a fitness app or a language learning app, etc.

**Comment by NellyWhadsDev** [comment]
This might be a little better scoped if it targeted [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&hl=en_CA) integration. This would allow users to create a Tasker tasks which are not limited to app launching (setting a timer, calling a phone number, playing an audio file, etc.).

Don't know if this is anywhere on the radar for the dev team though. Just some ramblings :)

**Comment by iSoron** [comment]
Thank you for the suggestion, but I don't think there's enough user demand for this feature. If anyone disagrees, please feel free to leave your comment here, and if enough users are interested in it, I may reconsider it.
