### ISSUE TITLE
Reminders show hours early or hours late following time zone changes

### ISSUE THREAD

**Issue by nottheend** [iSoron/uhabits#525]
Seems the app does not care about timezone, but reminds always according to the same UTC time.

Experienced behaviour: if you travel to +1 hour timezone, it will remind you one hour later than before.

I would expect that the reminder comes always at the same relative hour, e.g. 9 am. If you travel to timezone +1 hour, it will still remind at 9:00 am, which is one hour earlier then

**Comment by iSoron** [comment]
Thank you for the feedback, @nottheend. Yes, this is a bug. If the time zone changes after the alarm has been scheduled, then it will show up in the original time zone, not the modified one. The correct solution is probably to reschedule all alarms following a time zone change.

**Comment by nottheend** [comment]
Interestingly in recent past I get the reminders at the correct timings.

Explanation: Reminders occur at the relative timings which have been scheduled originally, no matter which timezone I am in. In other words, the reminder will popup at a point in time depending on the current timezone.

Did anything change in the code on this regard @iSoron?

Another recent change is that I am using Android 10

**Comment by iSoron** [comment]
It's not clear this bug still exists in Loop 1.8.8. If anyone is still having this issue, please let us know and I will reopen it.

**Comment by nottheend** [comment]
Can confirm that the bug no longer exists for me.

Thanks for fixing! 🎉
