### ISSUE TITLE
Incorrect streak behavior

### ISSUE THREAD

**Issue by kamil7x** [iSoron/uhabits#527]
I think, that streak behavior is quite weird. For example if I set my goal to "repeat 3 times in 4 days", I need to do my habit exactly on days 1 2 and 3, to make break on day 4 as not breaking streak.

In my opinion, it should work more like: 3 times in 4 days, starting with day 1, so:
a) 1 2 3 x - would work like it's working now
b) 1 x 3 4 - it's also 3 times in 4 days and I think x should be counted as streak
c ) 1 2 x 4 -same as b
d) x 2 3 4 - it would not mark x as streak part, but instead start streak on day 2, so having a break on day 5, should count as in example a.

What are your opinions?

**Comment by snpefk** [comment]
Double that! 
I have a gym training every Tuesday and Thursday. Skipping Tuesday means an unmarked Monday next week even if I disciplined attend every training.

**Comment by iSoron** [comment]
This has been fixed in Loop 1.8, now available for beta testers on Google Play.
