### ISSUE TITLE
Add a notes field to habits which is not shown in notifications for privacy reasons

### ISSUE THREAD

**Issue by nxxxse** [iSoron/uhabits#529]
Habits have a name and optional question currently. I would propose to add a "notes" field for two reasons:

* Both name and question are shown in notifications. "Notes" should not be shown outside of the app. This allows more private notes to be entered there instead what is shown in your notifications as they are far more likely to be (accidentally) shown to someone else when you show something on your phone. For this case, you could move the habit "requirements" (question field) to the notes and only use a "codename" in the name field that is clear to you but nobody else. This is related to #387 but no duplicate.

* Allow to enter more details of the habit (not privacy related). I am not sure if that reason counts because you could just enter it all into the question field. At least for me, only the first line of the question field is shown in notifications.

Workaround: Enter ".          " some non-space character and a lot of spaces before your actual question to move the actual private question out of the screen.

**Comment by cyphysan** [comment]
I find it helpful to experiment with different Cue, Routine and Rewards for a habit, made famous in a book called "The Power of Habit". Here's a [link](https://charlesduhigg.com/how-habits-work/). I'd LOVE to have a tiny "note" in a habit I'm tracking, like what @nxxxse raised.

Great app and absolutely loving it, thanks!
