### ISSUE TITLE
Allow user to pick Monday or Sunday as the first day of the week

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#53]
The individual habit statistics would look more familiar to Europeans, if the "saturday" and "sunday" would be at the bottom and "monday" at the top (see [here](http://i.imgur.com/pwupLvL.png) for clarification). A setting, to specify the beginning of the week, could easily correct that.

The calendar view is also somehow irritating, because the months name isn't above the column, where the month actually starts, as shown in the picture above.

**Comment by iSoron** [comment]
Thank you for the suggestion. I am making this issue about picking the first day of the week, and I will create a new one for the column not matching the month name.

**Comment by iSoron** [comment]
As of 24c02605d, the first day of the week is picked according to the system locale, so I am closing this issue.
