### ISSUE TITLE
Create widget with list of habits (similar to the main screen)

### ISSUE THREAD

**Issue by SuperHeroWebDev** [iSoron/uhabits#531]
Hi habit lovers! Having a simple condensed widget with habit list would take this app to another level. 
Example in picture. The idea is that you could quickly view and check habits directly from the phone desktop instead of opening the app. 

If anyone is capable of doing it I would be super grateful since I tried doing it myself but have no idea how to make it happen :(

![habits](https://user-images.githubusercontent.com/23101195/71088418-a8470f00-219e-11ea-9203-4644a6e1202c.png)

**Comment by iSoron** [comment]
Thank you for the suggestion, @SuperHeroWebDev. I agree that this feature could be very useful, but unfortunately I am not sure it's technically feasible. Android widgets are very restricted, and even our current (very simple) widgets already required multiple implementation hacks to overcome a number of non-obvious limitations. This would push it to another level.

If anyone is willing to try to code a prototype, that would be great, but I would expect it to be very hard. To clarify, rendering the widget could certainly be done, but accepting input and implementing scrolling would be very tricky, if not impossible.

**Comment by SuperHeroWebDev** [comment]
Thanks for taking the time to clarify and answer. It's to bad the implementation would be so hard to do. Hopefully android widget development gets easier in the coming years. 

Thanks again for everything. For me still the best habits app out there so thank you on that.

**Comment by chennemann** [comment]
what we might be able to do is a not quite as sophisticated version. 
I'm not sure whether or not it is possible but we could maybe implement a widget that is not scrollable and that tries to fit a configurable amount of habits into the given space. by scaling the space and font size down accordingly.

**Comment by nyshocka** [comment]
I love this idea. FYI Nine has a scrolling setup for their Calendar Widget. I dont know the complexity though.

**Comment by chrrris1987** [comment]
I'm not sure if this is a new suggestion, because it's about combining habits in 1 widget.
I love this suggestion to see an overview in the widget, even though you could not check it in the widget and you still get directly to the checking screen when you click it.
I would love if this would be posibble for more widgets, like the ones that give a graphic dot or line how you are doing on a habit over time. Now I have 6 small ones, but how cool would it be to have one big one. That you could choose which habits should be included in the graphic line widget instead of picking one.

**Comment by chrrris1987** [comment]
![2020-02-03 08 52 05 1](https://user-images.githubusercontent.com/60602902/73685861-2e73d200-46c7-11ea-89fc-bb27e941b895.jpg)

For example like this. Above a widget which you maybe can mark, put portrays how you are doing these days. In the example you see all habits, but could be for just the food related habits. And if more widget can combine more habits, you could for example show a graphic line how you are doing

**Comment by Aquabrick** [comment]
I really support this idea. Im new to software development so had no idea this would be so tricky.
Given its usefulness, maybe a non-scrolling widget which simply shows the remaining un-ticked tasks for the day? Clicking would just open the app?

**Comment by amerker** [comment]
I also love this idea of having an overview of multiple habits. Something simple, non-scrolling would already be enough imo.

Specifically I'm thinking of a widget that just shows all active habits, with a (toggleable) checkmark for each habit, which corresponds to its state for the current day.
Which would be the same as creating a Checkmark widget for each habit individually (if you have many, this can get tiresome though, hence this idea).
