### ISSUE TITLE
still get reminders for archived habits

### ISSUE THREAD

**Issue by ezekiel747** [iSoron/uhabits#537]
hi,
first - thank you for this great app.
I noticed that i still get reminders for archived habits - is this normal?
Thank you.

**Comment by iSoron** [comment]
@ezekiel747 Could you please submit a bug report from within the app, so we can better investigate this?

**Comment by iSoron** [comment]
Closing this as fixed. If you are still experiencing this issue in Loop 1.8.8 or newer, please let us know.

**Comment by antgel** [comment]
Hi @iSoron , I was about to open a bug report, then I saw this. I'm still seeing it in 1.8.8. Happy to help debug if you let me know what you need. My data is not very exciting, so I don't mind sharing that privately if it will help you fix the problem.

**Comment by joepetrakovich** [comment]
I just came here to report this issue.  Still getting reminders for an archived habit.
