### ISSUE TITLE
Add "reasons" on habit creation

### ISSUE THREAD

**Issue by AnderRasoVazquez** [iSoron/uhabits#54]
Reading the reasons that we wrote when we created the habit would help to avoid skipping them. For example, [Rewire](https://play.google.com/store/apps/details?id=com.rstudioz.habits) adds three fields and a `+` button to add more.

![photo_2016-03-20_16-34-03](https://cloud.githubusercontent.com/assets/3936719/13905215/a40ea504-eeb9-11e5-825f-e5e5e59ed74d.jpg)

**Comment by iSoron** [comment]
I have created a more general issue for this. See #56.
