### ISSUE TITLE
Notifications in large number no longer combined together in 1.8.x

### ISSUE THREAD

**Issue by szpak** [iSoron/uhabits#546]
I might be wrong, but I recall that notifications when in large number (3+?) were combined together in the top bar in Android 10 and were visible as one icon there.  When swiped down I had to expand the Habits category to see them all (which was much better than 8+ notification at 11 pm to scroll).

However, it no longer happens after an upgrade to 1.8/1.8.5/1.8.6. There is one other icon at the first place, 3 habits icons next and a small dot (informing that there is no many icons to be displayed). I wonder if it could be related to https://github.com/iSoron/uhabits/commit/58ed7592241d3bad87b3b70517147807052056bc#diff-fac3426849f74e19413fdcc13a8e54baL129-R127 and if it can be brought back by some settings changes (I haven't found any).

**Comment by szpak** [comment]
Wouldn't be enough to just [set](https://github.com/iSoron/uhabits/commit/58ed7592241d3bad87b3b70517147807052056bc#diff-fac3426849f74e19413fdcc13a8e54baL129-R127) a group for notifications to `default` or `"group" + habit.getId()` depending on the configuration switch to have two modes available? @iSoron I wonder, what was the purpose of the change (e.g. people disliking grouped tasks in newer Android)?

**Comment by iSoron** [comment]
Notification bundling is temporarily disabled in the beta version of the app. I am planning to re-enable it, but much less aggressively (e.g. bundle only 5+ notifications instead of 2+). The reason is that, from the feedback I received over the last few months, a large number of users had no idea notifications could even be expanded.

**Comment by szpak** [comment]
Thanks for you comment. It was a new mechanism in Android (at least for me migrating to Android 10). However, I believe that people are/will be more and more aware of that change (looking at some other applications it is a default behavior for notifications and it has to be manually changes - as you did - to disable it).

Maybe you could add a switch in the app to disable it? Then both groups of people should be happy (an ability to enter a minimal number of items to bundle would be probably the best for user experience - with some sane default and information in the changelog).

**Comment by szpak** [comment]
I wonder, if you decided to give it a try to tune up the settings to make it more friendly for people preferring bundled notifications?

**Comment by woj-tek** [comment]
I just upgraded to uHabits 1.8.6 from f-droid and was flooded with notifications. I have a couple of habits I track and set reminder for them at the beginning of the day (to have a "nudge"/reminder, with the idea to postpone them throughout the day, though postponing wasn't working in previous versions). In previous versions they were neatly groupped and now they use basically all status bar (also, darn you google with the silly idea of the 'dot' in the notification bar…)

Please bring back (configurable?) grouping :-)

**Comment by sersorrel** [comment]
Bundling is a normal behaviour for apps on Android 10, including commonly-used ones like Gmail. Obviously user feedback is paramount, but it's a lesson that users only have to learn once across the entire system – if bundling is turned off everyone has to live with the unbundled notifications forever.

Do you know if people were generally struggling with expanding the bundle, or with expanding the notifications within the bundle? A real solution would I guess be done by Android itself, with some pop-up over the notification menu, but I guess you could append `(swipe down to expand)` to notifications until the user proves that they know to do so, or maybe include a higher-priority notification exclusively for that purpose the first time a notification is bundled? Or a full tutorial which sends enough notifications to bundle? (though that's obviously a significant amount of work)

**Comment by iSoron** [comment]
Fixed in 09bf49a9cefd0dcb7847a0a622c575100421df06. If four or more notifications are displayed, they are grouped together. If fewer than four are displayed, they are shown separately.

**Comment by szpak** [comment]
Thanks. Do you plan to release 1.8.9 anytime soon?
