### ISSUE TITLE
Migrating from Android to iOS app

### ISSUE THREAD

**Issue by StefanTheWiz** [iSoron/uhabits#548]
Hi,

I've been using the app on Android and it's helped me a lot so thanks for all the effort all of you put in! 🙌

In meanwhile I've moved to iOS and I'm having trouble moving my data over. 

First, is this the app? [link removed] ?

Second, when I'm trying to import the db from Android to iOS, I get an error saying "This data could not be recognised. Please try again"

Please advise
Stefan.

**Comment by iSoron** [comment]
Hi Stefan, thank you for the feedback. The app you linked is an unauthorized clone not related to our project. The official Loop Habit Tracker for iOS is currently under development.

**Comment by liamaharon** [comment]
Hey @iSoron, any eta when Loop will be avail on iOS? Recently switched and have been hurting without it, can't find anything as good

**Comment by dumim** [comment]
Hi @iSoron love your work. Any update on this, a beta version perhaps?
