### ISSUE TITLE
Repeat Custom in Fibonacci Sequence

### ISSUE THREAD

**Issue by davidwilliston** [iSoron/uhabits#551]
Spaced repetition learning is based on the idea that the forgetting curve is exponential. To reinforce long term memory formation or habit forming a review repetition of increasing intervals is proven helpful. Spaced repetition intervals seem to vary as I read from different papers, but all are somewhat similar to that of the Fibonacci sequence.

A custom repeat in Fib seq would be as follows:
0 = initialization
1 = 8 hr (hours from initialization)
1 = 24 hr
3 = 72 hr
5 = 120 hr
8 = 192 hr
13 = 312 hr 
21 = 504 hr
34 = 816 hr (approximately 1 month)

Spaced repetition theory described
https://www.youtube.com/watch?v=cVf38y07cfk&feature=emb_title

Thank you to the developers of this great project. It's so useful for me.

**Comment by iSoron** [comment]
Thank you for the feedback, @davidwilliston. This has been brought up before in #299, but I still think it's outside the scope of the project. I recommend using [Anki](https://apps.ankiweb.net/) instead.
