### ISSUE TITLE
Untranslated line in Turkish translation

### ISSUE THREAD

**Issue by Alp7** [iSoron/uhabits#553]
There's an untranslated line in Turkish translation of the app. It should be:

![SS1](https://user-images.githubusercontent.com/60614101/73662364-96a8c080-4693-11ea-9543-a4fecc0370c4.png)

Customize notifications ==> Bildirimleri özelleştir
Change sound, vibration, light and other notification settings ==> Ses, titreşim, ışık ve diğer bildirim ayarlarını değiştirin.

**Comment by adrienbeau** [comment]
Translation are done on this website: https://translate.loophabits.org/ You can register there and contribute. :)
