### ISSUE TITLE
can we get the full database description?

### ISSUE THREAD

**Issue by mfadel85** [iSoron/uhabits#557]
Thanks very much for this application, it is amazing,

I tried to find a place or file that contains the database, it is distributed in many migrations, can you refer to a place where the database is located?

**Comment by mfadel85** [comment]
Ok, I got it, it is in this path /core/assets/main/databases/template.db, thanks

**Comment by iSoron** [comment]
Hi @mfadel85, our database schema is not part of our public (published) API. What this means is that the format can change at any time. We may even switch away from SQLite in a future version of the app.

In any case, to get the most current schema, the easiest way is to export a backup and have a look using `sqlite backup.db` then `schema`.
