### ISSUE TITLE
Resetting all habits and start from the beginning

### ISSUE THREAD

**Issue by p32929** [iSoron/uhabits#564]
in issue #61 @sojusnik mentioned about a feature to select multiple habits and reset the selected checkboxes. But @iSoron replied with some drawbacks of the feature & completely respect his decision. But how about a feature to reset all the habits without selecting and starting afresh?

in #61 @iSoron mentioned that, we can easily delete and create a new habits. But deleting a lot of habits and re-entering their names, setting reminders for them and also sometimes some people do change the colors, doing all that over and over again for some habits, that's a lot of work to do. A feature to reset multiple/all tasks would be greatly appreciated. This feature can be implemented in the settings activity/page where we cannot go mistakenly and click on the option by chance.

And if you still don't want to add the feature, I'd still respect your decision. In that case, could you please tell us how we can implement the feature in our forked codebase? Which files we need to change and how? That would be greatly appreciated...

Best wishes

**Comment by iSoron** [comment]
> But how about a feature to reset all the habits without selecting and starting afresh?

Thank you for the suggestion, but I unfortunately don't see this as significantly different from what was proposed #61. My comments in that issue are still valid. I have also not seen significant user demand for this feature.

**Comment by p32929** [comment]
I'm not actually asking YOU to implement the feature if you don't want to. I'm just asking, if you could guide us a little bit about which file to change, where to look for, etc that would be really helpful :)

**Comment by chennemann** [comment]
There is a (now closed) pull request for this feature [here](https://github.com/iSoron/uhabits/pull/592). You might have a look there to see how to solve your particular issue.

**Comment by p32929** [comment]
Thanks :) Really appreciate :)
