### ISSUE TITLE
Navigation bar does not change with theme

### ISSUE THREAD

**Issue by VinayMichaelSamuel** [iSoron/uhabits#567]
Android Version 9 with Samsung One UI
App version 1.7.11

Issue
I am using the AMOLED theme but the the Navigation bar is the same as the light mode.
![Screenshot_20200408-194559_Habits](https://user-images.githubusercontent.com/59197885/78806253-7d91f800-79d3-11ea-86a4-6bafbd6bc28e.jpg)

Suggestion
Here's how another open source app is doing this. The navigation bar background changes colour when the theme is changed to match the AMOLED or dark mode colour.
![Screenshot_20200408-014957_Goodtime](https://user-images.githubusercontent.com/59197885/78806402-a4502e80-79d3-11ea-8b7c-6377e71d122c.jpg)

**Comment by iSoron** [comment]
Thank you for the bug report, @VinayMichaelSamuel. Could you try out the beta version of the app and confirm if this issue is still there? You can join our beta program in the link below:

https://play.google.com/apps/testing/org.isoron.uhabits

**Comment by VinayMichaelSamuel** [comment]
This issue is fixed in version 1.8.7.

I had installed the app from F-droid. It still has 1.7.11 as the latest version. Will you be updating the app on F-droid or should I get it from Play store only?
