### ISSUE TITLE
App crashes during sorting

### ISSUE THREAD

**Issue by agepoor** [iSoron/uhabits#569]
App crashes when you don't select 'sort manually' and still select a habit item, right at the moment where you should have been able to drag and drop the item to a different place.

**Comment by iSoron** [comment]
Thank you for letting us know. Could you please send me a bug report from within the app (Settings / Generate bug report) after the app crashes, so we can have a better look?

**Comment by iSoron** [comment]
This seems to be the same bug as #598.
