### ISSUE TITLE
Feature Request: Option to let users explicitly mark a habit as failed

### ISSUE THREAD

**Issue by NunoAGoncalves** [iSoron/uhabits#571]
Explicitly marking a habit as failed (instead of either completed or leaving it blank) will encourage the user to keep track of their habits daily. 

With the current system, I tend to go several days without using the app because I failed my habits. Failing a habit leads to less use of the habit tracker overtime since failures are not recorded; you just leave them blank. I then ultimately forget about app. Tracking the successes, failures, and “not recorded” portions of a habit will encourage daily use of the app as you’ll always have an action that can be completed daily – even if you fail your habits. 

Personal informatics systems have a major issue in that most users forget to use them overtime. A failure toggle system will incentivize the user to track their habits daily regardless of failures or successes. I think something as little as a cross on the calendar or widget will go a long way. 

Hopefully I explained the feature well. I’ve been doing a lot of research on personal informatics system recently and having a failure toggle would be something I’d love to see integrated into Loop. 

Thanks for creating an awesome app @iSoron

**Comment by r4taw2mg** [comment]
I think, this is a duplicate to #96.
