### ISSUE TITLE
Best streaks has duplicated the latest streak

### ISSUE THREAD

**Issue by bootleg-icarus** [iSoron/uhabits#573]
First of all thanks for the app

After a 27 day streak the streak data shows 2 entries of the longest streak. I can fix it by removing the 'tick' for the last day and adding it again. But the next day if I add to the same streak, it happens again.

Environment:
Android: 7.0 ( Moto G4 + )
Loop Version: 1.7.11

**Comment by hiqua** [comment]
Can you reliably reproduce this issue? How?

**Comment by iSoron** [comment]
@bootleg-icarus Thank you for the bug report. I believe this is already fixed in the [beta version of the app](https://play.google.com/apps/testing/org.isoron.uhabits). Could you try it out and let us know?

**Comment by iSoron** [comment]
Closing this as fixed. If you are still experiencing this issue, please let us know.
