### ISSUE TITLE
Missing git tag/GitHub release for v1.8.7

### ISSUE THREAD

**Issue by tlvince** [iSoron/uhabits#576]
Please could you create a git tag/GitHub release for [v1.8.7](https://github.com/iSoron/uhabits/commit/58d8c799ce301fb35be132f36f129d92d79366e0)? That way, F-Droid will pick up the update. Refs https://gitlab.com/fdroid/fdroiddata/-/issues/2013. Thanks!

**Comment by primeapple** [comment]
Hey, @iSoron , we would greatly appreciate this. Please push forwards for more open source software and create a release :-)
It should be done pretty fast!

**Comment by iSoron** [comment]
Release 1.8.7 has now been tagged. Before making v1.8 available on F-Droid, I was doing a staged rollout on Google Play to make sure no serious bugs were present; and, in fact, we had a couple. Updates should be more frequent there now.
