### ISSUE TITLE
Add First Day of Week setting

### ISSUE THREAD

**Issue by nikolayhg** [iSoron/uhabits#578]
Currently the first day of the week is Sunday. This is valid for the America continents and China, but not for the rest of the world according to: http://chartsbin.com/view/41671

Please add the option the user to chose whether Sunday or Monday is the first day of the week.

This issue is related to #336, but created as a separate self-containing issue.

**Comment by iSoron** [comment]
Hi @nikolayhg, that's already available in the beta version of the app. Please try it out:
https://play.google.com/apps/testing/org.isoron.uhabits

**Comment by nikolayhg** [comment]
Awesome, thanks!
