### ISSUE TITLE
Date is incorrectly incremented in History view

### ISSUE THREAD

**Issue by di72nn** [iSoron/uhabits#58]
In the morning (and most of the day?) the view is ok (the first image), but in the evening the dates are incremented (the second image):
![correct](https://oc.di72nn.com/index.php/s/TxENQwyUVtDa7Dv/download)
![incorrect](https://oc.di72nn.com/index.php/s/DFKmmRsEFM5yZNM/download)
A history editor is shown, but 'History' view looks the same.

My guess is that happens at UTC midnight (which is 4 hours before my local midnight - my timezone is UTC+4), but I forgot to check it at 8 p.m..
After my local midnight a new grey square appears and everything goes back to normal.

**Comment by iSoron** [comment]
Thank you for reporting this issue. It is definitely an issue with time zones.
