### ISSUE TITLE
Allow user to dismiss sticky notification

### ISSUE THREAD

**Issue by goforgold** [iSoron/uhabits#581]
Hi @iSoron 

Heartfelt thanks for this wonderful application!

I am in kind of need of a small change since you developed a very useful feature #106.

I have enabled sticky notification so I don't accidentally clear the notification which I did plenty of times when I had sticky notifications disabled.

But I also need something so I can mark a habit unchecked (or skip for the day) at the same time. Without this, I see the notification until the next occurrence which is basically replaced by the current occurrence.  This makes it confusing. For example, I have a habit "brush your tooth" at 10:30 PM every day. Now, I missed it for say Monday then I will see the notification through the entire day on Tuesday and if I brush my teeth at 10:00 PM (earlier than I scheduled it) then I sometimes accidentally mark this checked right from the notification which was actually the notification for the previous day.

I find notifications very useful feature in this app to quickly mark the habit done for the day.

I would suggest adding a button `Skip for the day` or `Skip this occurrence` in the notification itself so if I miss the habit then I can simply let the notification getaway.

The workarounds I use as of now to clear the notification are:

1. Force stop app in the morning before my first habit of the started.
2. Go to the app, check the habit and then uncheck the habit back to clear state.

I am really in love with this application. It has brought regularity to a good number of things which I couldn't regulate from a long time.

I am not an Android developer but If you think what I am suggesting makes sense, I can ask one of Android developer friend to make a pull request for this change.

**Comment by iSoron** [comment]
Thank you for using the app, @goforgold. This should be now possible in the beta version of the app. Please try it out on Google Play. Instead of "check" there are now two buttons: yes and no.

**Comment by goforgold** [comment]
Hi @iSoron 

Thanks for this update.

Actually, I see there are three buttons now. Yes, No and Later.

Can you please tell me the difference between No and later?
