### ISSUE TITLE
Class of activities [feature request] 

### ISSUE THREAD

**Issue by noamteyssier** [iSoron/uhabits#587]
Hello all,

I love this app and use it all the time, but there's a feature I think would be incredibly useful that I would love to have implemented.

Essentially having sub-habits within a single habit. For example having an exercise habit and being able to nest running, biking, climbing etc within it. So when any of them are checked the highest level (exercise) is checked but each sub habit can still be tracked independently. I think it could reduce on row space in the app when habits belong to the same class of activities, make the app look much cleaner, and could also be really useful to people who are interested in tracking sub-habits within a hobby.

**Comment by chennemann** [comment]
This was already requested multiple times and is quite complicated to implement. We discussed a potential solution [here (#495)](https://github.com/iSoron/uhabits/issues/495). 

As far as I know nobody has started to work on it so far.

**Comment by iSoron** [comment]
Let's keep this discussion in #495
