### ISSUE TITLE
Description field.

### ISSUE THREAD

**Issue by rtevans01** [iSoron/uhabits#588]
Hello. I'd like to request an option be made to type a description when creating or editing habits. Since the title field is limited for visible space, it would be nice to have a second box for inputting context or notes. Thanks in advance e for the consideration.

**Comment by hiqua** [comment]
There's already a "question" field, does this not satisfy your needs? If not, do you have a more precise example?

**Comment by iSoron** [comment]
Thank you for the suggestion. We recently added a "notes" field in the development version of the app. It should become available to all users in the future.
