### ISSUE TITLE
Feature request: Add a button to randomly suggest an open task

### ISSUE THREAD

**Issue by bookshelfninja** [iSoron/uhabits#589]
Quite frequently I'd like to have a random suggestion for an unfinished task. A dice button at the top choosing one task at random and maybe offering a "roll again" function would be nice.

**Comment by hiqua** [comment]
This could easily be done by implementing a random sort on the habit list (that would require that you open the app though), but I'm not sure how many people would use this, and if it's even desirable in practice. If you can't complete all your goals, it means that these goals are too high.

**Comment by iSoron** [comment]
Thank you for the suggestion, @bookshelfninja, but I don't think there's enough user demand for this feature. If anyone disagrees, please feel free to leave your comment here; if enough users are interested in it, I may reconsider it.
