### ISSUE TITLE
Problems with Spanish translation

### ISSUE THREAD

**Issue by AnderRasoVazquez** [iSoron/uhabits#59]
**Red rectangle**: doesn't fit
**Blue rectangle**: instead of `veces` the text needs to be `veces cada`.
![photo_2016-03-21_17-56-35](https://cloud.githubusercontent.com/assets/3936719/13926916/bd101e22-ef8e-11e5-9f76-05e69cc993e3.jpg)

**Comment by iSoron** [comment]
Thank you for letting me know. The red rectangle issue has been already fixed. For the blue, please feel free to change the translation yourself at POEditor. Before each release, I always download the new version of the translations from there.

**Comment by AnderRasoVazquez** [comment]
Fixed.
