### ISSUE TITLE
Unable to remove notification if ticked manually from inside the app

### ISSUE THREAD

**Issue by mayank-ramnani** [iSoron/uhabits#593]
## Steps to reproduce:
1. Wait for notification reminder to appear on notification bar.
2. Go into the application and tick the habit manually.
3. Get out of the app and try to "check" the habit from notification.

## Expected behavior:
Since the habit was already checked manually from inside the app, clicking on the "check" button should remove the notification from the notification bar.

## Actual behavior:
Unable to remove the notification.
Swiping away doesn't work since sticky notifications are enabled,
"check" doesn't do anything.

## Workaround that works:
Untick the habit from inside the app, then click on "check" button from the notification.
That ticks the habit and removes the notification as well.

## Suggested fix:
Clicking on "check" from notification should check the state to see if the habit is already checked or not.
If it is checked, remove the notification.

**Comment by chennemann** [comment]
Even better (I don't know whether it's possible though) would be to remove the notification as soon as you check the habit inside the application.

**Comment by iSoron** [comment]
@mayank-ramnani Thank you for the bug report. Could you try out the [beta version of the app](https://play.google.com/apps/testing/org.isoron.uhabits) and let us know if the problem still happens? If it does, could you send us a bug report from within the app after you experience this issue?

@chennemann That's what the app already tries to do; when a checkmark is added, the app tries to dismiss the corresponding notification.

**Comment by me-manikanta** [comment]
I have tested this today and looks like it is working as expected

**Comment by iSoron** [comment]
Closing this as fixed. If you are still experiencing this bug, please let us know.
