### ISSUE TITLE
 Rotating the screen while setting the reminder time will cause the set time to be lost

### ISSUE THREAD

**Issue by sjl872964789** [iSoron/uhabits#599]
**Describe the bug**
 Rotating the screen while setting the reminder time will cause the set time to be lost

**To Reproduce**
1. Install and open uhabits
2. Click the Add button
3. Click the drop-down box after ”reminder“ to set the time
4. Rotate screen
5. Click "Done"

**Expected behavior**
The selected reminder time will not be lost

**Consequence**
As users can create habit without reminder time, they may not notice that the time is not set successfully, and they do not understand why uhabit does not remind themselves at the reminder time they set

**Smartphone (please complete the following information):**
 - Android version : Android 8.1.0
 - uhabits Version : 1.8.7

**Additional context**
If the user rotates the screen when setting the reminder time, the situation is as follows:
![rotate](https://user-images.githubusercontent.com/15941953/85419344-8e024980-b5a4-11ea-95fb-1efd8c12174c.gif)

If the user does not rotate the screen when setting the reminder time, the situation is as follows:
![no rotate](https://user-images.githubusercontent.com/15941953/85421394-f4886700-b5a6-11ea-89df-e05e6c3d73d2.gif)

**Comment by tingsu** [comment]
Similar issue here. Any update? Thanks.

**Comment by iSoron** [comment]
Thanks for reporting. This issue has already been fixed in the `dev` branch.
