### ISSUE TITLE
Allow other apps to put checkmarks

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#6]
In many situations, other automation apps, such as Llama or Tasker, could add the checkmarks automatically for the user. For example, a user could create a location-based trigger on Llama or Tasker that would add a checkmark on a certain habit every time they arrive the gym.

This would require us to implement custom intent filters in our app, and write some documentation on the wiki, explaining how to set everything up.

**Comment by pymai** [comment]
tasker support would be really great. 

im trying to do at least 10 minutes of learning spanish every day using duolingo but if there was tasker support you could count how long the duolingo app was open for and then tick off the habit once it went over a certain time!

**Comment by iSoron** [comment]
I have implemented this feature in the `dev` branch. Please see the [wiki][1] for more information.

[1]: https://github.com/iSoron/uhabits/wiki/Integration-with-Tasker

**Comment by iSoron** [comment]
The app now implements a Tasker plugin, so the configuration should be much easier. I have updated the wiki with a step-by-step instructions for Tasker. Let me know if you would like to write a similar guide for other apps (such as Automate and Locale).
