### ISSUE TITLE
Enabling vacation mode support to pause breaking streaks

### ISSUE THREAD

**Issue by jigneshdarji91** [iSoron/uhabits#601]
With the onset of Summer, most people are taking days off and might want to pause some habits. But this shouldn't break the streaks. It's not a result of laziness but a planned break. 

Todoist does a similar feature. Here's a snippet for example.
![image](https://user-images.githubusercontent.com/7569156/85790462-1982f400-b6e5-11ea-9893-6d14b36cdb70.png)

**Comment by chennemann** [comment]
I really like this idea. To circumvent this I always decide from a case to case basis whether I just loose the streak or check it off even though I didn't actually do it to not loose the streak/strength

**Comment by mrshll1001** [comment]
I think this is a good idea. I've been gunning for a vacation or suspension mode for habits for a while. In some cases the user might want to be trying to maintain the habit despite the vacation e.g. using the classic example of "meditation" you can still meditate while travelling for work, on vacation, etc. but a lot of the time there isn't scope for some habits.

For example a habit to clean the kitchen, or go cycling once a day will not be possible if you're travelling for work and don't have access to these things. In some extreme cases such as a temporary, but major, disruption to lifestyle and rhythm (e.g. family death etc) it might not be nice to also have your habits strength deteriorate. 

I do a similar thing to @chennemann where I often tick the habit off when under exceptional circumstances despite not being able to do-the-thing every time. I think there's a case for using the existing mechanism of the grey ticks when a habit is set to suspended / paused / vacation mode.

**Comment by chennemann** [comment]
One thing we should think about though is the way we want to handle it. It might be desirable to suspend certain habits but keep others active. Would we implement a global switch and just allow for explicit checking or should we make every habit suspendable independently? 
I don't think we should have both options and the one by one strategy is probably too much overhead to be usable. Any other ideas?

**Comment by iSoron** [comment]
This seems fundamentally the same as #88, although the proposal here is to pause all habit simultaneously, while the proposal there is to pause them individually. Let's keep this discussion focused on one thread, so that new contributors can find it more easily.

**Comment by jigneshdarji91** [comment]
@iSoron ack!
