### ISSUE TITLE
Remove internet permission

### ISSUE THREAD

**Issue by asdoi** [iSoron/uhabits#603]
In the privacy policy (https://loophabits.org/privacy) is written, that the app does not send any data and does not use any analytical services/libraries.
After I read that I analyzed the AndroidManifest.xml and saw that the app uses the Internet permission.
Basically this app does not send any data or something else, so I did not see any reason for that permission.

After some research I found #104 and I think that is the reason.
So I think a short explanation about the use of the internet permission would make it clear.
Because now the privacy statement says that the app does not send any personal data at all, but that would be in contrast to the use of the internet permission.

So to put it in a nutshell a short explanation in the privacy policy about the use of the internet permission, would increase the confidence in the app.
Or as #104 is not finished a removal of the internet permission, as well.

**Comment by biolauri** [comment]
I'd definitely prefer the removal of the permission as long as there's no need for it.

**Comment by iSoron** [comment]
I will remove this permission in Loop 1.8.9 and reintroduce it when we finish implementing #104 (probably in Loop 2.0).

**Comment by iSoron** [comment]
Fixed in 38fb37cde2c45356cc95d0d2eabab7eec977b791
