### ISSUE TITLE
Notification Not Work on Mi 10 Pro

### ISSUE THREAD

**Issue by xuhuanfeng** [iSoron/uhabits#609]
Hi,

  Recently, I'm using the Mi 10 Pro(Android version is 10, MIUI version is 12.0.2 Stable), But I found that the notification is not work. 

  I'm sure that already enabled the "Make notifications sticky" option as well as allowed the system permission for notified

  But it couldn't notify me, which is working well in Mi 6.

**Comment by iSoron** [comment]
Hi @xuhuanfeng, thank you for the bug report. Could you wait until the notification was supposed to show up, then, after you have confirmed that they indeed didn't appear, could you go into the settings and send me a bug report from within the app? Also, please make sure you update to Loop 1.8.8; we have made some changes to the notifications in that release.

**Comment by xuhuanfeng** [comment]
Hi @iSoron, I'm so sorry that I forgot to check the latest version before reporting the bug. After update to 1.8.8, the notification work fine now :)

Thank you very much.
