### ISSUE TITLE
Some text on the page has not been translated

### ISSUE THREAD

**Issue by sjl872964789** [iSoron/uhabits#620]
**Describe the bug**
Some text on the page has not been translated

**Context**
 - Device: [PIXEL XL]
 - OS version: [Android 10.0]
 - App version: [1.8.8]

**How to reproduce**
Steps to reproduce:
0. Change the language to Chinese in the system settings
1. Install uhabits and open
2. Click on three points in the upper right corner
3. Click on "preference" ("设置" in chinese)

**Expected behavior**
The text is translated correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/15941953/90306343-e4359e00-defe-11ea-8ddb-ee9f595c0ac7.png)

**Comment by chennemann** [comment]
Can you provide the correct translation? 
Either here or in the form of a pull request. That would make it much easier to fix ;)

**Comment by iSoron** [comment]
Thank you for the bug report, @sjl872964789. These strings have already been translated in our [translation platform](https://translate.loophabits.org) and should make it into the next version of the app. However, there are still some other strings that have not been translated to Chinese yet. If you could submit your translations there, that would be very helpful.

**Comment by sjl872964789** [comment]
Thanks for your quick reply. I have only noticed that there is no translation in these three places. It seems that you have solved it. If I find anything else, I will help to provide translation.
