### ISSUE TITLE
Add multiple times per DAY rule

### ISSUE THREAD

**Issue by injainja** [iSoron/uhabits#628]
Really awesome. Only thing missing is doing tasks several times per DAY. Like: drink 8 glasses of water per day. Or: meditate 3 times per day. This could be achieved by not displaying a check mark when clicking, but a countdown and on the final click the checkmark. E.g.: eat fruit twice a day will not show '❎'  but '2' each day as default. After my first fruit '1' and after my second fruit '✅'. That would be perfect.

**Comment by iSoron** [comment]
Duplicate of #42
