### ISSUE TITLE
Don't recognize backup data 

### ISSUE THREAD

**Issue by Villelmo** [iSoron/uhabits#632]
I export data saved .db and csv and when i want import data from memory of device don't recognize. I can't import backup data and visualize. 

SCH-I435 4.4.2
uhabits 1.7.11

**Comment by iSoron** [comment]
Hi @Villelmo, your backup is probably being rejected because it was generated by a newer version of the app. The current stable version is Loop 1.8.8. Unfortunately, this version no longer runs on Android 4.4 (KitKat).

**Comment by Villelmo** [comment]
For example, i make a backup with the new version and i want import this data, but equally don't recognize.

**Comment by iSoron** [comment]
Hi @Villelmo, it seems like you are trying to import a backup generated by a newer version of the app (probably 1.8.8) into an older version of the app (1.7.11). Unfortunately, this is technically impossible to do, so I am closing this issue. If this is not the situation, please let us know and I will reopen the issue.

**Comment by Villelmo** [comment]
I test two _scenario_:

1. Generate a backup from version 1.8.8 and try to import this backup with the same version

- Any result

2. Generate a backup from version 1.7.11 and try to import this backup with the version 1.8.8 

- Any result

**Comment by landry314** [comment]
what are you saying? this last post has no value.
