### ISSUE TITLE
"Help & FAQ" crashes the app when no browser is installed/enabled 

### ISSUE THREAD

**Issue by j4nw** [iSoron/uhabits#636]
Hey, I usually use my phone with Chrome disabled, as a way to focus and quit mindless browsing.

Understandable that the FAQ is just a webpage and not viewable without a browser, but crashes could be handled.

Thanks

[bugreport.txt](https://github.com/iSoron/uhabits/files/5195351/bugreport.txt)

**Comment by iSoron** [comment]
Thank you for the bug report, @j4nw. This has been fixed recently in the `dev` branch.
