### ISSUE TITLE
Widgets don't update automatically on new day

### ISSUE THREAD

**Issue by j4nw** [iSoron/uhabits#637]
I use the Checkmark and History widgets in tandem on my home screen. They show state for the previous day (Checkmark appears completed, and History shows one calendar day less), until interacted with in some way.

Thanks

**Comment by KristianTashkov** [comment]
https://github.com/iSoron/uhabits/commit/d59ab8942621881648161e7a4e5588ce8e3463af
Fixed recently! Not sure when @iSoron plans on releasing that version though :)

**Comment by j4nw** [comment]
Great to know, thank you!
