### ISSUE TITLE
Remove space around checkmarks

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#64]
When ticking habits off, you sometimes accidentally touch the small area around a checkmark (as indicated [here](http://i.imgur.com/XR2hiDM.jpg)), that opens the statistics window of a habit, which is quite annoying. Is it possible to remove this area?

**Comment by sojusnik** [comment]
This is also true for a small stripe between two checkmarks. Just try several times to click between them.

**Comment by iSoron** [comment]
Fixed in b601a64
