### ISSUE TITLE
[Feature] [Easy] Add total of accomplished per day

### ISSUE THREAD

**Issue by PeterBridge** [iSoron/uhabits#640]
Hi, I have been using Habits almost all this year and at the end of the day I'm used to count how many of my items I have accomplished.
I would like this to be done automatically and I'm sure this would benefit a great number of users.

My idea is as follows:
Add a row at the bottom (similar to that one of the date at the top) labeling it for example "Total of the day". It would display non-interactive numbers that change whenever the user check/uncheck an item, displaying the number of the items accomplished in each day.

================================

Up to this point that's all. However, this feature would have potential to add more features. Supposing I have 12 items in the app:
1. **Configure a number as objective per day:** Let's say I set it to 10. When I reach 10 my total is marked in a green circle. Otherwise it remains normal.
Optional/Additional:
- Configure a minimum objective: Let's say 5. It marks the day in an orange circle.
- Differentiate objective reached from perfect day: 10/12 would be different of 12/12
2. **Click the "Totals" label to see statistics:** For now I just would like to see a graphic where I see the days when I accomplished my objective per day. (And perfect day, lower objective if included).

Thank you all and regards!

**Comment by iSoron** [comment]
Thank you for the feedback, @PeterBridge. I consider this part of #51.
