### ISSUE TITLE
I can't import my habits

### ISSUE THREAD

**Issue by GANGST1ER** [iSoron/uhabits#647]
When I try import habits, it says file unable to determine file type. What should I do? Android 10.

**Comment by hiqua** [comment]
What's the filename? Did you export / backup from the same version of uhabits?

**Comment by GANGST1ER** [comment]
I used this app for a long time, then it started loading habits for a long time after the mark. I went with a backup to another app, a copy of this one, which is in Google play. After some time, this application was updated and I decided to try to return, but it does not accept a backup from that copy of this application, although the backups, their names and the databases themselves are identical, but it does not accept.

**Comment by hiqua** [comment]
Which copy of this application?

**Comment by iSoron** [comment]
@GANGST1ER Sorry, but there is no guarantee that backup files generated by clones of Loop will work with the official app.

**Comment by GANGST1ER** [comment]
> Which copy of this application?

This app (https://play.google.com/store/apps/details?id=com.herman.habits).

**Comment by GANGST1ER** [comment]
> @GANGST1ER Sorry, but there is no guarantee that backup files generated by clones of Loop will work with the official app.

It used to work, but now it doesn't. I don't know how to go back to the original app with my habits. I have hundreds of them.

**Comment by hiqua** [comment]
> > @GANGST1ER Sorry, but there is no guarantee that backup files generated by clones of Loop will work with the official app.
> 
> It used to work, but now it doesn't. I don't know how to go back to the original app with my habits. I have hundreds of them.

Please ask the "author" of the copy you used about that. If you manage to find the code (which they legally have to publish given the license), you could try to match the versions and import the files in the matching version of uhabits.

**Comment by GANGST1ER** [comment]
> > > @GANGST1ER Sorry, but there is no guarantee that backup files generated by clones of Loop will work with the official app.
> > 
> > 
> > It used to work, but now it doesn't. I don't know how to go back to the original app with my habits. I have hundreds of them.
> 
> Please ask the "author" of the copy you used about that. If you manage to find the code (which they legally have to publish given the license), you could try to match the versions and import the files in the matching version of uhabits.
> 
> Edit: you can also try with older versions the app. On F-Droid, as of now, two older versions are available, one dating back to August 2019.

I tried old versions of the original app, but it doesn't work. Comparing the databases of two applications using the sql program also does not help.

**Comment by hiqua** [comment]
You can export the full backup from the copied app, compare with a backup of the current app, and try to see the differences, and write some script to convert it.

You said that it used to work with a previous version of uhabits, right? They are actually all available there: https://github.com/iSoron/uhabits/releases so you can try to find the version which was working.

If it doesn't work anymore because of the "author" of the copy made some changes, you should ask them directly.

**Comment by GANGST1ER** [comment]
Here is the app https://github.com/hedongfu/7-Habits. I tried all versions, writes allegedly incorrect format when importing, although they are the same.

> Вы можете экспортировать полную резервную копию из скопированного приложения, сравнить с резервной копией текущего приложения, попытаться увидеть различия и написать сценарий для его преобразования.
> 
> Вы сказали, что раньше он работал с предыдущей версией uhabits, верно? Фактически все они доступны здесь: [https://github.com/iSoron/uhabits/releases,](https://github.com/iSoron/uhabits/releases) чтобы вы могли попытаться найти версию, которая работала.
> 
> Если это больше не работает из-за того, что «автор» копии внес какие-то изменения, вы должны спросить их напрямую.
