### ISSUE TITLE
Remember scroll position of main view when using back arrow

### ISSUE THREAD

**Issue by sojusnik** [iSoron/uhabits#65]
When using the back arrow, located at the left upper corner in the main bar, the scroll position of the main view is not saved.

**Comment by iSoron** [comment]
Yes, this is an issue. It is even worse than that, actually. The entire application is restarted when you press that back arrow, so if you have a lot of data, it can even take some time for everything to reload.

**Comment by regularcoder** [comment]
I would like to work on a fix for this issue.
