### ISSUE TITLE
Add option to play sound when completing a habit

### ISSUE THREAD

**Issue by pccchiang** [iSoron/uhabits#654]
Feature request to add option to vibrate and/or play sound when completing a habit.

**Comment by iSoron** [comment]
Thank you for the feature request, @pccchiang. Playing a sound after a habit is completed would be nice. I'm not sure whether this should be enabled by default, but at least it should be an option. Pull requests are welcome.

Regarding vibration, if you have "touch vibration" enabled in your phone settings (Settings / Sound) and your phone is not mute, then the app should already vibrate when adding a checkmark. If it doesn't, that's a bug.
