### ISSUE TITLE
Sort by Score decending

### ISSUE THREAD

**Issue by sputtering** [iSoron/uhabits#656]
You have an Sort->Score  option. What I would love is an option "Sort->Score dec". This would sort the list by descending score. That way the habit that needs the most work is at the top.

**Comment by Vncntmrchl** [comment]
Hello,
This issue seems to have already been dealt with as I don't have this bug on the current dev build (available on here).
I guess we only have to wait for the update to be made on the application stores.

**Comment by sputtering** [comment]
@Vncntmrchl  Are you saying that you have an option to sort with score ascending and descending? If so, where can I get the dev build?

**Comment by iSoron** [comment]
Thank you for the feature request @sputtering. As @Vncntmrchl mentioned, this has already been implemented and should be available in the next version of the app. 

The dev build is only available to developers. I don't recommend using it, as it contains bugs and incomplete features.
