### ISSUE TITLE
Display number of days since the habit was last performed

### ISSUE THREAD

**Issue by mohanrajkumarplus** [iSoron/uhabits#657]
we can either add a number near the habit indicating, the number of days since we have done this habit

example - habit 1 ( 3 ) --> here 3 indicates, we did this habit 3 days back

on top of it we can provide a order by based on aging habits similar to "score", but this will be purely based on the days

**Comment by iSoron** [comment]
Thank you for the suggestion, @mohanrajkumarplus. I welcome proposals to display this data in the app's main screen, but I would like to see actual mockups of the proposed UI changes. I don't think showing this number inside parenthesis is a good idea.
