### ISSUE TITLE
We found flaky tests

### ISSUE THREAD

**Issue by shaker-project** [iSoron/uhabits#659]
Hello, we are a group of researchers that investigate the occurrence of flaky tests in Android.

We voluntarily ran your GUI tests 20 times and found that some tests pass or fail non-deterministically, which characterizes them as flaky tests [1]. Below we list each flaky test we found, and its number of failures.

* `shouldDisplayAboutScreenFromSettings` failed 12 times ([stack trace](https://github.com/iSoron/uhabits/files/5540141/shouldDisplayAboutScreenFromSettings.txt))
* `shouldDisplayAboutScreen` failed 13 times ([stack trace](https://github.com/iSoron/uhabits/files/5540143/shouldDisplayAboutScreen.txt))
* `shouldEditHabitBlankDescription` failed 12 times  ([stack trace](https://github.com/iSoron/uhabits/files/5540145/shouldEditHabitBlankDescription.txt))
* `shouldShowHabitStatistics` failed 14 times  ([stack trace](https://github.com/iSoron/uhabits/files/5540147/shouldShowHabitStatistics.txt))
* `shouldDeleteHabit` failed 12 times  ([stack trace](https://github.com/iSoron/uhabits/files/5540149/shouldDeleteHabit.txt))
* `shouldEditHabit_fromStatisticsScreen` failed 12 times ([stack trace](https://github.com/iSoron/uhabits/files/5540151/shouldEditHabit_fromStatisticsScreen.txt)
* `shouldCreateHabit` failed 12 times ([stack trace](https://github.com/iSoron/uhabits/files/5540152/shouldCreateHabit.txt))
* `shouldArchiveAndUnarchiveHabits` failed 12 times ([stack trace](https://github.com/iSoron/uhabits/files/5540154/shouldArchiveAndUnarchiveHabits.txt))
* `shouldHideNotesCard` failed 13 times ([stack trace](https://github.com/iSoron/uhabits/files/5540155/shouldHideNotesCard.txt)
* `shouldToggleCheckmarksAndUpdateScore` failed 12 times ([stack trace](https://github.com/iSoron/uhabits/files/5540156/shouldToggleCheckmarksAndUpdateScore.txt))
* `shouldEditHabit` failed 14 times ([stack trace](https://github.com/iSoron/uhabits/files/5540157/shouldEditHabit.txt))
* `should_not_crash_after_deleting_then_adding_a_habit` failed 12 times ([stack trace](https://github.com/iSoron/uhabits/files/5540162/should_not_crash_after_deleting_then_adding_a_habit.txt))
* `testBundleSavedState` failed 12 times ([stack trace](https://github.com/iSoron/uhabits/files/5540164/testBundleSavedState.txt))

We ran these tests on a generic Android Emulator (AVD) with Android API version 28.
 
If you confirm this behavior, our suggestion is to add the `@FlakyTest` annotation on these tests. See https://developer.android.com/reference/androidx/test/filters/FlakyTest

If you wish for a repair proposal, please let us know.
 
Graciously,
[Denini](https://github.com/denini08), [Leopoldo](https://github.com/leopoldomt) and [Marcelo](https://github.com/damorim).

[1] https://hackernoon.com/flaky-tests-a-war-that-never-ends-9aa32fdef359

**Comment by iSoron** [comment]
Thank you for running these experiments on our repository, @shaker-project. However, all the tests identified as flaky by your tool seem to be interface tests (currently annotated with `@LargeTest`). It's already common knowledge that such tests are very flaky on Android, which is part of the reason why they are not in our CI.
