### ISSUE TITLE
DarkTheme : color and font inconsistencies in Settings

### ISSUE THREAD

**Issue by Nirvyz** [iSoron/uhabits#662]
Hello,

I'm a student in software engineering. My workmates and I are trying to contribute to an OpenSource project and we chose to work on your app. We saw that the issue linked to the Dark Mode in Settings has been dealt with not long go.
After the modification has been merged, we spotted some problems :

       -   In DarkTheme : the toolbar color is different in settings and on the Home Page.
       -   In DarkTheme the navigation bar is transparent, but not in LightTheme (in LightTheme the navigation bar is of the same color as the toolbar), we suggest to make it transparent in LightTheme too.
       -   In DarkTheme : submenus in Settings still have dark fonts which make them hard to read.

We are working on these issues. The two first ones are done and we are now working on the last one, we will soon make a pull request.

**Comment by iSoron** [comment]
Closed by f80fb35e35977b2591023ae8b49467b3f8db06dc
