### ISSUE TITLE
Sugestão de alteração

### ISSUE THREAD

**Issue by vitorroliveiraa** [iSoron/uhabits#664]
Após alguns meses usando o app, algo começou a incomodar. Eu utilizo demais os widgets de frequência e marcação, dessa forma uma vez e outra entro no app, esse recurso é ótimo. Porém quando acaba uma semana, o widget frequência continua com as marcações da semana anterior. Minha sugestão é que somente no widget frequência, quando trocar a semana, ele limpa os valores da semana anterior. Caso eu queira ver a minha frequência com mais detalhes, eu entro no app e analiso.
Só uma dica. 
Gostaria de contribuir no projeto, mas não sei nada de Kotlin.

**Comment by iSoron** [comment]
Thank you for the suggestion, but please let's keep all discussion here in English.

**Comment by vitorroliveiraa** [comment]
Blz, if there is anything i can help i am available
