### ISSUE TITLE
[Accessibility] Touch Target is not respected.

### ISSUE THREAD

**Issue by andreacantone** [iSoron/uhabits#665]
## Description

The size of the elements should be at least 48dp*48dp. Some elements don't respect the size of the touch target.

## How to reproduce the error

1. Activate the app [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=it&gl=US)
2. Open the app [Loop Habit Tracker](https://play.google.com/store/apps/details?id=org.isoron.uhabits&hl=it&gl=US)
3. Activate the registration from the Accessibility Scanner and use the Loop Habit Tracker app.
4. After using the app, stop the recording.

## Screenshot

The results will show the errors found in the app. For example:

![IMG_20201118_172651](https://user-images.githubusercontent.com/25429624/99558456-0d653f00-29c4-11eb-9044-120560d98f3e.png)

**Comment by iSoron** [comment]
This issue has been fixed in the `dev` branch.
