### ISSUE TITLE
Export Full Backup Feature Not Clear On How It Is Saving A File in Android Folder

### ISSUE THREAD

**Issue by landry314** [iSoron/uhabits#668]
When you use the "Export Full Backup" feature to create a backup file, it immediately pulls up a chooser dialog with a list of apps to share with but none of the apps actually do anything for me. I need to back out and it appears nothing happened. What is unclear is that this feature is ALSO creating a backup file in /Android/data/org.isoron.uhabits/files/Backups/.

This is poor design for a few reasons. First, the user is unaware that a file is being saved and where to go to get it. It does something behind the scenes which is hard for the user to figure out or take action on. Second, it does something unexpected which is act like a share feature. It is a backup feature, not a share feature.

I suggest a rehaul of this feature. Here are some suggestions:

1) Open a dialog explaining that the file was saved in PATH... maybe even just a Toast saying this. Anything!

2) Have an option to save the file where the user wants to save it. I have a Backup folder for all my backup files. It would require a new permission but it is quite useful. Allow the user to set a new default path for backup files.

3) Have an OPTION to share the data with another app and not have this be the main feature. Basically, separate these two actions in the Settings section. Call them "Create Full Backup File" and "Share Data With..." or "Send Backup File to..." or something like that.

The way it works now is confusing and I spent a bunch of time trying to figure out what was happening. I am glad I was able to save my habit data. I have data for about 4 years now. Glad I won't lose it! Thanks a lot!

**Comment by iSoron** [comment]
This is explained in the FAQ:

> **How can I export a full backup of my data?**
> Select the option "Export full backup" on the settings screen. A file will be generated, and you will be asked to choose an app to share it to. If you select an email application, you will be able to send the file as an attachment to yourself. If you select Google Drive, Dropbox or similar apps, you will be able to upload it. A copy of the generated file is also automatically saved on the SD card, inside the folder Android » data » org.isoron.uhabits » files. Be aware that this folder will be deleted when the app is uninstalled. If you would like to keep the backups on the SD card after the app is uninstalled, you should move them to another folder.

The main issue you are facing is that you do not seem to have any apps that are able to handle files.

> Open a dialog explaining that the file was saved in PATH... maybe even just a Toast saying this. Anything! [...] Have an OPTION to share the data with another app and not have this be the main feature. Basically, separate these two actions in the Settings section. Call them "Create Full Backup File" and "Share Data With..." or "Send Backup File to..." or something like that

Even if we showed the path, I would expect the vast majority of Android users not to be able to find the file. Android is making it increasingly hard to browse the local (internal storage) file system, and I think this will only get worse over time. This is the reason we combine generating the file with sharing it.

> Have an option to save the file where the user wants to save it. I have a Backup folder for all my backup files. It would require a new permission but it is quite useful. Allow the user to set a new default path for backup files.

I am fine with letting the user select a location where all backup files are stored, but this would have to be implemented through the Storage Access Framework. This would allow the user to pick a cloud folder, such as Google Drive. I am not planning to add invasive permissions to the app, such as the ability to browse/read/modify all files in the internal storage. These permissions are actually being phased out by Android, in any case. See [scoped storage](https://source.android.com/devices/storage/scoped)

**Comment by iSoron** [comment]
To summarize, I am not planning to modify the way manual backups are generated and shared at this time. I agree that picking a folder would be very useful for daily backups, but I suggest we discuss that in #178.

**Comment by landry314** [comment]
I still think that a toast popping up to tell the user that the file was just saved to FULL PATH would be quite helpful. Also, backing up the file to local storage and sharing it through an app are different actions. It is confusing to combine them...

**Comment by landry314** [comment]
At least modify the description below the Export Full Backup option to say it is doing both things. Now it says it is generating a file but when you back out of the choosing dialog you would assume the action has been canceled. That is saves a file anyway without confirming with the user is just bad design. I am sorry. I love the app but this is just messy.

**Comment by landry314** [comment]
So, the EASY fix to do is to add to the description below the "Export Full Backup" and to add a toast after the backup occurs. Not much programming and quickly solves the problem.
