### ISSUE TITLE
Improve list of translators

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#669]
## Description

In the about screen, we have a list of everyone who helped translating Loop Habit Tracker into different languages. This list has gotten very long over time, and it's now quite disorganized. It's also missing [a lot of people who have contributed more recently](https://translate.loophabits.org/project/loop-habit-tracker/activity_stream).

### Subtasks

- [x]  To make it more organized, it would be nice if the list was grouped by language. We could also potentially make each language group collapsible, so it's easier to navigate.
- [x] Modifying the list currently requires one of the developers to modify [a long XML file](https://github.com/iSoron/uhabits/blob/dev/android/uhabits-android/src/main/res/layout/about.xml). It would be nice if this list came from a file that was easier to edit. Extra points if this file could be exported automatically from our translation platform somehow. (#759)

**Comment by iSoron** [comment]
@hiqua I have updated the top post to indicate that this is partially completed. I will close this issue when we group translators by languages.

**Comment by hiqua** [comment]
Would it be ok to just have one text file per language and include in the .xml accordingly, with subsections?

For the collapsible part it seems that ExpandableListView would be the way to go.
