### ISSUE TITLE
Allow user to import/export the entire database, in native format

### ISSUE THREAD

**Issue by andunix** [iSoron/uhabits#67]
As discussed in #5, it would be nice if all habits could be exported to one CSV file. And it should be possible to re-import this file. This makes a nice backup and "new phone" solution.

For backup usage it would be necessary to also store the habit settings. So it could be better to use XML or JSON instead of CSV.

**Comment by iSoron** [comment]
What would this unified CSV look like? Currently, only the checkmarks and scores are exported, but I also plan to export streaks and frequency information in the future. These files should be useful even to people without expert knowledge in spreadsheet softwares or computer programming.

If the problem is simply about importing multiple files, you don't need to worry about that.
The app could import the whole zip file.

**Comment by iSoron** [comment]
I guess we could have a file with this format:

    checkmarks.csv
    --------------
    date,habit 1,habit 2,habit 3
    2016-01-01,0,0,1
    2016-01-02,0,1,1
    2016-01-03,1,0,1

    scores.csv
    ----------
    date,habit 1,habit 2,habit 3
    2016-01-01,0.30,0.24,0.70
    2016-01-02,0.29,0.24,0.75
    2016-01-03,0.35,0.24,0.80

Is this what you had in mind?

**Comment by andunix** [comment]
There are several usecases I'm thinking of:
- backup: daily store all data in a single file
- switching phone (move contents): manually export all to a single file which could be reimported
- export to Desktop/spreadsheet

For the first two the zip file works, if it also contains the habit settings. For the third the checkmarks.csv abouve shoud be exactly what the users need. For backup purposes, the app should be able to create the export automatically on an daily basis.

**Comment by iSoron** [comment]
I have updated your issue to focus on use cases 1 and 2. In this case, I think it would be better if the app simply allowed you to make a copy of the entire SQLite database. If you want something that is readable, but not importable, you can export as CSV files. See also the new issue #68.

**Comment by n3h3m** [comment]
@iSoron is there an option to export as Json?
