### ISSUE TITLE
Add screenshots to F-Droid

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#670]
Since [last year](https://f-droid.org/en/2019/03/26/the-latest-tab-now-highlights-good-descriptions.html), F-Droid allows apps to [provide screenshots and other graphics](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/). They require app developers to make this metadata available in the "Triple-T structure" and place it at `<module>/src/main/play/`. Loop already uses Triple-T's gradle-play-publisher plugin, but the metadata is located at a different place, so F-Droid can't find it: `android/uhabits-android/main/play`.

We should investigate how to fix this. Unfortunately, moving the metadata in our repository is not an option.

**Comment by ZilieCEO** [comment]
Hello,

I saw a solution in https://blog.fossasia.org/publish-an-open-source-app-on-fdroid.
Firstly I installed froidserver, then I cloned fdroiddata in my computer.
At this moment, I can see a folder called "repo" in froiddata,  you can put this project's APKs and all of the graphics/screenshots in this "repo" folder. Finally, you can use fdroidserver command to update your contents then make the pull requests. I think this will be successful.  This method is suitable for projects using Triple-T's gradle-play-publisher. 

I also found two other solutions for this problem in this website https://tomreyn.gitlab.io/fdroid-website/en/docs/All_About_Descriptions_Graphics_and_Screenshots/.

**Comment by iSoron** [comment]
> At this moment, I can see a folder called "repo" in froiddata, you can put this project's APKs and all of the graphics/screenshots in this "repo" folder. Finally, you can use fdroidserver command to update your contents then make the pull requests.

Thanks for looking into this, @ZilieCEO. Unfortunately, modifying `fdroiddata` does not seem to be acceptable, [according to their docs](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/):

> **Note:** This option is only meant for those who host their own repositories. If you are a developer who wants to get an app into the main F-Droid repository, do not choose this option. Specifically, screenshots may not be added to the fdroiddata repository.

**Comment by iSoron** [comment]
Having a look at [F-Droid/Server source code](https://gitlab.com/fdroid/fdroidserver/-/blob/master/fdroidserver/update.py#L982), it seems like the path is currently hardcoded. I have added a dummy `settings.gradle` in our repository's root directory to guide F-Droid towards the correct path. Let's wait a few days and see if it works. If someone has a better solution, please let me know.

I actually think F-Droid/Server should use the `subdir` path specified in our [YAML metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.isoron.uhabits.yml) when looking for these files. In fact, I would consider their current behaviour a bug. If someone wants to code this patch and submit it to them as a pull request, I think they would appreciate it. I'm not planning on doing it myself.

**Comment by iSoron** [comment]
This seems to have worked: https://f-droid.org/packages/org.isoron.uhabits/

If anyone has a better solution, please let us know. I'm closing this issue for now.

**Comment by yashpalgoyal1304** [comment]
fastlane?
