### ISSUE TITLE
Untranslated string when the question is empty

### ISSUE THREAD

**Issue by naoliv** [iSoron/uhabits#671]
I have a habit where my question is empty and with every reminder I see this:

![](https://user-images.githubusercontent.com/982338/100169027-40ff0800-2ea1-11eb-830d-7765dd47c358.png)

I personally would prefer to not have anything displayed when the question is empty (since the title/name is already enough for me).

If this is not an option, maybe this string needs to be checked if it is translatable (or if it's just missing the translation).

The app version is `1.8.9`

Obrigado!

**Comment by iSoron** [comment]
Thanks, @naoliv. This should be fixed in Loop 1.8.10, which is already available for beta testers.
