### ISSUE TITLE
Automatic Export?

### ISSUE THREAD

**Issue by merinleona** [iSoron/uhabits#677]
I would like to import my habits into my openhab instance. At the moment I use the openhab app to track some things, but this app has a much nicer interface for this kind of thing. I can export to file and then use syncthing to send the file to my server, however there seems no way to have a regular export happening without me clicking on the button. It would be great if i could schedule a daily export or even have an export happen everytime there is a change.

**Comment by hiqua** [comment]
See https://github.com/iSoron/uhabits/issues/178

**Comment by iSoron** [comment]
Duplicate of #178
