### ISSUE TITLE
Export CSV files with data for multiple habits

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#68]
In addition to the individual files already been exported, it would be nice if we could also export some files that contain data for multiple habits. For example:

    checkmarks.csv
    --------------
    date,habit 1,habit 2,habit 3
    2016-01-01,0,0,1
    2016-01-02,0,1,1
    2016-01-03,1,0,1

    scores.csv
    ----------
    date,habit 1,habit 2,habit 3
    2016-01-01,0.30,0.24,0.70
    2016-01-02,0.29,0.24,0.75
    2016-01-03,0.35,0.24,0.80

**Comment by PKompis** [comment]
I am gonna try it.

**Comment by PKompis** [comment]
It is completed i will push it in the next couple of days.

**Comment by iSoron** [comment]
@PKompis Nice, I'm looking forward to it.

**Comment by JotraN** [comment]
Hi, is this issue still open? I'd like to work on it if it is.

**Comment by iSoron** [comment]
@JotraN Yes, it's still open. Please, feel free to work on it.
