### ISSUE TITLE
Widgets no longer update

### ISSUE THREAD

**Issue by dRoskar** [iSoron/uhabits#680]
Sometime in the last few months widgets stopped updating on Android.

**Steps to reproduce:**
1. Create daily habit
2. Create Checkmark widget for that habit on the homescreen.
3. Check the widget
4. The next morning, the widget is still checked
5. Open Habits app
6. The widget has now updated and is unchecked

**specs**
Samsung Galaxy s10e (sm-g970f)
OS: Android version 10
Notifications are enabled
Application is exempt from battery optimization

**Comment by iSoron** [comment]
Thank you for the bug report, @dRoskar. Could you confirm that you still see this issue in [Loop 2.0.0-alpha](https://github.com/iSoron/uhabits/releases/tag/v2.0.0-alpha)? Before updating this alpha version, please make a full database backup, so that you can revert to the stable version later.

**Comment by dRoskar** [comment]
I've tested this over 3 nights with 2.0.0-alpha and I can confirm that the issue is fixed. I've observed that the widgets update at exactly 3AM, so I'm assuming it's fixed with the combination of https://github.com/iSoron/uhabits/pull/621 and https://github.com/iSoron/uhabits/pull/634

Something to note here: There doesn't seem to be a setting anywhere to decide whether the user prefers the update time to be midnight or 3AM.

**Comment by iSoron** [comment]
Thank you for the update, @dRoskar. If anyone else is affected by this, please let us know. Perhaps we should backport this fix to Loop 1.8, since Loop 2.0 may take a while to get released.

Regarding the 3AM update, this is indeed supposed to be an opt-in feature. I have created a new issue to track this (#694).

**Comment by iSoron** [comment]
The fix has been backported to Loop 1.8 in 4dd77463fb2, and should be fixed in Loop 1.8.12, which will become available soon. If anyone is still having this issue after the update, please let us know.
