### ISSUE TITLE
Feature requests are moving to GitHub Discussions

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#684]
In the past, we have used GitHub Issues for everything, from bug reports to feature requests. To better organize our project, I have now moved all feature requests from issues to the new [feature requests section](https://github.com/iSoron/uhabits/discussions/categories/feature-requests) of our discussion forum. This new space is more adequate for feature requests because it allows users to vote on the requests they like the most (by giving it a thumbs-up) and sort them by popularity. It also allows threaded conversations (where you can reply to a particular message to start a sub-conversation) which is better for long-lived threads with lots of messages.

Moving forward, GitHub Issues will only be used for bugs in the app (when something is clearly broken) or for open development tasks with clear requirements.

Please discuss this announcement in #683.

**Comment by hiqua** [comment]
Closing because it doesn't need to stay open.
