### ISSUE TITLE
Show "you're all done" when all habits are completed

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#700]
## Description

When all habits are completed and the user has selected "hide completed" as a filter, Loop incorrectly shows the message "You have no active habits". We should show something more cheerful, such as "You're all done for today!" instead. Originally proposed in #622.

## Implementation

The message is currently rendered by `EmptyListView`. The decision whether to show it or hide it is in `ListHabitsRootView.updateEmptyView`. We should allow `EmptyListView` to display one of several messages, and let `updateEmptyView` decide which message to show, according to the situation.

## Mockup

The mockup below uses the [umbrella-beach](https://fontawesome.com/icons/umbrella-beach?style=solid) icon from FontAwesome. Feel free to suggest an alternative one.

<img src="https://user-images.githubusercontent.com/4699657/103465880-4a338e00-4d05-11eb-8b23-2b4b84cc4314.png" width=400></img>

**Comment by vincenzopronesti** [comment]
Hello. I would be interested in tackling this issue. From the description I understand that I'm supposed to change both the string "You have no active habits" with "You're all done for today!", and the icon. But the implementation section states " We should allow `EmptyListView` to display *one of several messages*, and let `updateEmptyView` *decide which message to show, according to the situation*". My questions are:
- What are the several messages?
- How should `updateEmptyView` decide which message to show?

**Comment by hiqua** [comment]
Hi @vincenzopronesti,

@iSoron is more apt to answer, but I think the gist is:
* the messages are the two messages you've mentioned, they just appear in different situations (one when you have no habit, the other when you have habits *and* they are all completed for now)
* check whether there are habits. If not, show first message. Otherwise, check if all habits are completed, if yes, show second message

Does that answer your question?

**Comment by vincenzopronesti** [comment]
Yes, it does. Thanks @hiqua , you've been very clear. By the way, I've forked the repository because I wanted to play a little with the app. But the building process fails with this message:
```
Could not resolve all dependencies for configuration ':uhabits-android:debugRuntimeClasspath'.
Could not create task ':uhabits-android:minifyReleaseWithR8'.
Cannot query the value of this provider because it has no value available.
```
Any idea what that means?

**Comment by hiqua** [comment]
@vincenzopronesti feel free to ask on https://gitter.im/loophabits/dev or in https://github.com/iSoron/uhabits/discussions/categories/help-faq (otherwise we're going to fill this issue with irrelevant comments).

**Comment by iSoron** [comment]
@vincenzopronesti The explanation by @hiqua is correct. The task is not just to replace the current message by another one; it's to add a second message that shows up when (i) the user has "hide completed" enabled, and (ii) the user has at least one habit, and (iii) all habits have been completed for the day.

You're welcome to join the developed chat room if you need help building the project. I also recommend reading [docs/BUILD.md](https://github.com/iSoron/uhabits/blob/1869d05591ed75e3ef1aa743c0a288aa02405c1c/docs/BUILD.md) if you haven't already.

**Comment by vincenzopronesti** [comment]
Thanks both. I managed to sort it out. It turns out it was just an android studio quirk
