### ISSUE TITLE
Replace bitmap icons by vector drawables

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#701]
## Description

Loop currently uses bitmap images for all icons (for example, `ic_action_add_dark.png`). We should switch to vector drawables, which occupy less disk space. This would also allow us to have a single file for both light and dark themes.

Originally suggested in #673

## Implementation

Unless I am mistaken, all of our icons come from the clip art gallery from Android Studio, so vector versions of them can be generated using `File / New / Vector Asset / Clip Art`. If some icons are not there, feel free to replace them. We are already using [FontAwesome icons](https://fontawesome.com/) in other parts of the app, so those could be used here too.

The slightly more tricky part is making the same icon work for both light and dark themes. This can probably be achieved using `android:tint`.

## References

* https://developer.android.com/guide/topics/graphics/vector-drawable-resources
* https://medium.com/android-dev-hacks/android-vector-drawables-bfb515ba8f2e
* https://medium.com/androiddevelopers/using-vector-assets-in-android-apps-4318fd662eb9

**Comment by matkoniecz** [comment]
> vector versions of them can be generated using File / New / Vector Asset / Clip Art

Maybe it is just me, but main app icon ( https://github.com/iSoron/uhabits/blob/dev/uhabits-android/src/main/res/drawable/intro_icon_1.png ) is not there (I was looking for SVG version of it for unrelated reason).

**Comment by iSoron** [comment]
@matkoniecz You're right, the main app logo is not available as SVG. This issue is about the other icons.
