### ISSUE TITLE
Some Habits Swap Days Displayed When Time-Scrolled While Off-Screen

### ISSUE THREAD

**Issue by landry314** [iSoron/uhabits#713]
## Pre-submission checklist
- [ x] I am submitting a bug report, not a feature request.
- [ x] I am running the latest version of Loop Habit Tracker.
- [ x] I have have searched for similar issues, but did not find any matches.

## Description
Days temporarily get moved around if you scroll back in time while they are off screen then you bring them back on screen.

## Steps to reproduce
1. Go to main display of all habits
2. Scroll down so some habits are off screen. Turning into landscape mode can help you have enough habits to accomplish this.
3. Drag on the list of days to move back in time and reveal older days.
4. Scroll back up to reveal the habits that were off-screen. Some of them should be shifted a few days off.
5. To get it back to correct, simply slide the days again, they will fall back in place.

## System information
 - Phone: Pixel 3
 - Phone Operating System: Android 11
 - App version: Always newest version. I download releases on github immediately.

This can be confusing to someone, gving false information about a habit. I got quite confused until I figured it out.

**Comment by hiqua** [comment]
Could you add a screenshot of the buggy situation, so that it's easier to understand?

**Comment by landry314** [comment]
that's too personal

**Comment by landry314** [comment]
you can drag the days to see past days. if you do this while some habits are off screen then you bring them back on screen, they are shifted. try it with staggered habits alternating days. on/off but on different days. you can get it so they are on the same days and simply on the wrong days.

**Comment by hiqua** [comment]
Ok I think I managed to reproduce the bug. So when scrolling back up, the ticks are not refreshed until the days are shifted again. uhabits should not assume that the view previously computed is still valid if the days have been shifted.

**Comment by iSoron** [comment]
@landry314 Thank you for the bug report. Could you just clarify if this is affecting v1.8.11 or v2.0.0-alpha?

**Comment by landry314** [comment]
1.8.11 is what i am using

**Comment by hiqua** [comment]
> Could you just clarify if this is affecting v1.8.11 or v2.0.0-alpha?

I also reproduced it on the last `dev` version.
