### ISSUE TITLE
Explain shaded check marks on FAQ

### ISSUE THREAD

**Issue by mathstuf** [iSoron/uhabits#75]
In some of my habits, a shaded check is shown. What is the difference between it and a shaded X?

**Comment by iSoron** [comment]
A shaded check mark appears when there is no repetition on that day, but a repetition was not expected in any case. For example, if you have a habit that repeats one time every week, and you perform it on Monday, then a shaded check mark will appear on Tuesday.

Maybe this should be added to the FAQ?

**Comment by mathstuf** [comment]
Ah, OK, that makes sense. Thanks. Documenting it would be great.

**Comment by iSoron** [comment]
Added. See [FAQ](http://loophabits.org/faq.html).
