### ISSUE TITLE
Validation errors in dark theme are unreadable

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#757]
## Description
When the user tries to save a habit, but some data is missing, the app shows validation errors with a brief description of the problem. In the dark theme, the error messages are shown as black text on black background, which makes them completely unreadable. We should make the text white on black instead.

## Steps to reproduce
1. Open the app
2. Switch to the dark theme
3. Click "add new habit"
4. Click "save" without typing any data

## Screenshots

![Screenshot_1612114857](https://user-images.githubusercontent.com/4699657/106392874-7819fa00-63b9-11eb-9668-a11934af6836.png)

## System information
 - Phone: Emulator
 - Phone Operating System: Android 10
 - App version: e4121b2

**Comment by hiqua** [comment]
Relevant:
* https://stackoverflow.com/a/17269203
* https://devdeeds.com/change-color-seterror-method/
