### ISSUE TITLE
Widgets do not expand to occupy all space available and text is too small

### ISSUE THREAD

**Issue by katrinleinweber** [iSoron/uhabits#76]
maybe related to #4 

When using the grid size `condensed` on [an Samsung S4 mini with CyanogenMod 12.1](http://wiki.cyanogenmod.org/w/Serranoltexx_Info), the checkmark widget titles are extremely small; maybe 4pt. At the same time some space is available around the checkmarks:

![screenshot_2016-04-05-21-15-10](https://cloud.githubusercontent.com/assets/9948149/14294977/eea2b044-fb73-11e5-87ca-21ddbb233896.png)
 
Please consider increasing the font size to maybe a bit less than the  `Habit strength` diagram titles. The same request could be made for the label sizes within the diagram.

**Comment by iSoron** [comment]
Thank you for opening this issue. The underlying cause is that Android tries to make sure that the widgets fit in both landscape and portrait mode at the same time, so they do not fully expand. There are some workarounds.
