### ISSUE TITLE
Import from habit bull export fails

### ISSUE THREAD

**Issue by dadatuputi** [iSoron/uhabits#762]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
Importing a newly exported habit bull csv fails

## Steps to reproduce
1. Export habit bull csv
2. Import into Habits
3. See error

## System information
 - Phone: S20 FE
 - Phone Operating System: 
 - App version:

**Comment by hiqua** [comment]
Which versions do you use? Habit bull / Loop Habit Tracker?

**Comment by dadatuputi** [comment]
HabitBull 1.5.15.

**Comment by hiqua** [comment]
Thanks! If you have a minimal CSV example that fails to be imported that could also speed up the debugging.

**Comment by dadatuputi** [comment]
Here you go: 
[HabitBullData.zip](https://github.com/iSoron/uhabits/files/5959196/HabitBullData.zip)

**Comment by hiqua** [comment]
Thanks!

The problem seems to be the date format. Loop Habit Tracker expects `$year-$month-$day`:

In your CSV, it seems to be `$month/$day/$year/` instead. If you switch these manually you should be able to import your habits.

The values `-2.15E+09` are also weird, but the code seems to just ignore these values so that should be fine.

**Comment by iSoron** [comment]
@dadatuputi Thank you for the bug report and for the sample CSV file. They are very helpful.

@hiqua Nice debugging. It looks like they are now generating CSV files according to the user locale. Perhaps we should try both formats (`YYYY-MM-DD` and current locale).

**Comment by iSoron** [comment]
Fixed in b58af03a7ce86fd68d497e96ba37ac1d099cfe26. The fix will become available in Loop 2.0.
