### ISSUE TITLE
Add (configurable) feedback on checkmark toggle

### ISSUE THREAD

**Issue by di72nn** [iSoron/uhabits#78]
(speaking of release/1.4.0 branch)
It's hard to say whether the checkmark was set, if you use a long press to toggle: more likely you either hold it not long enough or wasting time by holding it for too long (unless you have system-wide haptic feedback enabled, which is not applicable to everyone).
Most apps have some kind of visual feedback for long-press actions: usually the action changes something on the screen, but in case of Loop you can't see the checkmark under your finger.

System-settings-independent haptic feedback would be good enough, though.

**Comment by iSoron** [comment]
My concern is that, if we start adding options to undo the system settings, we will end up needing lots of them, so I would like to avoid that. If the user has disabled haptic feedback, maybe we could display a message when the check mark is toggled.

**Comment by di72nn** [comment]
A message or a blink of some kind (for example, current line can be highlighted for a fraction of a second) would be fine. I'm not sure about toast messages, because they have 'fade in' delay and if the message text is the same, two consecutive toast messages may seem like one.

**Comment by iSoron** [comment]
Yes, that makes sense. Thank you for the suggestion. Even if we eventually add the option to override system settings for haptic feedback, it would still be nice to have a visual feedback in case the user disables it.

**Comment by di72nn** [comment]
I can't see any visual feedback, to be honest.
I run Android 4.4.4 on a device with 3″ HVGA screen - maybe the screen is too small for me to notice anything?

**Comment by iSoron** [comment]
The feedback is only visible on Android 5.0 or later. We could still add some visual feedback on pre-Lollipop, even though it would not look as nice. I will reopen this issue.

**Comment by iSoron** [comment]
As mentioned earlier, this feature is already implemented in Android Lollipop or later. Since we are dropping support for Android KitKat and earlier version of Android in the next release, I am closing this issue.
