### ISSUE TITLE
Habit strength diagram shows 0% sometimes

### ISSUE THREAD

**Issue by di72nn** [iSoron/uhabits#79]
![Screenshot](https://oc.di72nn.com/index.php/s/OqI8L6ZyXtvkWqw/download)
All the other diagrams seem to work fine.
I didn't notice any pattern in this behavior - it just shows 0% from time to time.

Not sure when it started. I use build of `release/1.4.0` branch (7bba6a8).

**Comment by iSoron** [comment]
Thank you for testing the release branch. Do let me know if you find any other problems.
