### ISSUE TITLE
The widget stopped presenting the progress in One UI 3 

### ISSUE THREAD

**Issue by giladraf** [iSoron/uhabits#790]
Hey,
First, thanks for a great app!
I have been using it for 4 years now and it's amazing!

As for the bug, I've updated my Android One UI to the 3rd version and I stopped seeing the circle with the progress on while using the widget.

Is this a known issue?

**Comment by hiqua** [comment]
The circle is the only thing missing, or is the widget completely blank? Would you mind sharing a screenshot if possible?

**Comment by giladraf** [comment]
The V and X Indiaction is also missing, see this
![Screenshot_20210212-194935_One UI Home](https://user-images.githubusercontent.com/78966523/107803699-9c87b600-6d6b-11eb-8d1b-04de2aac1513.jpg)

**Comment by hiqua** [comment]
What happens if you resize them? Does it change anything?

**Comment by giladraf** [comment]
It's not possible to resize this widget

**Comment by hiqua** [comment]
Ok, I can't reproduce it in an Android 11 emulator, so I'd blame the Samsung layer for now. I'd suggest to wait and see if they release a new version with bug fixes, and possibly revisit this bug when the v2 is out.

**Comment by iSoron** [comment]
@giladraf Thank you for the bug report. This is happening because there is not enough space in the widget for Loop to draw the progress circle. Is this the default launcher, with default settings, or have you customized it to show more rows and columns?

**Comment by giladraf** [comment]
Hi @iSoron ! I'm working with the default settings

**Comment by mh166** [comment]
I understand, you just have updated to the new OneUI version without making any changes to the widgets, right? Maybe you could try adding a new widget from scratch and see if that fixes it. If so, you'd just have to recreate them and be done with it.

**Comment by giladraf** [comment]
Yes, this is exactly what I did.

I've tried to delete all the widgets and recreate them, but it didn't solve the problem :(

**Comment by giladraf** [comment]
Hey guys, 
Any other suggestions how to solve or overcome this bug?

**Comment by iSoron** [comment]
I'm still considering how should we handle this. To clarify, this is not a bug, in the sense that Loop is intentionally hiding progress circle, as it detected that there is not enough space in the widget to render it. This is expected behavior. What is unexpected here is that Samsung has suddenly decided that the 1x1 widgets should be tiny.

An immediate work around for this change is using a more customizable launcher, such as Nova.

**Comment by hiqua** [comment]
Would it make sense to make the checkmark widget resizable?

**Comment by iSoron** [comment]
@giladraf I cannot reproduce this in Samsung Galaxy S21 running Android 11 and One UI 3.1. Please let us know what Samsung phone, One UI version and Android version are you using. Even increasing the home screen grid to 5x6 does not trigger the behavior.

@hiqua We could allow that, but I suspect that a 2x2 checkmark widget would then become too large.

**Comment by giladraf** [comment]
@iSoron - after your last msg I tried to play with the 'home screen grid' and the progress circle disappears only when the 5x5 option is selected.

What means we have a workaround - just change the grid to anything else and you can see the progress!

![Screenshot_20210223-182519_One UI Home](https://user-images.githubusercontent.com/78966523/108874720-1ab64900-7605-11eb-91c7-43b784363574.jpg)


Thank you guys!!

**Comment by hiqua** [comment]
In theory the widgets should have less space with 5x6 than with 5x5, that's weird...

@giladraf are the circles also hidden with the 4x5 setting? Could list the grid sizes for which the bug appears?

**Comment by giladraf** [comment]
I agree, but this is how it works.. the only size that doesn't show the circle is 5x5, all the rest work well.

**Comment by hiqua** [comment]
Ok so this might be more about the ratio rather than the absolute sizes.

**Comment by qbarron73** [comment]
> 
> 
> I'm still considering how should we handle this. To clarify, this is not a bug, in the sense that Loop is intentionally hiding progress circle, as it detected that there is not enough space in the widget to render it. This is expected behavior. What is unexpected here is that Samsung has suddenly decided that the 1x1 widgets should be tiny.
> 
> An immediate work around for this change is using a more customizable launcher, such as Nova.

if this is not a bug why not move to discussion like you do for a buinch of other bug reports and as your docs state to do? should be consistent

**Comment by amydrummond** [comment]
I had the same problem when I upgraded my Samsung phone and the grid solution worked for me. Considering the popularity of Samsung phones, perhaps this is FAQ-worthy?
