### ISSUE TITLE
Add strength of habit next to habit name

### ISSUE THREAD

**Issue by castor-troy** [iSoron/uhabits#80]
Feature request.

I have 6-7 habits, and I should be able to see which ones i am good at, by just looking at the dashboard. Probably adding the strength percentage next to habit name?

**Comment by iSoron** [comment]
Thank you for the suggestion. Currently, the star indicates how strong your habit is (habits with strength greater than 80% get a full star), but, judging from user feedback, this seems to be quite unclear, so we might replace it in the future.

**Comment by iSoron** [comment]
I am considering replacing the star by a little ring, similar to the one we currently have on the statistics screen. This would make the visual representation of the habit score more consistent, and hopefully more obvious. Feedback is appreciated.

![device-2016-04-21-182025](https://cloud.githubusercontent.com/assets/4699657/14726121/f4a0b78a-07ed-11e6-8ad2-533d2da82a9a.png)

**Comment by Hkly** [comment]
I like the star! 😄

**Comment by sojusnik** [comment]
Totally love your idea!

**Comment by AnderRasoVazquez** [comment]
Those rings look great!

2016-04-22 13:44 GMT+02:00 sojusnik <notifications@github.com>:

**Comment by iSoron** [comment]
I am also planning to add the rings to the check mark widgets. This is also related to issue #4. Thank you for the feedback, everyone.

![ring_check_mark_widget](https://cloud.githubusercontent.com/assets/4699657/14743757/32ec33d8-0871-11e6-9fa2-12e4f6cf0484.png)

**Comment by Hkly** [comment]
Oo actually I really like the loop for the widgets!

**Comment by iSoron** [comment]
These changes have been merged into the `dev` branch.
