### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by schirinowski** [iSoron/uhabits#800]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
Not all strings in the app are localised. As an example, when adding a habit a number of strings (e.g. Repeat, Custom..., Discard) appear untranslated when displaying Loop in German.
The list of strings on the Crowdin platform seems to be incomplete. I searched https://translate.loophabits.org/translate/loop-habit-tracker/1/en-de but did not find an entry to translate these and possibly others.

## Screenshots
![Screenshot_20210218-100412_Habits](https://user-images.githubusercontent.com/47022976/108334504-4cc54680-71d2-11eb-96b9-f7e1d676fdfb.jpg)

**Comment by hiqua** [comment]
I think this string is not used anymore in the v2, which could explain why you don't see it on transifex (check "frequency").

The edit window looks good in German in the last `dev` version, so this issue will be fixed when the v2 is released.
