### ISSUE TITLE
Cannot choose new share method for Export backup

### ISSUE THREAD

**Issue by rurowj** [iSoron/uhabits#803]
Hi there,
Love this app! I have just bought a new phone and would like to move my data over. After tapping "Export full backup" I chose to share via Bluetooth but have been unable to succesfully send the backup file over bluetooth - I just get the message "File not sent." So, I would like to share the backup file via email or Google Drive, but I can find no way of reselecting my share method. Whenever I tap an "Export" button, it automatically tries to share via Bluetooth. I would greatly appreciate help so that I do not lose my history and streaks when using my new phone. Can the app please be updated so that every time the user selects "Export" they reselect the share method? 
Thank you very much,
J

**Comment by hiqua** [comment]
@rurowj did you choose "always" when you shared via bluetooth?

That should be something you can reset at the Android level, try to find the app corresponding to the bluetooth share and find "clear defaults" or something similar.

See also: https://androidforums.com/threads/change-default-share-with.1123023/

**Comment by iSoron** [comment]
hiqua's comment is correct. You need to "clear the defaults" for the app you selected.

> Can the app please be updated so that every time the user selects "Export" they reselect the share method?

Unfortunately, Android doesn't allow us to do this.
