### ISSUE TITLE
missing translations for strength intervals

### ISSUE THREAD

**Issue by sciamano** [iSoron/uhabits#81]
There is a plot right after the "circle" with an option (top-right corner) to plot on daily, weekly, montly etc basis. The options values "Day, Week, Month, Quarter, Year" are not translated (at least in RU and DE locales)

**Comment by iSoron** [comment]
Yes, you are right. I forgot to [exttract some strings here](https://github.com/iSoron/uhabits/blob/5d808dd2e8f83558e5e4324497b2b130995cff94/app/src/main/res/values/dimens.xml#L58-64).
