### ISSUE TITLE
Widgets not working

### ISSUE THREAD

**Issue by dervisbey** [iSoron/uhabits#810]
Hello, 
Widgets dont work on my OnePlus2, LineageOS 17. When I add them to a screen, my screen turns a bit darker and the widget disappears aggain.

**Comment by hiqua** [comment]
Which version? 1.8.12?

**Comment by dervisbey** [comment]
No, 1.8.11.
I don't have an update available in the Play Store.

**Comment by hiqua** [comment]
@iSoron you might want to release 1.8.12 on the playstore.
