### ISSUE TITLE
Marking habits as completed the next day does not clear sticky notifications for the previous day

### ISSUE THREAD

**Issue by seva-luchianov** [iSoron/uhabits#855]
## Description
Sticky notifications do not clear for habits that happened on the previous day when checked off in the app.

## Steps to reproduce
1. Enable sticky notifications
2. Set a daily habit (in my case 11pm each day)
3. Do not interact with the notification or mark the habit completed till the next day
4. The next day: marking the habit completed for the previous day does not clear the notification, however checking off the same habit for the current day will clear the sticky notification (for the habit triggered on the previous day).

## Screenshots
I can provide screenshots tomorrow since the notifications were already cleared before I made this post.

## System information
 - Phone: Razer Phone 2
 - Phone OS: Android 9
 - App version: 1.8.12

**Comment by iSoron** [comment]
Thank you for the bug report, @seva-luchianov. This bug appears to have been fixed in the current development version of the app. A fix should be available in the next 2.0.x release.
