### ISSUE TITLE
PIN lock at opening of the app

### ISSUE THREAD

**Issue by tdkl** [iSoron/uhabits#86]
Convenient so that you can safely lend a phone for a minute without people seeing your bad habits 😜 

Not crucial, but would be nice to have and it usually exists in these kind of apps.

**Comment by iSoron** [comment]
Thank you for the suggestion. I have decided not to implement this feature for two reasons.

First, this is very hard to implement correctly, and once we add PIN locking, inevitably people will ask for pattern locking, fingerprint locking and so on. There are already a dozen of apps that allow you to lock any other app on your phone, using all kinds of fancy methods. For example, [this one][1]. Some modified versions of Android also allow you to do this without the need of any third-party app. [CyanogenMod][3], for example, has [folder locking][2]. I think this is the right way it should be done. The operating system should do this consistently across all apps.

Second, your phone has all kinds of private information about you, including all your emails, text messages and calendar. Locking apps individually a losing battle. I believe this is the reason why stock Android doesn't include this feature. The official solution, if you don't want your friend to read your personal information, is [screen pinning][4].

Again, thank you for the suggestion anyway.

[1]: https://play.google.com/store/apps/details?id=com.liquidum.hexlock&hl=en
[2]: http://www.androidcentral.com/folder-locking-how-it-works-and-why-it-awesome
[3]: http://www.cyanogenmod.org/
[4]: http://www.greenbot.com/article/2850373/lock-to-a-single-app-with-lollipop-s-screen-pinning.html

**Comment by tdkl** [comment]
Hey, thanks for the thorough explanation of the arguments against this implementation and I agree with your conclusion. I did know about screen pinning, but didn't know the linked app, which I'll definitely  check out. 

Also good that it exists in the issue list for the future, since I probably wasn't the only wondering about the possibility of this feature.
