### ISSUE TITLE
What's up with upgrade from F-Droid?

### ISSUE THREAD

**Issue by Villelmo** [iSoron/uhabits#862]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [ ] I am running the latest version of Loop Habit Tracker.
- [ ] I have have searched for similar issues, but did not find any matches.

## Description
I trying upgrade Loop Habit Tracker from F-Droid but the installation is failed. Actually i get the latest version 1.7.11 but don't show the latest version official from F-Droid. 

## Steps to reproduce
1. Go to F-Droid
2. Click on Updates 
3. Upgrade application 
4. Installation failed 

## Screenshots
![Screenshot_2021-03-24-09-16-21](https://user-images.githubusercontent.com/7723227/112335944-4408da00-8c82-11eb-9752-73b67c06c186.png)

## System information
 - Phone: [Samsung Galaxy S4 mini SCH-i435]
 - Phone Operating System: [Android 4.4.2]
 - App version: [1.7.11]

**Comment by hiqua** [comment]
1.7.11 is the last version supporting Android 4, after that the minimum Android version is 5. I guess the message from F-Droid could be improved.
