### ISSUE TITLE
Note why the app needs Photos/Media/Files permissions

### ISSUE THREAD

**Issue by gravyboat** [iSoron/uhabits#89]
Currently in the repo and on the store page the app doesn't note why the Photos/Media/Files permissions are required. This is the only permission that is required for the application so I think it would be great for users to know (at a glance instead of reviewing the source) what this permission is used for.

Thanks for your consideration!

**Comment by iSoron** [comment]
What makes you think we need this permission? We don't need any special permissions at all, unless you are using very old versions of Android (ICS or Jelly Bean).

**Comment by gravyboat** [comment]
I'm on KitKat (4.4) and this pops as a permission when I go to install the application.
![loop_app_permissions](https://cloud.githubusercontent.com/assets/1396878/14898775/734bd016-0d3d-11e6-8a03-a61c3a46ef76.PNG)

This is definitely an older release of Android but sadly it's as far as this phone can go unless I want to side load something.

**Comment by iSoron** [comment]
Okay, thank you for letting me know. This is just a bug or limitation of Google Play. If you install it using your phone, instead of the web interface, Google Play should not ask you for this permission.

The only versions of Android that need this permission are Ice Cream Sandwich and Jelly Bean (Android 4.0 -- 4.3).

**Comment by gravyboat** [comment]
@iSoron For sure, I'm going to close this out now since I didn't really consider how few people use the web version of the Play store. Thanks for taking the time to answer.
