### ISSUE TITLE
Add a stopwatch to help user track time spent on certain habits

### ISSUE THREAD

**Issue by Keho** [iSoron/uhabits#90]
Hello, thanks for this app. It's really useful :)

It would be nice to be able to set a (optional) timer when we define a habit.
The timer would be a chronometer (for habits like read at least 30 minutes a day) or a countdown (don't play videogames more than x)
At the begining of the day 'reading' should be uncrossed, 'playing' crossed. Each time we do the habit we start/unpause the timer (a notification for the timer would be great), when we are done we pause it. When the timer reaches the limit (30 or 0) it crosses or uncrosses the habit.

**Comment by iSoron** [comment]
This is an interesting suggestion, but I would prefer to consider it after we add support to numerical habits #42. If the user has a habit such as 'how many hours/minutes did you work on this today?', then the app could provide a timer that would increment the number automatically.
