### ISSUE TITLE
Build failed with an exception: 

### ISSUE THREAD

**Issue by luiscruz** [iSoron/uhabits#91]
I've just tried to build the latest version of dev:

```
./gradlew build
```

I get the following error message:
```
Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to ....
```

Do you have any idea how to fix this?

**Comment by iSoron** [comment]
Thank you. I had fixed this in another branch, but forgot to apply the patch to dev.

**Comment by luiscruz** [comment]
No problem ;)
