### ISSUE TITLE
"Pure black background" AMOLED option not applied in Settings

### ISSUE THREAD

**Issue by Mrnofish** [iSoron/uhabits#915]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
Despite the "Pure black" option being Enabled, the background is still grey in Settings.

## Steps to reproduce
1. Enable Dark Theme
2. Enable Pure Black 
3. Open Settings
4. Background is grey

## Screenshot

![Screenshot_1621703406](https://user-images.githubusercontent.com/4699657/119235169-d39dfe00-baf6-11eb-88ea-9d25ac03f37c.png)

## System information
 - Phone: Unknown
 - Phone Operating System: Lineage 17.1
 - App version: 2.0.1

**Comment by iSoron** [comment]
Thank you for the bug report, @Mrnofish, but we also need to know the phone, phone operating system and app version. Please add this information to your bug report, and I will reopen the issue.

**Comment by Yquas** [comment]
I have the same issue with Habits 2.0.1 from F-Droid on a MIUI 11 phone. Everything fits the pure black setting, but not the settings. At least not how I would imagine it.

**Comment by Mrnofish** [comment]
Lineage 17.1, latest version of Habits (as checked above), which should be v2.0.1.

**Comment by iSoron** [comment]
@Mrnofish Thanks, I have updated the original post and reopened the issue. PRs fixing this are welcome.

**Comment by iSoron** [comment]
Fixed in branch `hotfix/2.0.3`
