### ISSUE TITLE
Widget selection menu does not respect Theme selection

### ISSUE THREAD

**Issue by Mrnofish** [iSoron/uhabits#916]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I am running the latest version of Loop Habit Tracker.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
When configuring a widget, the selection menu is presented in white background / Light Theme, despite Dark Theme being set for both the app and the phone UI.

## Steps to reproduce
1. Enable Dark theme in your phone settings
2. Open the main app and add a new habit
3. Try to add a widget to your home screen

## Screenshots
![Screenshot_1621703721](https://user-images.githubusercontent.com/4699657/119235308-76567c80-baf7-11eb-99ae-f3421e64057a.png)

## System information
 - Phone: Unknown
 - Phone Operating System: Lineage 17.1
 - App version: 2.0.1

**Comment by iSoron** [comment]
Thank you for the bug report, @Mrnofish, but we also need to know the phone, phone operating system and app version. Please add this information to your bug report, and I will reopen the issue.

**Comment by Mesenotaur** [comment]
Why are you closing every issue which doesn't provide enough information immediately? And why are you silently closing an issue and not allowing any further discussion, like with #920 and #896?

**Comment by iSoron** [comment]
@Mesenotaur Issues #920 and #896 were moved to the Discussions tab. The other issues were closed because they are missing essential information. I will reopen them if the information is provided.

**Comment by Mrnofish** [comment]
Lineage 17.1, latest version of Habits (as checked above), which should be v2.0.1.

**Comment by Mesenotaur** [comment]
@iSoron ok, thanks for the explanation. :grinning:

**Comment by iSoron** [comment]
Added screenshot and reopened. PRs fixing this are very welcome.

**Comment by iSoron** [comment]
Fixed in branch `hotfix/2.0.3`
