### ISSUE TITLE
Error creating widget with one item

### ISSUE THREAD

**Issue by CristianKerr** [iSoron/uhabits#919]
I want to have one item next to each other. In previous versions i just put separate checkmark widgets on home screen and arranged the way i wanted. Now it is not possible because when I choose only one habit I get error: 
![Screenshot_20210521-084818__01](https://user-images.githubusercontent.com/79404036/119095224-4c775a00-ba12-11eb-94ba-8bc103492743.jpg)
I am on Android 10.

**Comment by iSoron** [comment]
Thank you for the bug report, @CristianKerr, but please create a new issue following the bug report template and adding all the required information (phone model, app version, etc).
