### ISSUE TITLE
Make numpad work better in number picker dialog 

### ISSUE THREAD

**Issue by iSoron** [iSoron/uhabits#922]
## Description

(originally proposed by @hiqua in #900)

Our current number picker dialog (shown below) uses two NumberPickers to allow the user to either type a value or scroll, whichever is the most convenient. Unfortunately our current implementation has two shortcomings:

1. Only the first NumberPicker is accessible through the numpad. For example, typing "3.15" in the numpad actually enters the value "315" because the widget does not recognize the decimal separator. It is currently completely impossible to change the focus to the second `NumberPicker` and type a number.
2. It is impossible to type fractional numbers that are not multiple of 0.05 (for example, 3.14).

This task is to:
- [ ] Make both NumberPickers focusable.
- [ ] Make the second NumberPicker have 0.01 increments instead of 0.05.
- [ ] Ensure that typing "." in the numpad switches the focus from the first NumberPicker to the second and selects the current number, so that typing "3.14" works as expected.

Note that, in some languages, the decimal separator is "," or "٫" instead of dot. An ideal implementation would work with these as well.

## Screenshot

![Screenshot_1621644720](https://user-images.githubusercontent.com/4699657/119209786-56c74180-ba6e-11eb-89aa-280b07dd7b72.png)

**Comment by sumanabhi** [comment]
Hey @iSoron,

I think I got some idea about this as well and looking to take this in my bucket of PRs.

**Comment by hiqua** [comment]
We need to allow a bunch of separators on top of the locale default to switch from one number picker to the other, because keyboards might not respect this locale, see https://stackoverflow.com/questions/3821539/decimal-separator-comma-with-numberdecimal-inputtype-in-edittext#comment80982671_34256139
