### ISSUE TITLE
Statistic Curves are a bit off then the value

### ISSUE THREAD

**Issue by dummifiedme** [iSoron/uhabits#937]
I noticed for a while now that the curve and the data in the 'Score' curve doesn't match.

If I am wrong please correct me.

-  In the image attached below, we have weekly score plot. When we look at the value, it clearly shows greater than 40% (be it Month, year or overall), but in the curve if we notice, the 'May' value is below 40. 
    - Initially I thought, it is representing the overall value ie 33.
    - But see the second screenshot of another habit. There the score is 22 (overall) and the curve is way below 20%.
---
1.  [Screenshot 1](https://user-images.githubusercontent.com/68785729/120066779-b5f00c00-c095-11eb-8a1c-e78c9fac7f9d.jpg)
---

2. [Screenshot 2](https://user-images.githubusercontent.com/68785729/120066878-475f7e00-c096-11eb-9b6d-b0ae17d770eb.jpg)

---
PS not previewing the image here itself since they are way too big.

The 'DAILY' curve shows the correct value though, but the weekly, monthly and yearly are off.
Also, if there is a problem with my understanding, please let me know :)

**Comment by iSoron** [comment]
Thank you for the bug report, but please edit your post to follow our bug report template, include all the necessary information, and I will reopen it.

**Comment by dummifiedme** [comment]
@iSoron I don't think it was a bug. It is a straight-forward problem irrespective of device, version or language. Anyway. Thanks for the reply and the app :)
Will live with it :D
