### ISSUE TITLE
Make Back-Arrow work as expected

### ISSUE THREAD

**Issue by brasilikum** [iSoron/uhabits#94]
If you tap on a widget, the app opens on the detailed view of this habit.
If you opened the app before that, then the Back-Arrow will bring you to the main menu. 
However if you did not open it beforehand, the back-arrow brings you to the launcher, which is unexpected. I would like to go to the main menu to mark that I completed this Habit today. 

Thanks to all contributors for this great app.

**Comment by iSoron** [comment]
Yes, this is a bug. Thank you for reporting.
