### ISSUE TITLE
Frequency showing as "Unknown" when "[x] times per month" is selected for Yes/No habit

### ISSUE THREAD

**Issue by kumaraish** [iSoron/uhabits#940]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have have searched for similar issues, but did not find any matches.

## Description
For a Yes/No habit, when Frequency is selected as "[x] times per month", it shows as "Unknown" on the Create/Edit screen after the dialog box is closed.

## Steps to reproduce
1. Create or edit a Yes/No Habit
2. In Frequency, select the last option - [x] times per month
3. Click Save on the dialog box
4. Frequency shows as "Unknown", while it should have shown as "[x] times per month" as it shows correctly when the third option is selected - "[x] times per week"
5. See attached screenshots

## System information
 - Phone: [Android Emulator - AVD created Google Pixel 3a]
 - Phone Operating System: [Android 10]
 - App version: [loop-2.0.0-alpha-debug]

## Screenshots
![image](https://user-images.githubusercontent.com/5192368/120099858-670caa00-c15b-11eb-8653-8a6605ee38d2.png)
![image](https://user-images.githubusercontent.com/5192368/120099867-77bd2000-c15b-11eb-9289-843c6b7bc0ee.png)

**Comment by iSoron** [comment]
Thank you for the bug report, @kumaraish. Can you still reproduce this in Loop 2.0.2? I believe it has been fixed.

**Comment by iSoron** [comment]
Closing since we received no response. If you anyone is still having this issue in Loop 2.0.2, please let us know.
