### ISSUE TITLE
Allow adding missed entries

### ISSUE THREAD

**Issue by SecUpwN** [iSoron/uhabits#95]
Hey @iSoron, I really enjoy using your app and all its statistics! Is it a **bug** or a "feature" that users are not able to add entries of habits that have been executed, but missed to check in your app? ;-) 

Seriously, the simplest solution would be if users could scroll back the time arrow with a swipe to the left and add those missed checkmarks from a few days back.

**Comment by iSoron** [comment]
Hi @SecUpwN, I'm glad you like the app. What version are you using? As of version 1.4.1, there is a button in the statistics screen, under the calendar, that allows you to put check marks as far back in time as you want. Also note that all the check marks on the main screen are editable, and that you can see a few more of them by putting your phone in landscape mode.

**Comment by SecUpwN** [comment]
I am using the bleeding edge version from F-Droid, meaning 1.4.1. Ah, found that edit button! 👍
