### ISSUE TITLE
Popup marks the wrong day

### ISSUE THREAD

**Issue by ke352802081770314** [iSoron/uhabits#969]
## Pre-submission checklist
- [X] I am submitting a bug report, not a feature request.
- [X] I have searched for similar issues, but did not find any matches.

## Description
When a popup is answered the following morning, it will mark the new day instead of the one the reminder refers to

## Steps to reproduce
0. Have a habit "brush teeth in the evening" with the question "Have you brushed your teeth this evening?" and a reminder at 2200
1. Observe the next morning that there is a reminder "Have you brushed your teeth this evening? Yes, no, Later"
2. Click on No because you know the reminder refers to last night, and you haven't.
3. Look at resulting habit list
4. Observe that yesterday remains at ? (no answer) but today was marked X for fail even though it wasn't due yet (note, long click on the wrongly entered X can only toogle between check and fail, it cannot revert to not-yet-decided which I would like to set it to because I don't know yet whether I will brush my teeth today in the evening - that's not the subject of this bug report but if I could have done so, I would have regarded it as cosmetic because a workaround exists and not bothered reporting it).

## System information
 - Phone: OnePlus 3
 - Phone Operating System: LineageOS (Android 9)
 - App version: 2.0.2

## Screenshots
not necessary

**Comment by iSoron** [comment]
Thank you for the detailed bug report, @ke352802081770314. I have successfully reproduced it. It looks like the bug only affects the "No" button. The "Yes" button correctly adds a check mark to the night before.
