### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by christianbundy** [iSoron/uhabits#97]
I'm trying to find an app where I can set non-boolean metadata, such as the time I woke up, the number of calories consumed, my weight, etc.

Is that within the scope of this project, or do you have any suggestions of other apps I should take a look at? Cheers!

**Comment by iSoron** [comment]
Hi Christian, some of these are within the scope of Loop, namely the number of calories and weight. See #42. For things like "what time of the day has such event happened", I would recommend a time tracker app.

**Comment by christianbundy** [comment]
Thanks for the quick reply. I'll check out #42 and try to find another solution for time metadata. Cheers!
