### ISSUE TITLE
Allow user to specify a duration or deadline for a habit

### ISSUE THREAD

**Issue by JoshGraham** [iSoron/uhabits#98]
(Translating some user feedback from Google Play Store)
...It'd have been better if it had the function to add habits for

1. during certain periods of time (period)
2. till certain day (d-day)

**Comment by iSoron** [comment]
Thank you for translating. I don't quite see how would this feature be useful, though. If your habit is only valid until a certain date, you can easily archive it. If anyone has more insight into this feature request, I would be glad to hear. Until then, I am keeping this closed as wont-fix.

**Comment by JoshGraham** [comment]
I'm not sure why that user left that feedback, but I'll take a wild guess.

Imaginary User's thought process : 

1. This app his easy-to-use 'Reminder' funtion.

2. 'Reminder' function is usually intergrated with calendar apps.
 2-1.That intergration is clumsy.
 2-2.If 'Reminder' is screwed up, I can get screwed up.

3. Oh, this app has nice reminder function.

4. I can use this instead of cluncky reminder of calendar!

5. Uh, but I only need to be reminded only during this period, or till this specific day.

6. Feature request!

So, not really habit of absolute terms.
But habit(reminder) with specific circumstances,

ex. of period
Remind me to buy cabbages at this supermarket because it's on sale.

ex. of d-day
Remind me to drive Mary to school till she leaves for her mother.

So, it's more-or-less Reminder feature of this app, not really habit.

Just .02 cents.
