### ISSUE TITLE
backups are still being stored in data folder even after exporting to.another path or app.

### ISSUE THREAD

**Issue by pokegamer5547** [iSoron/uhabits#982]
Confusing title ik sorry about that, what i mean is, when i click on export file for habits, it stores it in /storage/emulated/0/Android/data/org.isoron.uhabits/files/Backups even after finishing exporting or sharing it to another path or app. It should not store there like that when we exported it to another path or app.

**Comment by iSoron** [comment]
Thank you for creating this issue, but we are closing it as it does not follow our bug report template. Please edit your issue to follow our bug report template and make sure to include all the required information (description of the problem, steps to reproduce and system information).

**Comment by pokegamer5547** [comment]
> Thank you for creating this issue, but we are closing it as it does not follow our bug report template. Please edit your issue to follow our bug report template and make sure to include all the required information (description of the problem, steps to reproduce and system information).

@iSoron oh i'm really sorry about that😅. But the thing i was trying to say is related to this issue.
https://github.com/iSoron/uhabits/issues/668
I jist don't think it's a good idea to save the file in android folder. I know it helps with sharing it with others, but apps like example simple calender is able to export events in any folder just lije habits but without saving it in android folder. Maybe if possible using content provider to share the file with other apps  would be better way, that way atleast i can encrypt my file safely.
