### ISSUE TITLE
Widgets are sometimes invisible

### ISSUE THREAD

**Issue by dynobo** [iSoron/uhabits#985]
## Pre-submission checklist
- [x] I am submitting a bug report, not a feature request.
- [x] I have searched for similar issues, but did not find any matches.

## Description
First: thanks for this app! I'm using it since years, and it is super useful. The widgets also worked flawless for me.

Since version 2 I experiencing an annoying bug, where the loophabit widgets are quite often not rendered. They occupy space and can be resized, but no content is visible.
E.g. take a look at the screenshot: 2 widgets are rendered perfectly nice, but there should be 2 more widgets visible, just below them. I selected one of the two "invisible" widgets to make the resize handles appear, so you can see where it should show up.

## Steps to reproduce
Sadly I can't reliable reproduce. It happens very often after a phone reboot, sometime all widgets are affected, sometime none. Resizing a widget multiple time can make it re-appear, but not reliably.
I'd happily help testing or try out stuff to solve this.

## System information
 - Phone: Sony XA2
 - Phone Operating System: Lineage 18.1 (Android 11)
 - App version: 2.0.2

## Screenshots

![image](https://user-images.githubusercontent.com/11071876/122648715-af036900-d12a-11eb-9ab4-6bedd09dce15.png)

Thanks!

**Comment by hiqua** [comment]
Does this fix itself after some time, or does it stay like this?

What happens when this happens and you start the app?

**Comment by dynobo** [comment]
@hiqua 
It stays like this and app start doesn't seem to help. Sometimes resizing the broken widgets does help.

(After reboot, all my widget's also can take a while (30-90sec) until they show up. But I think this is a normal startup-delay and isn't a problem for me. The issue I reported here is something different.)

**Comment by iSoron** [comment]
Thank you for the bug report, @dynobo. This may be related to #965 or #966. After the widgets disappear, could you please send us a bug report from within the app (Settings / Generate bug report)?

**Comment by nobodywasishere** [comment]
This sometimes happens to me when resizing the widget. Here's my log https://paste.rs/xBw

**Comment by dynobo** [comment]
As requested in, here's my bug report: https://paste.rs/E0L

This time, none of my four widgets were rendered.

Thanks for your efforts! :)

**Comment by gesu92** [comment]
Hello I got some similar, but only with the widgets that have multiple choices, after one day (and a little more) just disappear:

![Screenshot_20210729-142212](https://user-images.githubusercontent.com/87961082/127545792-2c060595-00da-49c1-805b-7b3ff6b35018.png)

Versión 2.0.2 
Android 9

**Comment by hiqua** [comment]
@gesu92 I think that'd be a different bug with stacked widgets, maybe you should open another issue.

**Comment by hiqua** [comment]
@dynobo can you confirm that you encounter your issue with widget containing only the data for one habit (i.e. not stacked widgets)?

**Comment by dynobo** [comment]
@hiqua: Yeah, I only use widgets containing data for one habit. I don't know, if the issue with stacked widgets is related.

**Comment by gesu92** [comment]
> @gesu92 I think that'd be a different bug with stacked widgets, maybe you should open another issue. I think I might be fixing this issue right now there: #1043 so we can also wait until this PR is done and the next version is released, to see if you still have this bug.

Here: #1046

**Comment by iSoron** [comment]
We have fixed several issues related to widgets in Loop 2.0.3. The new version is already available in [GitHub Releases](https://github.com/iSoron/uhabits/releases) and should become available in F-Droid and in Google Play (Beta) in a few days.

If you are still experiencing problems with the new version of the app, please let us know, and I will reopen this issue.
